/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Vistas._Animales;

import Busqueda.VistaBusqueda;
import Control.ControlGeneral;
import Control._Animales.ControlDescendientes;
import Modelo.ModeloFincas;
import Modelo.ModeloGestorBusqueda;
import Modelo.ModeloVentanaGeneral;
import Utilidades.Utilidades;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import org.jfree.data.contour.ContourDataset;

/**
 *
 * @author MERRY
 */
public class VistaDescendientesAnimal extends javax.swing.JPanel {

    public ControlGeneral controlgen = new ControlGeneral();
    public ControlDescendientes control = new ControlDescendientes();
    public String idFinca;
    public String idMama;
    public String idAnimalConsultado;
    public String idTipoAnimal;
    public List<Map<String, String>> listaFincas;
    public List<Map<String, String>> listaTipoAnimales;
    public List<Map<String, String>> listaHijos;
    public Map<String, String> DatoHijoConsultado;
    public int banBQDAnimalesMadre;
    public int banBQDAnimales;
    ModeloGestorBusqueda objetoBusqueda;
    ModeloVentanaGeneral objetoVentana;
    public int idModulo = 222;
    /**
     * Creates new form VistaDescendientesAnimal
     */
    public VistaDescendientesAnimal() {
        initComponents();
        Utilidades.EstablecerPermisosVista2(this, idModulo, 0);
        idFinca = "";
        idTipoAnimal = "";
        idMama = "";
        listaFincas = new ArrayList<>();
        listaTipoAnimales = new ArrayList<>();
        listaHijos = new ArrayList<>();
        DatoHijoConsultado = new HashMap<>();
        CargarListaFincas();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        lblTid = new javax.swing.JLabel();
        cbFinca = new javax.swing.JComboBox();
        cbTipoAnimales = new javax.swing.JComboBox();
        lblTid2 = new javax.swing.JLabel();
        lblTid1 = new javax.swing.JLabel();
        txtNumMama = new javax.swing.JTextField();
        jSeparator6 = new javax.swing.JSeparator();
        lblBsqAnimalesMadre = new javax.swing.JLabel();
        scrpnlsDecendencia = new javax.swing.JScrollPane();
        pnlDescendencia = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        txtNumero = new javax.swing.JTextField();
        txtNumero1 = new javax.swing.JTextField();
        txtNumero2 = new javax.swing.JTextField();
        txtNumero3 = new javax.swing.JTextField();
        btnGuardar = new javax.swing.JButton();
        btnGuardar1 = new javax.swing.JButton();
        txtNumero4 = new javax.swing.JTextField();
        txtNumero5 = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        lblTid3 = new javax.swing.JLabel();
        btnAgregarAnimales = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTid.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblTid.setForeground(new java.awt.Color(59, 123, 50));
        lblTid.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblTid.setText("Animal Madre");
        add(lblTid, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, -1, -1));

        cbFinca.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        cbFinca.setForeground(new java.awt.Color(59, 123, 50));
        cbFinca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbFincaActionPerformed(evt);
            }
        });
        add(cbFinca, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, 160, 30));

        cbTipoAnimales.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        cbTipoAnimales.setForeground(new java.awt.Color(59, 123, 50));
        cbTipoAnimales.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbTipoAnimalesActionPerformed(evt);
            }
        });
        add(cbTipoAnimales, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 40, 190, 30));

        lblTid2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblTid2.setForeground(new java.awt.Color(59, 123, 50));
        lblTid2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblTid2.setText("Descendencia");
        add(lblTid2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 150, -1, -1));

        lblTid1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblTid1.setForeground(new java.awt.Color(59, 123, 50));
        lblTid1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblTid1.setText("Finca");
        add(lblTid1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));

        txtNumMama.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtNumMama.setForeground(new java.awt.Color(59, 123, 50));
        txtNumMama.setBorder(null);
        txtNumMama.setCaretColor(new java.awt.Color(59, 123, 50));
        txtNumMama.setFocusCycleRoot(true);
        txtNumMama.setSelectionColor(new java.awt.Color(59, 123, 50));
        txtNumMama.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtNumMamaFocusLost(evt);
            }
        });
        txtNumMama.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtNumMamaKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtNumMamaKeyReleased(evt);
            }
        });
        add(txtNumMama, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 110, 30));

        jSeparator6.setBackground(new java.awt.Color(59, 123, 50));
        add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 110, 10));

        lblBsqAnimalesMadre.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconos/buscar30.png"))); // NOI18N
        lblBsqAnimalesMadre.setToolTipText("Consultar Arrendatario");
        lblBsqAnimalesMadre.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblBsqAnimalesMadre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblBsqAnimalesMadreMouseClicked(evt);
            }
        });
        add(lblBsqAnimalesMadre, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 100, -1, -1));

        pnlDescendencia.setBackground(new java.awt.Color(255, 255, 255));
        pnlDescendencia.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(59, 123, 50)));
        pnlDescendencia.setLayout(new java.awt.GridBagLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(59, 123, 50)));
        jPanel1.setVerifyInputWhenFocusTarget(false);
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtNumero.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtNumero.setForeground(new java.awt.Color(59, 123, 50));
        txtNumero.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtNumero.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(59, 123, 50)), "Parto", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12), new java.awt.Color(59, 123, 50))); // NOI18N
        txtNumero.setCaretColor(new java.awt.Color(59, 123, 50));
        txtNumero.setMargin(new java.awt.Insets(2, 5, 2, 5));
        txtNumero.setSelectionColor(new java.awt.Color(59, 123, 50));
        txtNumero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNumeroActionPerformed(evt);
            }
        });
        txtNumero.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtNumeroFocusLost(evt);
            }
        });
        txtNumero.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtNumeroKeyReleased(evt);
            }
        });
        jPanel1.add(txtNumero, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 30, 60, 52));

        txtNumero1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtNumero1.setForeground(new java.awt.Color(59, 123, 50));
        txtNumero1.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtNumero1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(59, 123, 50)), "Número", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12), new java.awt.Color(59, 123, 50))); // NOI18N
        txtNumero1.setCaretColor(new java.awt.Color(59, 123, 50));
        txtNumero1.setMargin(new java.awt.Insets(2, 5, 2, 5));
        txtNumero1.setSelectionColor(new java.awt.Color(59, 123, 50));
        txtNumero1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtNumero1FocusLost(evt);
            }
        });
        txtNumero1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtNumero1KeyReleased(evt);
            }
        });
        jPanel1.add(txtNumero1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 80, 52));

        txtNumero2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtNumero2.setForeground(new java.awt.Color(59, 123, 50));
        txtNumero2.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtNumero2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(59, 123, 50)), "Genero", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12), new java.awt.Color(59, 123, 50))); // NOI18N
        txtNumero2.setCaretColor(new java.awt.Color(59, 123, 50));
        txtNumero2.setMargin(new java.awt.Insets(2, 5, 2, 5));
        txtNumero2.setSelectionColor(new java.awt.Color(59, 123, 50));
        txtNumero2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtNumero2FocusLost(evt);
            }
        });
        txtNumero2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtNumero2KeyReleased(evt);
            }
        });
        jPanel1.add(txtNumero2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 30, 80, 52));

        txtNumero3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtNumero3.setForeground(new java.awt.Color(59, 123, 50));
        txtNumero3.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtNumero3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(59, 123, 50)), "Fecha Nacimiento", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12), new java.awt.Color(59, 123, 50))); // NOI18N
        txtNumero3.setCaretColor(new java.awt.Color(59, 123, 50));
        txtNumero3.setMargin(new java.awt.Insets(2, 5, 2, 5));
        txtNumero3.setSelectionColor(new java.awt.Color(59, 123, 50));
        txtNumero3.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtNumero3FocusLost(evt);
            }
        });
        txtNumero3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtNumero3KeyReleased(evt);
            }
        });
        jPanel1.add(txtNumero3, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 30, 130, 52));

        btnGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconos/eliminar30.png"))); // NOI18N
        btnGuardar.setToolTipText("Guardar");
        btnGuardar.setBorderPainted(false);
        btnGuardar.setContentAreaFilled(false);
        btnGuardar.setMargin(new java.awt.Insets(2, 3, 2, 3));
        btnGuardar.setName("btnGuardar"); // NOI18N
        btnGuardar.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconos/guardar30_over.png"))); // NOI18N
        btnGuardar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconos/guardar30_over.png"))); // NOI18N
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        jPanel1.add(btnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 40, -1, -1));

        btnGuardar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconos/guardar30.png"))); // NOI18N
        btnGuardar1.setToolTipText("Guardar");
        btnGuardar1.setBorderPainted(false);
        btnGuardar1.setContentAreaFilled(false);
        btnGuardar1.setMargin(new java.awt.Insets(2, 3, 2, 3));
        btnGuardar1.setName("btnGuardar"); // NOI18N
        btnGuardar1.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconos/guardar30_over.png"))); // NOI18N
        btnGuardar1.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconos/guardar30_over.png"))); // NOI18N
        btnGuardar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardar1ActionPerformed(evt);
            }
        });
        jPanel1.add(btnGuardar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 40, -1, -1));

        txtNumero4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtNumero4.setForeground(new java.awt.Color(59, 123, 50));
        txtNumero4.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtNumero4.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(59, 123, 50)), "Grupo", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12), new java.awt.Color(59, 123, 50))); // NOI18N
        txtNumero4.setCaretColor(new java.awt.Color(59, 123, 50));
        txtNumero4.setMargin(new java.awt.Insets(2, 5, 2, 5));
        txtNumero4.setSelectionColor(new java.awt.Color(59, 123, 50));
        txtNumero4.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtNumero4FocusLost(evt);
            }
        });
        txtNumero4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtNumero4KeyReleased(evt);
            }
        });
        jPanel1.add(txtNumero4, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 30, 130, 52));

        txtNumero5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtNumero5.setForeground(new java.awt.Color(59, 123, 50));
        txtNumero5.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtNumero5.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(59, 123, 50)), "Desc", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12), new java.awt.Color(59, 123, 50))); // NOI18N
        txtNumero5.setCaretColor(new java.awt.Color(59, 123, 50));
        txtNumero5.setMargin(new java.awt.Insets(2, 5, 2, 5));
        txtNumero5.setSelectionColor(new java.awt.Color(59, 123, 50));
        txtNumero5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNumero5ActionPerformed(evt);
            }
        });
        txtNumero5.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtNumero5FocusLost(evt);
            }
        });
        txtNumero5.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtNumero5KeyReleased(evt);
            }
        });
        jPanel1.add(txtNumero5, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 30, 60, 52));

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        pnlDescendencia.add(jPanel1, gridBagConstraints);

        jPanel2.setBackground(new java.awt.Color(255, 102, 0));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 651, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTH;
        gridBagConstraints.weightx = 1.0;
        pnlDescendencia.add(jPanel2, gridBagConstraints);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 651, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHEAST;
        pnlDescendencia.add(jPanel3, gridBagConstraints);

        scrpnlsDecendencia.setViewportView(pnlDescendencia);

        add(scrpnlsDecendencia, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, 490, 260));

        lblTid3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblTid3.setForeground(new java.awt.Color(59, 123, 50));
        lblTid3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblTid3.setText("Tipo Animales");
        add(lblTid3, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 20, -1, -1));

        btnAgregarAnimales.setBackground(new java.awt.Color(0, 0, 204));
        btnAgregarAnimales.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconos/agregar30.png"))); // NOI18N
        btnAgregarAnimales.setToolTipText("Agregar Arrendatario");
        btnAgregarAnimales.setBorder(null);
        btnAgregarAnimales.setBorderPainted(false);
        btnAgregarAnimales.setContentAreaFilled(false);
        btnAgregarAnimales.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAgregarAnimales.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarAnimalesActionPerformed(evt);
            }
        });
        add(btnAgregarAnimales, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 140, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void cbFincaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbFincaActionPerformed
        if (cbFinca.getItemCount() > 0) {
            //EventoComboFincas();
            System.out.println("cbFinca.getSelectedIndex()--" + cbFinca.getSelectedIndex());
            if (cbFinca.getSelectedIndex() >= 0) {
                idFinca = listaFincas.get(cbFinca.getSelectedIndex()).get("ID");
                CargarListaTipoAnimales();
            } else {
                cbTipoAnimales.removeAllItems();
            }
        }
    }//GEN-LAST:event_cbFincaActionPerformed

    private void cbTipoAnimalesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbTipoAnimalesActionPerformed
        if (cbTipoAnimales.getItemCount() > 0) {
            if (cbTipoAnimales.getSelectedIndex() >= 0) {
                idTipoAnimal = listaTipoAnimales.get(cbTipoAnimales.getSelectedIndex()).get("ID");
                //EventoComboFincas();
            } else {
                
            }
        }
    }//GEN-LAST:event_cbTipoAnimalesActionPerformed

    private void txtNumMamaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNumMamaFocusLost
        //MostrarTabla();
    }//GEN-LAST:event_txtNumMamaFocusLost

    private void txtNumMamaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNumMamaKeyPressed
        if (evt.getKeyCode() == evt.VK_ENTER) {
            
        }
    }//GEN-LAST:event_txtNumMamaKeyPressed

    private void txtNumMamaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNumMamaKeyReleased
        if (txtNumMama.getText().equals("")) {
            
        }
    }//GEN-LAST:event_txtNumMamaKeyReleased

    private void lblBsqAnimalesMadreMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBsqAnimalesMadreMouseClicked
        if (banBQDAnimalesMadre == 0) {
            banBQDAnimalesMadre = 1;
            //new ventanaBusquedaPaciente(1, "IDENTIFICACION:-:NOMBRE", estadoch, this);
            if (lblBsqAnimalesMadre.isEnabled()) {
                String param = "IDFINCA:"+idFinca+"<::>IDTIPO:"+idTipoAnimal+"<::>ADD:*/ AND animal.`genero` = 'hembra' AND animal.destete = '1' /*";
                objetoBusqueda = new ModeloGestorBusqueda(this, "BQD_ANML_DESC", 1, param);
                LimpiarPropietarios();
                new VistaBusqueda(objetoBusqueda);
            }
        }
    }//GEN-LAST:event_lblBsqAnimalesMadreMouseClicked

    private void btnAgregarAnimalesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarAnimalesActionPerformed
        if (banBQDAnimales == 0) {
            banBQDAnimales = 1;
            //new ventanaBusquedaPaciente(1, "IDENTIFICACION:-:NOMBRE", estadoch, this);
            if (btnAgregarAnimales.isEnabled()) {
                String param = "IDFINCA:"+idFinca+"<::>IDTIPO:"+idTipoAnimal+"<::>ADD:*/ AND animal.id <> '"+idMama+"' /*";
                objetoBusqueda = new ModeloGestorBusqueda(this, "BQD_ANML_DESC", 2, param);
                new VistaBusqueda(objetoBusqueda);
            }
        }
    }//GEN-LAST:event_btnAgregarAnimalesActionPerformed

    private void txtNumeroFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNumeroFocusLost
        String numeroMadre = txtNumero.getText();
        Object[] datos = control.ObtenerUltimoDescendiente(numeroMadre, txtCodigoTipoAnimal.getText());
        String nroDescendiente = datos[0].toString();
        txtNumeroDescendiente.setText(nroDescendiente);

        System.out.println("mostrar->>>>" + datos[2]);
        List<Map<String, String>> animal = new ArrayList<Map<String, String>>();
        animal = (List<Map<String, String>>) datos[2];
        if (animal.size() > 0) {
            txtNumeroMadre = animal.get(0).get("id");
        }

        boolean mostrar = true;
        lblNumeroDescendiente.setVisible(mostrar);
        txtNumeroDescendiente.setVisible(mostrar);
    }//GEN-LAST:event_txtNumeroFocusLost

    private void txtNumeroKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNumeroKeyReleased
        if (!chkAdoptivo.isSelected()) {
            String numeroMadre = txtNumero.getText().trim();
            if (!numeroMadre.isEmpty()) {
                txtNumero.setText(numeroMadre);
            }
        }
    }//GEN-LAST:event_txtNumeroKeyReleased

    private void txtNumero1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNumero1FocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNumero1FocusLost

    private void txtNumero1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNumero1KeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNumero1KeyReleased

    private void txtNumero2FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNumero2FocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNumero2FocusLost

    private void txtNumero2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNumero2KeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNumero2KeyReleased

    private void txtNumero3FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNumero3FocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNumero3FocusLost

    private void txtNumero3KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNumero3KeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNumero3KeyReleased

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        Guardar();
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnGuardar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardar1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnGuardar1ActionPerformed

    private void txtNumero4FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNumero4FocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNumero4FocusLost

    private void txtNumero4KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNumero4KeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNumero4KeyReleased

    private void txtNumeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNumeroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNumeroActionPerformed

    private void txtNumero5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNumero5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNumero5ActionPerformed

    private void txtNumero5FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNumero5FocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNumero5FocusLost

    private void txtNumero5KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNumero5KeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNumero5KeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnAgregarAnimales;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnGuardar1;
    public javax.swing.JComboBox cbFinca;
    public javax.swing.JComboBox cbTipoAnimales;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JLabel lblBsqAnimalesMadre;
    private javax.swing.JLabel lblTid;
    private javax.swing.JLabel lblTid1;
    private javax.swing.JLabel lblTid2;
    private javax.swing.JLabel lblTid3;
    private javax.swing.JPanel pnlDescendencia;
    private javax.swing.JScrollPane scrpnlsDecendencia;
    public javax.swing.JTextField txtNumMama;
    public javax.swing.JTextField txtNumero;
    public javax.swing.JTextField txtNumero1;
    public javax.swing.JTextField txtNumero2;
    public javax.swing.JTextField txtNumero3;
    public javax.swing.JTextField txtNumero4;
    public javax.swing.JTextField txtNumero5;
    // End of variables declaration//GEN-END:variables

    private void CargarListaFincas() {
        listaFincas = controlgen.GetComboBox("SELECT '-1' AS ID, 'Seleccionar' AS DESCRIPCION\n"
                + "UNION\n"
                + "SELECT `id` AS ID, `descripcion` AS DESCRIPCION\n"
                + "FROM `fincas`\n"
                + "/*UNION \n"
                + "SELECT 'ALL' AS ID, 'TODOS' AS DESCRIPCION*/");

        Utilidades.LlenarComboBox(cbFinca, listaFincas, "DESCRIPCION");
        cbFinca.setSelectedIndex(1);
        CargarListaTipoAnimales();
        //EventoComboFincas();
    }

    private void CargarListaTipoAnimales() {
        listaTipoAnimales = controlgen.GetComboBox("SELECT '-1' AS ID, 'Seleccionar' AS DESCRIPCION\n"
                + "UNION\n"
                + "SELECT id AS ID, descripcion AS DESCRIPCION\n"
                + "FROM `tipo_animales`\n"
                + "WHERE id_finca = '" + idFinca + "' AND estado = 'Activo'\n"
                + "ORDER BY id ASC");

        Utilidades.LlenarComboBox(cbTipoAnimales, listaTipoAnimales, "DESCRIPCION");
        cbTipoAnimales.setSelectedIndex(0);
        //EventoComboFincas();
    }
    private void LimpiarPropietarios() {
        idMama = "";
        txtNumMama.setText("");
    }
    
     //<editor-fold defaultstate="collapsed" desc="Metodo Busqueda Retorno">
    public void RetornoBusqueda(ModeloGestorBusqueda objeto, Map<String, String> retorno) {

        if (objeto.getOpcion() == 0) {// DEFAULT VISTA__VENTANA__
//            id_Finca = Integer.parseInt(retorno.get("ID"));
//            modelo = (ModeloFincas) ((ArrayList<ModeloFincas>) controlFinca.ObtenerDatosKey("" + id_Finca)).get(0);
//
//            txtDescripcion.setText(Utilidades.decodificarElemento(modelo.getDescripcion()));
//            txtDireccion.setText(Utilidades.decodificarElemento(modelo.getDireccion()));
//            txtAreaT.setText("" + modelo.getAreat());
//            lblIdPropietario.setText("" + modelo.getId_propietario());
//            txtPropietarios.setText(Utilidades.decodificarElemento(modelo.getPropietario()));
//
//            for (int i = 0; i < Tipo_moneda.size(); i++) {
//                if (Tipo_moneda.get(i).get("ID").equals(modelo.getIdTipoMoneda())) {
//                    cbTipoMoneda.setSelectedItem(Tipo_moneda.get(i).get("DESCRIPCION"));
//                    break;
//                }
//            }
        } else if (objeto.getOpcion() == 1) {// Numero animal
            idMama = "" + retorno.get("ID_ANIMAL");
            txtNumMama.setText(Utilidades.decodificarElemento(retorno.get("NUMERO_ANIMAL")));
            banBQDAnimalesMadre = 0;
        } else if (objeto.getOpcion() == 2) {// Numero Hijo
            idAnimalConsultado = "" + retorno.get("ID_ANIMAL");
            banBQDAnimales = 0;
            DatoHijoConsultado = control.getDatosHijo(idAnimalConsultado);
            AgregarHijoAnimal();
            idAnimalConsultado = "";
        }
    } 
    
    //</editor-fold>

    private void AgregarHijoAnimal() {
        
    }
    
}
