/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Vistas._Animales;

import Busqueda.VistaBusqueda;
import Control.ControlGeneral;
import Control._Animales.ControlDescendientes;
import Modelo.ModeloFincas;
import Modelo.ModeloGestorBusqueda;
import Modelo.ModeloVentanaGeneral;
import Utilidades.Utilidades;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import org.jfree.data.contour.ContourDataset;

/**
 *
 * @author MERRY
 */
public class VistaDescendientesAnimal extends javax.swing.JPanel {

    public ControlGeneral controlgen = new ControlGeneral();
    public ControlDescendientes control = new ControlDescendientes();
    public String idFinca;
    public String idMama;
    public String idAnimalConsultado;
    public String idTipoAnimal;
    public List<Map<String, String>> listaFincas;
    public List<Map<String, String>> listaTipoAnimales;
    public List<Map<String, String>> listaHijos;
    public Map<String, String> DatoHijoConsultado;
    public int banBQDAnimalesMadre;
    public int banBQDAnimales;
    ModeloGestorBusqueda objetoBusqueda;
    ModeloVentanaGeneral objetoVentana;
    public int idModulo = 222;
    /**
     * Creates new form VistaDescendientesAnimal
     */
    public VistaDescendientesAnimal() {
        initComponents();
        Utilidades.EstablecerPermisosVista2(this, idModulo, 0);
        idFinca = "";
        idTipoAnimal = "";
        idMama = "";
        listaFincas = new ArrayList<>();
        listaTipoAnimales = new ArrayList<>();
        listaHijos = new ArrayList<>();
        DatoHijoConsultado = new HashMap<>();
        CargarListaFincas();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        lblTid = new javax.swing.JLabel();
        cbFinca = new javax.swing.JComboBox();
        cbTipoAnimales = new javax.swing.JComboBox();
        lblTid2 = new javax.swing.JLabel();
        lblTid1 = new javax.swing.JLabel();
        txtNumMama = new javax.swing.JTextField();
        jSeparator6 = new javax.swing.JSeparator();
        lblBsqAnimalesMadre = new javax.swing.JLabel();
        scrpnlsDecendencia = new javax.swing.JScrollPane();
        pnlDescendencia = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        txtNumero = new javax.swing.JTextField();
        txtNumero1 = new javax.swing.JTextField();
        txtNumero2 = new javax.swing.JTextField();
        txtNumero3 = new javax.swing.JTextField();
        txtNumero4 = new javax.swing.JTextField();
        txtNumero5 = new javax.swing.JTextField();
        panelAcciones = new javax.swing.JPanel();
        btnGuardar = new javax.swing.JButton();
        btnGuardar1 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        txtNumero6 = new javax.swing.JTextField();
        txtNumero7 = new javax.swing.JTextField();
        txtNumero8 = new javax.swing.JTextField();
        txtNumero9 = new javax.swing.JTextField();
        txtNumero10 = new javax.swing.JTextField();
        txtNumero11 = new javax.swing.JTextField();
        panelAcciones1 = new javax.swing.JPanel();
        btnGuardar2 = new javax.swing.JButton();
        btnGuardar3 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        txtNumero12 = new javax.swing.JTextField();
        txtNumero13 = new javax.swing.JTextField();
        txtNumero14 = new javax.swing.JTextField();
        txtNumero15 = new javax.swing.JTextField();
        txtNumero16 = new javax.swing.JTextField();
        txtNumero17 = new javax.swing.JTextField();
        panelAcciones2 = new javax.swing.JPanel();
        btnGuardar4 = new javax.swing.JButton();
        btnGuardar5 = new javax.swing.JButton();
        lblTid3 = new javax.swing.JLabel();
        btnAgregarAnimales = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTid.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblTid.setForeground(new java.awt.Color(59, 123, 50));
        lblTid.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblTid.setText("Animal Madre");
        add(lblTid, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, -1, -1));

        cbFinca.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        cbFinca.setForeground(new java.awt.Color(59, 123, 50));
        cbFinca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbFincaActionPerformed(evt);
            }
        });
        add(cbFinca, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, 160, 30));

        cbTipoAnimales.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        cbTipoAnimales.setForeground(new java.awt.Color(59, 123, 50));
        cbTipoAnimales.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbTipoAnimalesActionPerformed(evt);
            }
        });
        add(cbTipoAnimales, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 40, 190, 30));

        lblTid2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblTid2.setForeground(new java.awt.Color(59, 123, 50));
        lblTid2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblTid2.setText("Descendencia");
        add(lblTid2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 150, -1, -1));

        lblTid1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblTid1.setForeground(new java.awt.Color(59, 123, 50));
        lblTid1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblTid1.setText("Finca");
        add(lblTid1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));

        txtNumMama.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtNumMama.setForeground(new java.awt.Color(59, 123, 50));
        txtNumMama.setBorder(null);
        txtNumMama.setCaretColor(new java.awt.Color(59, 123, 50));
        txtNumMama.setFocusCycleRoot(true);
        txtNumMama.setSelectionColor(new java.awt.Color(59, 123, 50));
        txtNumMama.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtNumMamaFocusLost(evt);
            }
        });
        txtNumMama.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtNumMamaKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtNumMamaKeyReleased(evt);
            }
        });
        add(txtNumMama, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 110, 30));

        jSeparator6.setBackground(new java.awt.Color(59, 123, 50));
        add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 110, 10));

        lblBsqAnimalesMadre.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconos/buscar30.png"))); // NOI18N
        lblBsqAnimalesMadre.setToolTipText("Consultar Arrendatario");
        lblBsqAnimalesMadre.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblBsqAnimalesMadre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblBsqAnimalesMadreMouseClicked(evt);
            }
        });
        add(lblBsqAnimalesMadre, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 100, -1, -1));

        pnlDescendencia.setBackground(new java.awt.Color(255, 255, 255));
        pnlDescendencia.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(59, 123, 50)));
        pnlDescendencia.setLayout(new java.awt.GridBagLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(59, 123, 50)));
        jPanel1.setVerifyInputWhenFocusTarget(false);
        java.awt.GridBagLayout jPanel1Layout = new java.awt.GridBagLayout();
        jPanel1Layout.columnWidths = new int[] {0, 15, 0, 15, 0, 15, 0, 15, 0, 15, 0, 15, 0, 15, 0};
        jPanel1Layout.rowHeights = new int[] {0};
        jPanel1.setLayout(jPanel1Layout);

        txtNumero.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtNumero.setForeground(new java.awt.Color(59, 123, 50));
        txtNumero.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtNumero.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(59, 123, 50)), "Parto", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12), new java.awt.Color(59, 123, 50))); // NOI18N
        txtNumero.setCaretColor(new java.awt.Color(59, 123, 50));
        txtNumero.setMargin(new java.awt.Insets(2, 5, 2, 5));
        txtNumero.setSelectionColor(new java.awt.Color(59, 123, 50));
        txtNumero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNumeroActionPerformed(evt);
            }
        });
        txtNumero.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtNumeroFocusLost(evt);
            }
        });
        txtNumero.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtNumeroKeyReleased(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 10;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipady = 15;
        gridBagConstraints.weightx = 0.125;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 10, 0);
        jPanel1.add(txtNumero, gridBagConstraints);

        txtNumero1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtNumero1.setForeground(new java.awt.Color(59, 123, 50));
        txtNumero1.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtNumero1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(59, 123, 50)), "Número", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12), new java.awt.Color(59, 123, 50))); // NOI18N
        txtNumero1.setCaretColor(new java.awt.Color(59, 123, 50));
        txtNumero1.setMargin(new java.awt.Insets(2, 5, 2, 5));
        txtNumero1.setSelectionColor(new java.awt.Color(59, 123, 50));
        txtNumero1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtNumero1FocusLost(evt);
            }
        });
        txtNumero1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtNumero1KeyReleased(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipady = 15;
        gridBagConstraints.weightx = 0.125;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 0);
        jPanel1.add(txtNumero1, gridBagConstraints);

        txtNumero2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtNumero2.setForeground(new java.awt.Color(59, 123, 50));
        txtNumero2.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtNumero2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(59, 123, 50)), "Genero", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12), new java.awt.Color(59, 123, 50))); // NOI18N
        txtNumero2.setCaretColor(new java.awt.Color(59, 123, 50));
        txtNumero2.setMargin(new java.awt.Insets(2, 5, 2, 5));
        txtNumero2.setSelectionColor(new java.awt.Color(59, 123, 50));
        txtNumero2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtNumero2FocusLost(evt);
            }
        });
        txtNumero2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtNumero2KeyReleased(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipady = 15;
        gridBagConstraints.weightx = 0.125;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 10, 0);
        jPanel1.add(txtNumero2, gridBagConstraints);

        txtNumero3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtNumero3.setForeground(new java.awt.Color(59, 123, 50));
        txtNumero3.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtNumero3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(59, 123, 50)), "Fecha Nacimiento", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12), new java.awt.Color(59, 123, 50))); // NOI18N
        txtNumero3.setCaretColor(new java.awt.Color(59, 123, 50));
        txtNumero3.setMargin(new java.awt.Insets(2, 5, 2, 5));
        txtNumero3.setSelectionColor(new java.awt.Color(59, 123, 50));
        txtNumero3.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtNumero3FocusLost(evt);
            }
        });
        txtNumero3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtNumero3KeyReleased(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipady = 15;
        gridBagConstraints.weightx = 0.25;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 10, 0);
        jPanel1.add(txtNumero3, gridBagConstraints);

        txtNumero4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtNumero4.setForeground(new java.awt.Color(59, 123, 50));
        txtNumero4.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtNumero4.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(59, 123, 50)), "Grupo", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12), new java.awt.Color(59, 123, 50))); // NOI18N
        txtNumero4.setCaretColor(new java.awt.Color(59, 123, 50));
        txtNumero4.setMargin(new java.awt.Insets(2, 5, 2, 5));
        txtNumero4.setSelectionColor(new java.awt.Color(59, 123, 50));
        txtNumero4.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtNumero4FocusLost(evt);
            }
        });
        txtNumero4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtNumero4KeyReleased(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipady = 15;
        gridBagConstraints.weightx = 0.25;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 10, 0);
        jPanel1.add(txtNumero4, gridBagConstraints);

        txtNumero5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtNumero5.setForeground(new java.awt.Color(59, 123, 50));
        txtNumero5.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtNumero5.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(59, 123, 50)), "Desc", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12), new java.awt.Color(59, 123, 50))); // NOI18N
        txtNumero5.setCaretColor(new java.awt.Color(59, 123, 50));
        txtNumero5.setMargin(new java.awt.Insets(2, 5, 2, 5));
        txtNumero5.setSelectionColor(new java.awt.Color(59, 123, 50));
        txtNumero5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNumero5ActionPerformed(evt);
            }
        });
        txtNumero5.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtNumero5FocusLost(evt);
            }
        });
        txtNumero5.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtNumero5KeyReleased(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 8;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipady = 15;
        gridBagConstraints.weightx = 0.125;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 10, 0);
        jPanel1.add(txtNumero5, gridBagConstraints);

        panelAcciones.setBackground(new java.awt.Color(255, 255, 255));
        panelAcciones.setLayout(new java.awt.GridBagLayout());

        btnGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconos/eliminar30.png"))); // NOI18N
        btnGuardar.setToolTipText("Guardar");
        btnGuardar.setBorderPainted(false);
        btnGuardar.setContentAreaFilled(false);
        btnGuardar.setMargin(new java.awt.Insets(2, 3, 2, 3));
        btnGuardar.setName("btnGuardar"); // NOI18N
        btnGuardar.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconos/guardar30_over.png"))); // NOI18N
        btnGuardar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconos/guardar30_over.png"))); // NOI18N
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        panelAcciones.add(btnGuardar, gridBagConstraints);

        btnGuardar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconos/guardar30.png"))); // NOI18N
        btnGuardar1.setToolTipText("Guardar");
        btnGuardar1.setBorderPainted(false);
        btnGuardar1.setContentAreaFilled(false);
        btnGuardar1.setMargin(new java.awt.Insets(2, 3, 2, 3));
        btnGuardar1.setName("btnGuardar"); // NOI18N
        btnGuardar1.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconos/guardar30_over.png"))); // NOI18N
        btnGuardar1.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconos/guardar30_over.png"))); // NOI18N
        btnGuardar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardar1ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        panelAcciones.add(btnGuardar1, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 12;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 10);
        jPanel1.add(panelAcciones, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        pnlDescendencia.add(jPanel1, gridBagConstraints);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(59, 123, 50)));
        jPanel4.setVerifyInputWhenFocusTarget(false);
        jPanel4.setLayout(new java.awt.GridBagLayout());

        txtNumero6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtNumero6.setForeground(new java.awt.Color(59, 123, 50));
        txtNumero6.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtNumero6.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(59, 123, 50)), "Parto", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12), new java.awt.Color(59, 123, 50))); // NOI18N
        txtNumero6.setCaretColor(new java.awt.Color(59, 123, 50));
        txtNumero6.setMargin(new java.awt.Insets(2, 5, 2, 5));
        txtNumero6.setSelectionColor(new java.awt.Color(59, 123, 50));
        txtNumero6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNumero6ActionPerformed(evt);
            }
        });
        txtNumero6.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtNumero6FocusLost(evt);
            }
        });
        txtNumero6.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtNumero6KeyReleased(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 10;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipady = 15;
        gridBagConstraints.weightx = 0.125;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 10, 0);
        jPanel4.add(txtNumero6, gridBagConstraints);

        txtNumero7.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtNumero7.setForeground(new java.awt.Color(59, 123, 50));
        txtNumero7.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtNumero7.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(59, 123, 50)), "Número", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12), new java.awt.Color(59, 123, 50))); // NOI18N
        txtNumero7.setCaretColor(new java.awt.Color(59, 123, 50));
        txtNumero7.setMargin(new java.awt.Insets(2, 5, 2, 5));
        txtNumero7.setSelectionColor(new java.awt.Color(59, 123, 50));
        txtNumero7.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtNumero7FocusLost(evt);
            }
        });
        txtNumero7.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtNumero7KeyReleased(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipady = 15;
        gridBagConstraints.weightx = 0.125;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 0);
        jPanel4.add(txtNumero7, gridBagConstraints);

        txtNumero8.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtNumero8.setForeground(new java.awt.Color(59, 123, 50));
        txtNumero8.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtNumero8.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(59, 123, 50)), "Genero", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12), new java.awt.Color(59, 123, 50))); // NOI18N
        txtNumero8.setCaretColor(new java.awt.Color(59, 123, 50));
        txtNumero8.setMargin(new java.awt.Insets(2, 5, 2, 5));
        txtNumero8.setSelectionColor(new java.awt.Color(59, 123, 50));
        txtNumero8.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtNumero8FocusLost(evt);
            }
        });
        txtNumero8.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtNumero8KeyReleased(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipady = 15;
        gridBagConstraints.weightx = 0.125;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 10, 0);
        jPanel4.add(txtNumero8, gridBagConstraints);

        txtNumero9.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtNumero9.setForeground(new java.awt.Color(59, 123, 50));
        txtNumero9.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtNumero9.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(59, 123, 50)), "Fecha Nacimiento", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12), new java.awt.Color(59, 123, 50))); // NOI18N
        txtNumero9.setCaretColor(new java.awt.Color(59, 123, 50));
        txtNumero9.setMargin(new java.awt.Insets(2, 5, 2, 5));
        txtNumero9.setSelectionColor(new java.awt.Color(59, 123, 50));
        txtNumero9.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtNumero9FocusLost(evt);
            }
        });
        txtNumero9.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtNumero9KeyReleased(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipady = 15;
        gridBagConstraints.weightx = 0.25;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 10, 0);
        jPanel4.add(txtNumero9, gridBagConstraints);

        txtNumero10.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtNumero10.setForeground(new java.awt.Color(59, 123, 50));
        txtNumero10.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtNumero10.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(59, 123, 50)), "Grupo", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12), new java.awt.Color(59, 123, 50))); // NOI18N
        txtNumero10.setCaretColor(new java.awt.Color(59, 123, 50));
        txtNumero10.setMargin(new java.awt.Insets(2, 5, 2, 5));
        txtNumero10.setSelectionColor(new java.awt.Color(59, 123, 50));
        txtNumero10.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtNumero10FocusLost(evt);
            }
        });
        txtNumero10.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtNumero10KeyReleased(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipady = 15;
        gridBagConstraints.weightx = 0.25;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 10, 0);
        jPanel4.add(txtNumero10, gridBagConstraints);

        txtNumero11.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtNumero11.setForeground(new java.awt.Color(59, 123, 50));
        txtNumero11.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtNumero11.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(59, 123, 50)), "Desc", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12), new java.awt.Color(59, 123, 50))); // NOI18N
        txtNumero11.setCaretColor(new java.awt.Color(59, 123, 50));
        txtNumero11.setMargin(new java.awt.Insets(2, 5, 2, 5));
        txtNumero11.setSelectionColor(new java.awt.Color(59, 123, 50));
        txtNumero11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNumero11ActionPerformed(evt);
            }
        });
        txtNumero11.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtNumero11FocusLost(evt);
            }
        });
        txtNumero11.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtNumero11KeyReleased(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 8;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipady = 15;
        gridBagConstraints.weightx = 0.125;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 10, 0);
        jPanel4.add(txtNumero11, gridBagConstraints);

        panelAcciones1.setBackground(new java.awt.Color(255, 255, 255));
        panelAcciones1.setLayout(new java.awt.GridBagLayout());

        btnGuardar2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconos/eliminar30.png"))); // NOI18N
        btnGuardar2.setToolTipText("Guardar");
        btnGuardar2.setBorderPainted(false);
        btnGuardar2.setContentAreaFilled(false);
        btnGuardar2.setMargin(new java.awt.Insets(2, 3, 2, 3));
        btnGuardar2.setName("btnGuardar"); // NOI18N
        btnGuardar2.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconos/guardar30_over.png"))); // NOI18N
        btnGuardar2.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconos/guardar30_over.png"))); // NOI18N
        btnGuardar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardar2ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        panelAcciones1.add(btnGuardar2, gridBagConstraints);

        btnGuardar3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconos/guardar30.png"))); // NOI18N
        btnGuardar3.setToolTipText("Guardar");
        btnGuardar3.setBorderPainted(false);
        btnGuardar3.setContentAreaFilled(false);
        btnGuardar3.setMargin(new java.awt.Insets(2, 3, 2, 3));
        btnGuardar3.setName("btnGuardar"); // NOI18N
        btnGuardar3.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconos/guardar30_over.png"))); // NOI18N
        btnGuardar3.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconos/guardar30_over.png"))); // NOI18N
        btnGuardar3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardar3ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        panelAcciones1.add(btnGuardar3, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 12;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 10);
        jPanel4.add(panelAcciones1, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        pnlDescendencia.add(jPanel4, gridBagConstraints);

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(59, 123, 50)));
        jPanel5.setVerifyInputWhenFocusTarget(false);
        jPanel5.setLayout(new java.awt.GridBagLayout());

        txtNumero12.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtNumero12.setForeground(new java.awt.Color(59, 123, 50));
        txtNumero12.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtNumero12.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(59, 123, 50)), "Parto", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12), new java.awt.Color(59, 123, 50))); // NOI18N
        txtNumero12.setCaretColor(new java.awt.Color(59, 123, 50));
        txtNumero12.setMargin(new java.awt.Insets(2, 5, 2, 5));
        txtNumero12.setSelectionColor(new java.awt.Color(59, 123, 50));
        txtNumero12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNumero12ActionPerformed(evt);
            }
        });
        txtNumero12.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtNumero12FocusLost(evt);
            }
        });
        txtNumero12.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtNumero12KeyReleased(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 10;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipady = 15;
        gridBagConstraints.weightx = 0.125;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 10, 0);
        jPanel5.add(txtNumero12, gridBagConstraints);

        txtNumero13.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtNumero13.setForeground(new java.awt.Color(59, 123, 50));
        txtNumero13.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtNumero13.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(59, 123, 50)), "Número", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12), new java.awt.Color(59, 123, 50))); // NOI18N
        txtNumero13.setCaretColor(new java.awt.Color(59, 123, 50));
        txtNumero13.setMargin(new java.awt.Insets(2, 5, 2, 5));
        txtNumero13.setSelectionColor(new java.awt.Color(59, 123, 50));
        txtNumero13.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtNumero13FocusLost(evt);
            }
        });
        txtNumero13.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtNumero13KeyReleased(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipady = 15;
        gridBagConstraints.weightx = 0.125;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 0);
        jPanel5.add(txtNumero13, gridBagConstraints);

        txtNumero14.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtNumero14.setForeground(new java.awt.Color(59, 123, 50));
        txtNumero14.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtNumero14.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(59, 123, 50)), "Genero", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12), new java.awt.Color(59, 123, 50))); // NOI18N
        txtNumero14.setCaretColor(new java.awt.Color(59, 123, 50));
        txtNumero14.setMargin(new java.awt.Insets(2, 5, 2, 5));
        txtNumero14.setSelectionColor(new java.awt.Color(59, 123, 50));
        txtNumero14.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtNumero14FocusLost(evt);
            }
        });
        txtNumero14.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtNumero14KeyReleased(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipady = 15;
        gridBagConstraints.weightx = 0.125;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 10, 0);
        jPanel5.add(txtNumero14, gridBagConstraints);

        txtNumero15.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtNumero15.setForeground(new java.awt.Color(59, 123, 50));
        txtNumero15.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtNumero15.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(59, 123, 50)), "Fecha Nacimiento", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12), new java.awt.Color(59, 123, 50))); // NOI18N
        txtNumero15.setCaretColor(new java.awt.Color(59, 123, 50));
        txtNumero15.setMargin(new java.awt.Insets(2, 5, 2, 5));
        txtNumero15.setSelectionColor(new java.awt.Color(59, 123, 50));
        txtNumero15.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtNumero15FocusLost(evt);
            }
        });
        txtNumero15.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtNumero15KeyReleased(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipady = 15;
        gridBagConstraints.weightx = 0.25;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 10, 0);
        jPanel5.add(txtNumero15, gridBagConstraints);

        txtNumero16.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtNumero16.setForeground(new java.awt.Color(59, 123, 50));
        txtNumero16.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtNumero16.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(59, 123, 50)), "Grupo", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12), new java.awt.Color(59, 123, 50))); // NOI18N
        txtNumero16.setCaretColor(new java.awt.Color(59, 123, 50));
        txtNumero16.setMargin(new java.awt.Insets(2, 5, 2, 5));
        txtNumero16.setSelectionColor(new java.awt.Color(59, 123, 50));
        txtNumero16.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtNumero16FocusLost(evt);
            }
        });
        txtNumero16.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtNumero16KeyReleased(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipady = 15;
        gridBagConstraints.weightx = 0.25;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 10, 0);
        jPanel5.add(txtNumero16, gridBagConstraints);

        txtNumero17.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtNumero17.setForeground(new java.awt.Color(59, 123, 50));
        txtNumero17.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtNumero17.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(59, 123, 50)), "Desc", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12), new java.awt.Color(59, 123, 50))); // NOI18N
        txtNumero17.setCaretColor(new java.awt.Color(59, 123, 50));
        txtNumero17.setMargin(new java.awt.Insets(2, 5, 2, 5));
        txtNumero17.setSelectionColor(new java.awt.Color(59, 123, 50));
        txtNumero17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNumero17ActionPerformed(evt);
            }
        });
        txtNumero17.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtNumero17FocusLost(evt);
            }
        });
        txtNumero17.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtNumero17KeyReleased(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 8;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipady = 15;
        gridBagConstraints.weightx = 0.125;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 10, 0);
        jPanel5.add(txtNumero17, gridBagConstraints);

        panelAcciones2.setBackground(new java.awt.Color(255, 255, 255));
        panelAcciones2.setLayout(new java.awt.GridBagLayout());

        btnGuardar4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconos/eliminar30.png"))); // NOI18N
        btnGuardar4.setToolTipText("Guardar");
        btnGuardar4.setBorderPainted(false);
        btnGuardar4.setContentAreaFilled(false);
        btnGuardar4.setMargin(new java.awt.Insets(2, 3, 2, 3));
        btnGuardar4.setName("btnGuardar"); // NOI18N
        btnGuardar4.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconos/guardar30_over.png"))); // NOI18N
        btnGuardar4.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconos/guardar30_over.png"))); // NOI18N
        btnGuardar4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardar4ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        panelAcciones2.add(btnGuardar4, gridBagConstraints);

        btnGuardar5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconos/guardar30.png"))); // NOI18N
        btnGuardar5.setToolTipText("Guardar");
        btnGuardar5.setBorderPainted(false);
        btnGuardar5.setContentAreaFilled(false);
        btnGuardar5.setMargin(new java.awt.Insets(2, 3, 2, 3));
        btnGuardar5.setName("btnGuardar"); // NOI18N
        btnGuardar5.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconos/guardar30_over.png"))); // NOI18N
        btnGuardar5.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconos/guardar30_over.png"))); // NOI18N
        btnGuardar5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardar5ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        panelAcciones2.add(btnGuardar5, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 12;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 10);
        jPanel5.add(panelAcciones2, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        pnlDescendencia.add(jPanel5, gridBagConstraints);

        scrpnlsDecendencia.setViewportView(pnlDescendencia);

        add(scrpnlsDecendencia, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, 670, 350));

        lblTid3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblTid3.setForeground(new java.awt.Color(59, 123, 50));
        lblTid3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblTid3.setText("Tipo Animales");
        add(lblTid3, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 20, -1, -1));

        btnAgregarAnimales.setBackground(new java.awt.Color(0, 0, 204));
        btnAgregarAnimales.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconos/addFromDB30.png"))); // NOI18N
        btnAgregarAnimales.setToolTipText("Agregar Arrendatario");
        btnAgregarAnimales.setBorder(null);
        btnAgregarAnimales.setBorderPainted(false);
        btnAgregarAnimales.setContentAreaFilled(false);
        btnAgregarAnimales.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAgregarAnimales.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconos/addFromDB30_over.png"))); // NOI18N
        btnAgregarAnimales.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconos/addFromDB30_over.png"))); // NOI18N
        btnAgregarAnimales.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarAnimalesActionPerformed(evt);
            }
        });
        add(btnAgregarAnimales, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 140, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void cbFincaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbFincaActionPerformed
        if (cbFinca.getItemCount() > 0) {
            //EventoComboFincas();
            System.out.println("cbFinca.getSelectedIndex()--" + cbFinca.getSelectedIndex());
            if (cbFinca.getSelectedIndex() >= 0) {
                idFinca = listaFincas.get(cbFinca.getSelectedIndex()).get("ID");
                CargarListaTipoAnimales();
            } else {
                cbTipoAnimales.removeAllItems();
            }
        }
    }//GEN-LAST:event_cbFincaActionPerformed

    private void cbTipoAnimalesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbTipoAnimalesActionPerformed
        if (cbTipoAnimales.getItemCount() > 0) {
            if (cbTipoAnimales.getSelectedIndex() >= 0) {
                idTipoAnimal = listaTipoAnimales.get(cbTipoAnimales.getSelectedIndex()).get("ID");
                //EventoComboFincas();
            } else {
                
            }
        }
    }//GEN-LAST:event_cbTipoAnimalesActionPerformed

    private void txtNumMamaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNumMamaFocusLost
        //MostrarTabla();
    }//GEN-LAST:event_txtNumMamaFocusLost

    private void txtNumMamaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNumMamaKeyPressed
        if (evt.getKeyCode() == evt.VK_ENTER) {
            
        }
    }//GEN-LAST:event_txtNumMamaKeyPressed

    private void txtNumMamaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNumMamaKeyReleased
        if (txtNumMama.getText().equals("")) {
            
        }
    }//GEN-LAST:event_txtNumMamaKeyReleased

    private void lblBsqAnimalesMadreMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBsqAnimalesMadreMouseClicked
        if (banBQDAnimalesMadre == 0) {
            banBQDAnimalesMadre = 1;
            //new ventanaBusquedaPaciente(1, "IDENTIFICACION:-:NOMBRE", estadoch, this);
            if (lblBsqAnimalesMadre.isEnabled()) {
                String param = "IDFINCA:"+idFinca+"<::>IDTIPO:"+idTipoAnimal+"<::>ADD:*/ AND animal.`genero` = 'hembra' AND animal.destete = '1' /*";
                objetoBusqueda = new ModeloGestorBusqueda(this, "BQD_ANML_DESC", 1, param);
                LimpiarPropietarios();
                new VistaBusqueda(objetoBusqueda);
            }
        }
    }//GEN-LAST:event_lblBsqAnimalesMadreMouseClicked

    private void btnAgregarAnimalesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarAnimalesActionPerformed
        if (banBQDAnimales == 0) {
            banBQDAnimales = 1;
            //new ventanaBusquedaPaciente(1, "IDENTIFICACION:-:NOMBRE", estadoch, this);
            if (btnAgregarAnimales.isEnabled()) {
                String param = "IDFINCA:"+idFinca+"<::>IDTIPO:"+idTipoAnimal+"<::>ADD:*/ AND animal.id <> '"+idMama+"' /*";
                objetoBusqueda = new ModeloGestorBusqueda(this, "BQD_ANML_DESC", 2, param);
                new VistaBusqueda(objetoBusqueda);
            }
        }
    }//GEN-LAST:event_btnAgregarAnimalesActionPerformed

    private void btnGuardar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardar1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnGuardar1ActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        Guardar();
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void txtNumero5KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNumero5KeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNumero5KeyReleased

    private void txtNumero5FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNumero5FocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNumero5FocusLost

    private void txtNumero5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNumero5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNumero5ActionPerformed

    private void txtNumero4KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNumero4KeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNumero4KeyReleased

    private void txtNumero4FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNumero4FocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNumero4FocusLost

    private void txtNumero3KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNumero3KeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNumero3KeyReleased

    private void txtNumero3FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNumero3FocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNumero3FocusLost

    private void txtNumero2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNumero2KeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNumero2KeyReleased

    private void txtNumero2FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNumero2FocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNumero2FocusLost

    private void txtNumero1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNumero1KeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNumero1KeyReleased

    private void txtNumero1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNumero1FocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNumero1FocusLost

    private void txtNumeroKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNumeroKeyReleased
        if (!chkAdoptivo.isSelected()) {
            String numeroMadre = txtNumero.getText().trim();
            if (!numeroMadre.isEmpty()) {
                txtNumero.setText(numeroMadre);
            }
        }
    }//GEN-LAST:event_txtNumeroKeyReleased

    private void txtNumeroFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNumeroFocusLost
        String numeroMadre = txtNumero.getText();
        Object[] datos = control.ObtenerUltimoDescendiente(numeroMadre, txtCodigoTipoAnimal.getText());
        String nroDescendiente = datos[0].toString();
        txtNumeroDescendiente.setText(nroDescendiente);

        System.out.println("mostrar->>>>" + datos[2]);
        List<Map<String, String>> animal = new ArrayList<Map<String, String>>();
        animal = (List<Map<String, String>>) datos[2];
        if (animal.size() > 0) {
            txtNumeroMadre = animal.get(0).get("id");
        }

        boolean mostrar = true;
        lblNumeroDescendiente.setVisible(mostrar);
        txtNumeroDescendiente.setVisible(mostrar);
    }//GEN-LAST:event_txtNumeroFocusLost

    private void txtNumeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNumeroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNumeroActionPerformed

    private void txtNumero6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNumero6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNumero6ActionPerformed

    private void txtNumero6FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNumero6FocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNumero6FocusLost

    private void txtNumero6KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNumero6KeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNumero6KeyReleased

    private void txtNumero7FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNumero7FocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNumero7FocusLost

    private void txtNumero7KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNumero7KeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNumero7KeyReleased

    private void txtNumero8FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNumero8FocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNumero8FocusLost

    private void txtNumero8KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNumero8KeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNumero8KeyReleased

    private void txtNumero9FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNumero9FocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNumero9FocusLost

    private void txtNumero9KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNumero9KeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNumero9KeyReleased

    private void txtNumero10FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNumero10FocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNumero10FocusLost

    private void txtNumero10KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNumero10KeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNumero10KeyReleased

    private void txtNumero11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNumero11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNumero11ActionPerformed

    private void txtNumero11FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNumero11FocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNumero11FocusLost

    private void txtNumero11KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNumero11KeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNumero11KeyReleased

    private void btnGuardar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardar2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnGuardar2ActionPerformed

    private void btnGuardar3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardar3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnGuardar3ActionPerformed

    private void txtNumero12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNumero12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNumero12ActionPerformed

    private void txtNumero12FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNumero12FocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNumero12FocusLost

    private void txtNumero12KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNumero12KeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNumero12KeyReleased

    private void txtNumero13FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNumero13FocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNumero13FocusLost

    private void txtNumero13KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNumero13KeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNumero13KeyReleased

    private void txtNumero14FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNumero14FocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNumero14FocusLost

    private void txtNumero14KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNumero14KeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNumero14KeyReleased

    private void txtNumero15FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNumero15FocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNumero15FocusLost

    private void txtNumero15KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNumero15KeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNumero15KeyReleased

    private void txtNumero16FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNumero16FocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNumero16FocusLost

    private void txtNumero16KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNumero16KeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNumero16KeyReleased

    private void txtNumero17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNumero17ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNumero17ActionPerformed

    private void txtNumero17FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNumero17FocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNumero17FocusLost

    private void txtNumero17KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNumero17KeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNumero17KeyReleased

    private void btnGuardar4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardar4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnGuardar4ActionPerformed

    private void btnGuardar5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardar5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnGuardar5ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnAgregarAnimales;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnGuardar1;
    private javax.swing.JButton btnGuardar2;
    private javax.swing.JButton btnGuardar3;
    private javax.swing.JButton btnGuardar4;
    private javax.swing.JButton btnGuardar5;
    public javax.swing.JComboBox cbFinca;
    public javax.swing.JComboBox cbTipoAnimales;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JLabel lblBsqAnimalesMadre;
    private javax.swing.JLabel lblTid;
    private javax.swing.JLabel lblTid1;
    private javax.swing.JLabel lblTid2;
    private javax.swing.JLabel lblTid3;
    private javax.swing.JPanel panelAcciones;
    private javax.swing.JPanel panelAcciones1;
    private javax.swing.JPanel panelAcciones2;
    private javax.swing.JPanel pnlDescendencia;
    private javax.swing.JScrollPane scrpnlsDecendencia;
    public javax.swing.JTextField txtNumMama;
    public javax.swing.JTextField txtNumero;
    public javax.swing.JTextField txtNumero1;
    public javax.swing.JTextField txtNumero10;
    public javax.swing.JTextField txtNumero11;
    public javax.swing.JTextField txtNumero12;
    public javax.swing.JTextField txtNumero13;
    public javax.swing.JTextField txtNumero14;
    public javax.swing.JTextField txtNumero15;
    public javax.swing.JTextField txtNumero16;
    public javax.swing.JTextField txtNumero17;
    public javax.swing.JTextField txtNumero2;
    public javax.swing.JTextField txtNumero3;
    public javax.swing.JTextField txtNumero4;
    public javax.swing.JTextField txtNumero5;
    public javax.swing.JTextField txtNumero6;
    public javax.swing.JTextField txtNumero7;
    public javax.swing.JTextField txtNumero8;
    public javax.swing.JTextField txtNumero9;
    // End of variables declaration//GEN-END:variables

    private void CargarListaFincas() {
        listaFincas = controlgen.GetComboBox("SELECT '-1' AS ID, 'Seleccionar' AS DESCRIPCION\n"
                + "UNION\n"
                + "SELECT `id` AS ID, `descripcion` AS DESCRIPCION\n"
                + "FROM `fincas`\n"
                + "/*UNION \n"
                + "SELECT 'ALL' AS ID, 'TODOS' AS DESCRIPCION*/");

        Utilidades.LlenarComboBox(cbFinca, listaFincas, "DESCRIPCION");
        cbFinca.setSelectedIndex(1);
        CargarListaTipoAnimales();
        //EventoComboFincas();
    }

    private void CargarListaTipoAnimales() {
        listaTipoAnimales = controlgen.GetComboBox("SELECT '-1' AS ID, 'Seleccionar' AS DESCRIPCION\n"
                + "UNION\n"
                + "SELECT id AS ID, descripcion AS DESCRIPCION\n"
                + "FROM `tipo_animales`\n"
                + "WHERE id_finca = '" + idFinca + "' AND estado = 'Activo'\n"
                + "ORDER BY id ASC");

        Utilidades.LlenarComboBox(cbTipoAnimales, listaTipoAnimales, "DESCRIPCION");
        cbTipoAnimales.setSelectedIndex(0);
        //EventoComboFincas();
    }
    private void LimpiarPropietarios() {
        idMama = "";
        txtNumMama.setText("");
    }
    
     //<editor-fold defaultstate="collapsed" desc="Metodo Busqueda Retorno">
    public void RetornoBusqueda(ModeloGestorBusqueda objeto, Map<String, String> retorno) {

        if (objeto.getOpcion() == 0) {// DEFAULT VISTA__VENTANA__
//            id_Finca = Integer.parseInt(retorno.get("ID"));
//            modelo = (ModeloFincas) ((ArrayList<ModeloFincas>) controlFinca.ObtenerDatosKey("" + id_Finca)).get(0);
//
//            txtDescripcion.setText(Utilidades.decodificarElemento(modelo.getDescripcion()));
//            txtDireccion.setText(Utilidades.decodificarElemento(modelo.getDireccion()));
//            txtAreaT.setText("" + modelo.getAreat());
//            lblIdPropietario.setText("" + modelo.getId_propietario());
//            txtPropietarios.setText(Utilidades.decodificarElemento(modelo.getPropietario()));
//
//            for (int i = 0; i < Tipo_moneda.size(); i++) {
//                if (Tipo_moneda.get(i).get("ID").equals(modelo.getIdTipoMoneda())) {
//                    cbTipoMoneda.setSelectedItem(Tipo_moneda.get(i).get("DESCRIPCION"));
//                    break;
//                }
//            }
        } else if (objeto.getOpcion() == 1) {// Numero animal
            idMama = "" + retorno.get("ID_ANIMAL");
            txtNumMama.setText(Utilidades.decodificarElemento(retorno.get("NUMERO_ANIMAL")));
            banBQDAnimalesMadre = 0;
        } else if (objeto.getOpcion() == 2) {// Numero Hijo
            idAnimalConsultado = "" + retorno.get("ID_ANIMAL");
            banBQDAnimales = 0;
            DatoHijoConsultado = control.getDatosHijo(idAnimalConsultado);
            AgregarHijoAnimal();
            idAnimalConsultado = "";
        }
    } 
    
    //</editor-fold>

    private void AgregarHijoAnimal() {
        
    }
    
}
