/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

import Control.*;
import Modelo.*;
import Utilidades.Utilidades;
import Utilidades.datosUsuario;
import java.awt.Cursor;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author MERRY
 */
public class VistaTrasladar extends javax.swing.JPanel {

    public ControlGeneral controlgen = new ControlGeneral();
    public ControlTraslado controlTraslado = new ControlTraslado();
    public List<Map<String, String>> listaFincas;
    public List<Map<String, String>> listaTipoAnimales;
    public List<Map<String, String>> listaGrupos;
    private ModeloVentanaGeneral modeloVentanaGeneral;
    private ModeloTraslado modeloTraslado;
    private ArrayList<ModeloTraslado> ListamodeloTraslado;
    private List<Map<String, String>> ListaAnimalesSeleccionados;
    private List<Map<String, String>> ListaAnimales;
    public ArrayList<ModeloDatosMultiple> Lista_Animales_Seleccionados = new ArrayList<>();
    public ArrayList<ModeloDatosMultiple> Lista_Animales_Mostrar = new ArrayList<>();
    public int cantpnl = 3;
    public int ind = 0;

    public String idFinca = "";
    public String idTipoAnimal = "";
    public String idTipoAnimalFinca = "";
    public String idGrupo = "";
    public String tipoGrupo = "";
    public int ancho;
    public int alto;

    /**
     * Creates new form VistaRotar
     */
    public VistaTrasladar() {
        initComponents();
        setSize(745, 615);
    }

    public VistaTrasladar(ModeloVentanaGeneral modeloVentanaGeneral) {
        initComponents();
        setSize(745, 615);
        System.out.println("******************VistaRotar***************+fasdfasdfasd+");
        this.modeloVentanaGeneral = modeloVentanaGeneral;
        controlTraslado = new ControlTraslado();
        IniciarFecha();
        idFinca = "";
        idGrupo = "";

        listaGrupos = new ArrayList<>();
        listaTipoAnimales = new ArrayList<>();
        ListaAnimales = new ArrayList<>();
        Lista_Animales_Mostrar = new ArrayList<>();
        modeloTraslado = new ModeloTraslado();
        ListamodeloTraslado = new ArrayList<>();
        Lista_Animales_Seleccionados = new ArrayList<>();
        ListaAnimalesSeleccionados = (List<Map<String, String>>) modeloVentanaGeneral.getModeloDatos();
        
        txtMotivo.setText("");
        
        if (ListaAnimalesSeleccionados.size() > 0) {
            LlenarPnlAnimales();
        }
        idTipoAnimalFinca = ListaAnimalesSeleccionados.get(0).get("IDTIPO_ANIMAL");
        CargarListaFincas();
        getAnimalesSistema();
        if (ListaAnimales.size() > 0) {
            EstablecerAnimalesxMostrar();
        }
        if (Lista_Animales_Mostrar.size() > 0) {
            LlenarPnlAnimalesMostrar();
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        scrpnlsAnimalesMostrar = new javax.swing.JScrollPane();
        pnlAnimalesMostrar = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        cbTipoAnimales = new javax.swing.JComboBox();
        lblTid2 = new javax.swing.JLabel();
        cbGrupo = new javax.swing.JComboBox();
        lblTid4 = new javax.swing.JLabel();
        jdFechaTraslado = new com.toedter.calendar.JDateChooser();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtMotivo = new javax.swing.JTextArea();
        lblTid5 = new javax.swing.JLabel();
        cbFinca = new javax.swing.JComboBox();
        lblTid = new javax.swing.JLabel();
        scrpnlsGrupos = new javax.swing.JScrollPane();
        pnlGrupos = new javax.swing.JPanel();
        lblTid3 = new javax.swing.JLabel();
        chNovilla = new javax.swing.JCheckBox();
        jPanel2 = new javax.swing.JPanel();
        btnGuardar = new javax.swing.JButton();
        btnDescartar = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 0)));
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                formComponentResized(evt);
            }
        });
        java.awt.GridBagLayout layout = new java.awt.GridBagLayout();
        layout.columnWidths = new int[] {0, 15, 0, 15, 0};
        layout.rowHeights = new int[] {0, 5, 0, 5, 0, 5, 0, 5, 0};
        setLayout(layout);

        jPanel1.setLayout(new java.awt.GridBagLayout());

        scrpnlsAnimalesMostrar.setBackground(new java.awt.Color(255, 255, 255));
        scrpnlsAnimalesMostrar.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(59, 123, 50)), "Animales a Trasladar", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12), new java.awt.Color(59, 123, 50))); // NOI18N
        scrpnlsAnimalesMostrar.setForeground(new java.awt.Color(59, 123, 50));

        pnlAnimalesMostrar.setBackground(new java.awt.Color(255, 255, 255));
        pnlAnimalesMostrar.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                pnlAnimalesMostrarComponentAdded(evt);
            }
            public void componentRemoved(java.awt.event.ContainerEvent evt) {
                pnlAnimalesMostrarComponentRemoved(evt);
            }
        });
        pnlAnimalesMostrar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        scrpnlsAnimalesMostrar.setViewportView(pnlAnimalesMostrar);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.FIRST_LINE_START;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.weighty = 1.0;
        jPanel1.add(scrpnlsAnimalesMostrar, gridBagConstraints);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        java.awt.GridBagLayout jPanel3Layout = new java.awt.GridBagLayout();
        jPanel3Layout.columnWidths = new int[] {0, 15, 0, 15, 0, 15, 0};
        jPanel3Layout.rowHeights = new int[] {0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0};
        jPanel3.setLayout(jPanel3Layout);

        cbTipoAnimales.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        cbTipoAnimales.setForeground(new java.awt.Color(59, 123, 50));
        cbTipoAnimales.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbTipoAnimalesActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipady = 9;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 0.5;
        jPanel3.add(cbTipoAnimales, gridBagConstraints);

        lblTid2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblTid2.setForeground(new java.awt.Color(59, 123, 50));
        lblTid2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblTid2.setText("Motivo");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 16;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        jPanel3.add(lblTid2, gridBagConstraints);

        cbGrupo.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        cbGrupo.setForeground(new java.awt.Color(59, 123, 50));
        cbGrupo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbGrupoActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipady = 9;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        jPanel3.add(cbGrupo, gridBagConstraints);

        lblTid4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblTid4.setForeground(new java.awt.Color(59, 123, 50));
        lblTid4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblTid4.setText("Fecha Traslado");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 0.15;
        jPanel3.add(lblTid4, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 12;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 60;
        gridBagConstraints.ipady = 10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        jPanel3.add(jdFechaTraslado, gridBagConstraints);

        txtMotivo.setColumns(20);
        txtMotivo.setRows(5);
        jScrollPane2.setViewportView(txtMotivo);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 18;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 0.5;
        jPanel3.add(jScrollPane2, gridBagConstraints);

        lblTid5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblTid5.setForeground(new java.awt.Color(59, 123, 50));
        lblTid5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblTid5.setText("Tipo Animales");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 0.5;
        jPanel3.add(lblTid5, gridBagConstraints);

        cbFinca.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        cbFinca.setForeground(new java.awt.Color(59, 123, 50));
        cbFinca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbFincaActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipady = 9;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 0.5;
        jPanel3.add(cbFinca, gridBagConstraints);

        lblTid.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblTid.setForeground(new java.awt.Color(59, 123, 50));
        lblTid.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblTid.setText("Finca");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 0.5;
        jPanel3.add(lblTid, gridBagConstraints);

        scrpnlsGrupos.setBackground(new java.awt.Color(255, 255, 255));
        scrpnlsGrupos.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(59, 123, 50)), "Animales a Trasladar", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12), new java.awt.Color(59, 123, 50))); // NOI18N
        scrpnlsGrupos.setForeground(new java.awt.Color(59, 123, 50));

        pnlGrupos.setBackground(new java.awt.Color(255, 255, 255));
        pnlGrupos.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                pnlGruposComponentAdded(evt);
            }
            public void componentRemoved(java.awt.event.ContainerEvent evt) {
                pnlGruposComponentRemoved(evt);
            }
        });
        pnlGrupos.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        scrpnlsGrupos.setViewportView(pnlGrupos);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 14;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        jPanel3.add(scrpnlsGrupos, gridBagConstraints);

        lblTid3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblTid3.setForeground(new java.awt.Color(59, 123, 50));
        lblTid3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblTid3.setText("Grupo");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        jPanel3.add(lblTid3, gridBagConstraints);

        chNovilla.setBackground(new java.awt.Color(255, 255, 255));
        chNovilla.setText("Novilla?");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 12;
        gridBagConstraints.weightx = 0.15;
        jPanel3.add(chNovilla, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.weighty = 1.0;
        jPanel1.add(jPanel3, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        add(jPanel1, gridBagConstraints);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new java.awt.GridBagLayout());

        btnGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconos/guardar.png"))); // NOI18N
        btnGuardar.setToolTipText("Guardar");
        btnGuardar.setBorderPainted(false);
        btnGuardar.setContentAreaFilled(false);
        btnGuardar.setMargin(new java.awt.Insets(2, 10, 2, 8));
        btnGuardar.setName("btnGuardar"); // NOI18N
        btnGuardar.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconos/guardar_over.png"))); // NOI18N
        btnGuardar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconos/guardar_over.png"))); // NOI18N
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHEAST;
        gridBagConstraints.weightx = 0.5;
        jPanel2.add(btnGuardar, gridBagConstraints);

        btnDescartar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconos/descartar.png"))); // NOI18N
        btnDescartar.setToolTipText("Descartar");
        btnDescartar.setBorderPainted(false);
        btnDescartar.setContentAreaFilled(false);
        btnDescartar.setMargin(new java.awt.Insets(2, 10, 2, 8));
        btnDescartar.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconos/descartar_over.png"))); // NOI18N
        btnDescartar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconos/descartar_over.png"))); // NOI18N
        btnDescartar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDescartarActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 0.5;
        jPanel2.add(btnDescartar, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        add(jPanel2, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    private void cbFincaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbFincaActionPerformed
        idFinca = listaFincas.get(cbFinca.getSelectedIndex()).get("ID");
        
        CargarListaTipoAnimales(idFinca);
        //CargarListaGrupos(idFinca, idTipoAnimal);
    }//GEN-LAST:event_cbFincaActionPerformed

    private void cbGrupoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbGrupoActionPerformed
        System.out.println("listaLotes->" + listaGrupos.size());
        if (cbGrupo.getSelectedIndex() > -1) {
            idGrupo = listaGrupos.get(cbGrupo.getSelectedIndex()).get("ID");
            tipoGrupo = listaGrupos.get(cbGrupo.getSelectedIndex()).get("TIPOG");
        }
    }//GEN-LAST:event_cbGrupoActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        Guardar();
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnDescartarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDescartarActionPerformed
        LimpiarFomulario();
    }//GEN-LAST:event_btnDescartarActionPerformed

    private void pnlGruposComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_pnlGruposComponentAdded
        //pnlGrupos.repaint();
    }//GEN-LAST:event_pnlGruposComponentAdded

    private void pnlGruposComponentRemoved(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_pnlGruposComponentRemoved
        // TODO add your handling code here:
    }//GEN-LAST:event_pnlGruposComponentRemoved

    private void pnlAnimalesMostrarComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_pnlAnimalesMostrarComponentAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_pnlAnimalesMostrarComponentAdded

    private void pnlAnimalesMostrarComponentRemoved(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_pnlAnimalesMostrarComponentRemoved
        // TODO add your handling code here:
    }//GEN-LAST:event_pnlAnimalesMostrarComponentRemoved

    private void formComponentResized(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentResized
        ancho = this.getWidth();
        alto = this.getHeight();
    }//GEN-LAST:event_formComponentResized

    private void cbTipoAnimalesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbTipoAnimalesActionPerformed
        if(cbTipoAnimales.getItemCount() > 0){
            //EventoComboFincas();
            if(cbTipoAnimales.getSelectedIndex() >= 0){
                idFinca = listaFincas.get(cbFinca.getSelectedIndex()).get("ID");
                idTipoAnimal = listaTipoAnimales.get(cbTipoAnimales.getSelectedIndex()).get("ID");
                CargarListaGrupos(idFinca, idTipoAnimal);
            }
        }
    }//GEN-LAST:event_cbTipoAnimalesActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDescartar;
    private javax.swing.JButton btnGuardar;
    public javax.swing.JComboBox cbFinca;
    public javax.swing.JComboBox cbGrupo;
    public javax.swing.JComboBox cbTipoAnimales;
    private javax.swing.JCheckBox chNovilla;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane2;
    private com.toedter.calendar.JDateChooser jdFechaTraslado;
    private javax.swing.JLabel lblTid;
    private javax.swing.JLabel lblTid2;
    private javax.swing.JLabel lblTid3;
    private javax.swing.JLabel lblTid4;
    private javax.swing.JLabel lblTid5;
    private javax.swing.JPanel pnlAnimalesMostrar;
    private javax.swing.JPanel pnlGrupos;
    private javax.swing.JScrollPane scrpnlsAnimalesMostrar;
    private javax.swing.JScrollPane scrpnlsGrupos;
    private javax.swing.JTextArea txtMotivo;
    // End of variables declaration//GEN-END:variables

    private void CargarListaFincas() {
        System.out.println("******CargarListaFincas****");
        listaFincas = controlgen.GetComboBox("SELECT '-1' AS ID, 'Seleccionar' AS DESCRIPCION\n"
                + "UNION\n"
                + "SELECT `id` AS ID, `descripcion` AS DESCRIPCION\n"
                + "FROM `fincas`\n"
                + "UNION \n"
                + "SELECT 'ALL' AS ID, 'TODOS' AS DESCRIPCION");
        Utilidades.LlenarComboBox(cbFinca, listaFincas, "DESCRIPCION");
        cbFinca.setSelectedItem("" + ListaAnimalesSeleccionados.get(0).get("FINCA"));
        CargarListaTipoAnimales(ListaAnimalesSeleccionados.get(0).get("IDFINCA"));
    }
    
    private void CargarListaTipoAnimales(String Id_Finca) {
        listaTipoAnimales = controlgen.GetComboBox("SELECT '-1' AS ID, 'Seleccionar' AS DESCRIPCION\n" +
                                                    "UNION\n" +
                                                    "SELECT id AS ID, descripcion AS DESCRIPCION\n" +
                                                    "FROM `tipo_animales`\n" +
                                                    "WHERE id_finca = '"+Id_Finca+"' AND estado = 'Activo'\n" +
                                                    "ORDER BY id ASC");
         
        Utilidades.LlenarComboBox(cbTipoAnimales, listaTipoAnimales, "DESCRIPCION");
        if(ListaAnimalesSeleccionados.get(0).get("IDFINCA").equals(idFinca))
            cbTipoAnimales.setSelectedItem("" + ListaAnimalesSeleccionados.get(0).get("TIPO_ANIMAL"));
        else
            cbTipoAnimales.setSelectedIndex(0);
        
        //CargarListaGrupos(IDfINCA, idTipoAnimal);
    }

    private void CargarListaGrupos(String idFinca, String tipoAnimal) {
        System.out.println("******CargarListaGrupos****");
        listaGrupos = controlgen.GetComboBox("SELECT '-1' AS ID, 'Seleccionar' AS DESCRIPCION , '' AS TIPOG\n"
                + "UNION                                              \n"
                + "SELECT grup.`id` AS ID, grup.`descripcion` AS DESCRIPCION, grup.`tipo_grupo` AS TIPOG\n"
                + "FROM `grupos`  grup\n"
                + "INNER JOIN  `tipo_animales` tipo ON tipo.`id` = grup.`id_tipo_animal`\n"
                + "WHERE tipo.`id_finca` = '" + idFinca + "' AND tipo.`id` = '" + tipoAnimal + "'");

        Utilidades.LlenarComboBox(cbGrupo, listaGrupos, "DESCRIPCION");
    }

    private void Guardar() {
        //<editor-fold defaultstate="collapsed" desc="VALIDACIONES">
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
        Calendar fecha = jdFechaTraslado.getCalendar();
        String fechaT = sdf.format(fecha.getTime());
        String motivo = Utilidades.decodificarElemento(txtMotivo.getText().trim());
        boolean novilla = chNovilla.isSelected();
        boolean muerte =  tipoGrupo.equals("muerte");

//        if (motivo.equals("")) {
//            JOptionPane.showMessageDialog(this, "Por favor diligencie el motivo de traslado.");
//            return;
//        }
        if (idGrupo.equals("-1")) {
            JOptionPane.showMessageDialog(this, "Por favor seleccione el grupo a trasladar, e intentelo nuevamente.");
            return;
        }
        if (Lista_Animales_Seleccionados.size() == 0) {
            JOptionPane.showMessageDialog(this, "Para realizar la operación se debe ");
            return;
        }
        //</editor-fold>
        int ret = -1, ret2 = -1;
        for (int i = 0; i < Lista_Animales_Seleccionados.size(); i++) {
            ListamodeloTraslado.add(
                    new ModeloTraslado(
                            "Activo",
                            "NOW()",
                            fechaT,
                            "0",
                            "" + Lista_Animales_Seleccionados.get(i).getId(),
                            idFinca,
                            idGrupo,
                            datosUsuario.datos.get(0).get("ID_USUARIO"),
                            motivo,
                            "",
                            "",
                            "",
                            "",
                            ""+idTipoAnimal)//IDTIPOANIMAL
            );
        }

        for (int i = 0; i < ListamodeloTraslado.size(); i++) {
            ret = controlTraslado.ActulizarAnimal(ListamodeloTraslado.get(i), novilla, muerte);
            ret = controlTraslado.InactivarTraslado(ListamodeloTraslado.get(i));
            if (ret == 0) {
                ret = controlTraslado.Guardar(ListamodeloTraslado.get(i));
            }

        }

        if (ret == 0) {
            if (modeloVentanaGeneral.getPanelPadre() instanceof VistaTraslado) {
                ((VistaTraslado) modeloVentanaGeneral.getPanelPadre()).RetornoVistaGeneral(modeloVentanaGeneral, modeloTraslado);
            }
            ((VistaGeneral) modeloVentanaGeneral.getFrameVentana()).dispose();
        }
    }

    private void LimpiarFomulario() {
        txtMotivo.setText("");
        cbFinca.setSelectedIndex(0);
        cbGrupo.removeAllItems();
        cbFinca.requestFocusInWindow();
        IniciarFecha();
    }

    public void IniciarFecha() {
        SimpleDateFormat formato = new SimpleDateFormat("yyyy-MM-dd");
        jdFechaTraslado.setCalendar(Calendar.getInstance());
    }

    //<editor-fold defaultstate="collapsed" desc="Mostrar Grupos Panel">
    private void LlenarPnlAnimales() {
        System.out.println("********LlenarPnlGrupos********");
        System.out.println("ListaGruposSeleccionados.size()->" + ListaAnimalesSeleccionados.size());
        for (int i = 0; i < ListaAnimalesSeleccionados.size(); i++) {
            Lista_Animales_Seleccionados.add(
                    new ModeloDatosMultiple(
                            Integer.parseInt(ListaAnimalesSeleccionados.get(i).get("ID_ANIMAL")), // ID
                            ListaAnimalesSeleccionados.get(i).get("NUMERO_ANIMAL") + " / "
                            + Utilidades.decodificarElemento(ListaAnimalesSeleccionados.get(i).get("GRUPO")) + " / "
                            + ListaAnimalesSeleccionados.get(i).get("GENERO").toUpperCase().charAt(0) + " / "
                            + ListaAnimalesSeleccionados.get(i).get("PESO") + "Kg", // DATO
                            getOriX(i), // X
                            getOriY(i), // Y
                            155, // widthPnl
                            140, // widthLblD
                            15, // widthLblC 
                            25, // heightPnl
                            20, // height
                            3));          // padding
        }
        System.out.println("Lista_Grupos_Seleccionados-->" + Lista_Animales_Seleccionados.size());
        MostrarAnimalesSeleccionados();

//        int ind = listPropietarios.getSelectedIndex();
//        String nombre = "" + modlistPropietarios.get(ind);
//        int indlistProp = getIndiceListaProp(nombre);
//        
//        if (!ExisteListaSeleccionados(nombre)) {
//
//            Lista_Propietarios_Seleccionados.add(
//                    new ModeloPropietariosMultiple(
//                            Integer.parseInt(Lista_Propietarios.get(indlistProp)[0]),
//                            Lista_Propietarios.get(indlistProp)[1] + Lista_Propietarios.get(indlistProp)[2],
//                            getOriX(Lista_Propietarios_Seleccionados.size()),
//                            getOriY(Lista_Propietarios_Seleccionados.size()),
//                            115,
//                            100,
//                            15,
//                            20,
//                            15,
//                            3)
//            );
//            //Lista_Propietarios_Seleccionados.add(Lista_Propietarios.get(indlistProp));
//        }
    }

    public int getOriX(int tam) {
        int ret = -1;
        int filas = tam / cantpnl;
        int mod = tam % cantpnl;
        ret = 3 + (mod * (155 + 3));
        return ret;
    }

    private int getOriY(int tam) {
        int ret = -1;
        int filas = tam / cantpnl;
        int mod = tam % cantpnl;
        ret = 3 + (filas * (25 + 3));
        return ret;
    }

    private void MostrarAnimalesSeleccionados() {
        System.out.println("*****************MostrarSeleccionados***************+" + Lista_Animales_Seleccionados.size());
        ind = -1;
        System.out.println("Lista_Grupos_Seleccionados-->" + Lista_Animales_Seleccionados.size());
        pnlGrupos.removeAll();
        repaint();

        for (ModeloDatosMultiple obj : Lista_Animales_Seleccionados) {
            ind++;
            javax.swing.JPanel pnlDato = new javax.swing.JPanel();
            javax.swing.JLabel lblnombre = new javax.swing.JLabel();
            javax.swing.JLabel lblCerrar = new javax.swing.JLabel();
            ///[26,82,118]
            pnlDato.setBackground(new java.awt.Color(59, 123, 50));
            pnlDato.setForeground(new java.awt.Color(255, 255, 255));
            pnlDato.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
            pnlDato.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(59, 123, 50), 1, true));
            pnlDato.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

            lblnombre.setText(obj.getDatosMostrar());
            lblnombre.setForeground(new java.awt.Color(255, 255, 255));

            lblCerrar.setFont(new java.awt.Font("Tahoma", 1, 12));
            lblCerrar.setText("X");//MousePressed
            lblCerrar.setName("" + ind);
            lblCerrar.setForeground(new java.awt.Color(255, 255, 255));
            lblCerrar.setCursor(new Cursor(Cursor.HAND_CURSOR));
            lblCerrar.addMouseListener(new java.awt.event.MouseAdapter() {
                public void mousePressed(java.awt.event.MouseEvent evt) {
                    int indr = Integer.parseInt(evt.getComponent().getName());
                    ActualizarGruposSeleccionados(indr);
                }
            });
            pnlDato.setToolTipText(obj.getDatosMostrar());
            pnlDato.add(lblnombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(3, 3, obj.getWidthLblD(), obj.getHeight()));
            pnlDato.add(lblCerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(3 + obj.getWidthLblD(), 3, obj.getWidthLblC(), obj.getHeight()));
            System.out.println("obj.getX()-->" + obj.getDatosMostrar());
            System.out.println("obj.getX()-->" + obj.getX());
            System.out.println("obj.getY()-->" + obj.getY());
            pnlGrupos.add(pnlDato, new org.netbeans.lib.awtextra.AbsoluteConstraints(obj.getX(), obj.getY(), obj.getWidthPnl(), obj.getHeightPnl()));
        }

        ((JFrame) modeloVentanaGeneral.getFrameVentana()).revalidate();
        ((JFrame) modeloVentanaGeneral.getFrameVentana()).repaint();
    }

    private void ActualizarGruposSeleccionados(int ind) {
        Lista_Animales_Mostrar.add(Lista_Animales_Seleccionados.get(ind));
        Lista_Animales_Seleccionados.remove(ind);
        RecargarListaSeleccionados();
        MostrarAnimalesSeleccionados();

        RecargarListaAnimalesMostrar();
        LlenarPnlAnimalesMostrar();
    }

    private void RecargarListaSeleccionados() {
        int ind = -1;
        for (ModeloDatosMultiple obj : Lista_Animales_Seleccionados) {
            ind++;
            obj.setX(getOriX(ind));
            obj.setY(getOriY(ind));
            obj.setWidthPnl(155);
            obj.setWidthLblD(140);
        }
    }

    //</editor-fold>    
    
    private void getAnimalesSistema() {
        ListaAnimales = controlTraslado.getAnimalesxFinca(idFinca, idTipoAnimalFinca);
    }

    private void EstablecerAnimalesxMostrar() {
        int ind = -1;
        boolean encontro = false;
        for (int i = 0; i < ListaAnimales.size(); i++) {
            encontro = false;
            for (int j = 0; j < Lista_Animales_Seleccionados.size(); j++) {
                if (("" + Lista_Animales_Seleccionados.get(j).getId()).equals("" + ListaAnimales.get(i).get("ID_ANIMAL"))) {
                    encontro = true;
                    break;
                }
            }
            if (!encontro) {
                ind++;
                Lista_Animales_Mostrar.add(
                        new ModeloDatosMultiple(
                                Integer.parseInt(ListaAnimales.get(i).get("ID_ANIMAL")), // ID
                                ListaAnimales.get(i).get("NUMERO_ANIMAL") + " / "
                                + ListaAnimales.get(i).get("GRUPO") + " / "
                                + ListaAnimales.get(i).get("GENERO").toUpperCase().charAt(0) + " / "
                                + ListaAnimales.get(i).get("PESO") + "Kg", // DATO
                                getOriXMostrar(ind), // X
                                getOriYMostrar(ind), // Y
                                175, // widthPnl
                                160, // widthLblD
                                15, // widthLblC 
                                25, // heightPnl
                                20, // height
                                3));          // padding
            }
        }
    }

    public int getOriXMostrar(int tam) {
        int ret = -1;
        int filas = tam / 1;
        int mod = tam % 1;
        ret = 3 + (mod * (155 + 3));
        return ret;
    }

    private int getOriYMostrar(int tam) {
        int ret = -1;
        int filas = tam / 1;
        int mod = tam % 1;
        ret = 3 + (filas * (25 + 3));
        return ret;
    }

    private void LlenarPnlAnimalesMostrar() {
        ind = -1;
        System.out.println("Lista_Grupos_Seleccionados-->" + Lista_Animales_Mostrar.size());
        pnlAnimalesMostrar.removeAll();
        revalidate();
        repaint();
        javax.swing.JPanel pnlDato = new javax.swing.JPanel();
        javax.swing.JLabel lblnombre = new javax.swing.JLabel();
        javax.swing.JLabel lblAgregar = new javax.swing.JLabel();

        for (ModeloDatosMultiple obj : Lista_Animales_Mostrar) {
            ind++;
            pnlDato = new javax.swing.JPanel();
            lblnombre = new javax.swing.JLabel();
            lblAgregar = new javax.swing.JLabel();
            ///[26,82,118]
            pnlDato.setBackground(new java.awt.Color(59, 123, 50));
            pnlDato.setForeground(new java.awt.Color(255, 255, 255));
            pnlDato.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
            pnlDato.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(59, 123, 50), 1, true));
            pnlDato.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
            pnlDato.setCursor(new Cursor(Cursor.HAND_CURSOR));
            pnlDato.setName("" + ind);
            pnlDato.addMouseListener(new java.awt.event.MouseAdapter() {
                public void mousePressed(java.awt.event.MouseEvent evt) {
                    int indr = Integer.parseInt(evt.getComponent().getName());
                    ActualizarAnimalesMostrar(indr);
                }
            });

            lblnombre.setText(obj.getDatosMostrar());
            lblnombre.setForeground(new java.awt.Color(255, 255, 255));

            lblAgregar.setFont(new java.awt.Font("Tahoma", 1, 12));
            lblAgregar.setText("+");//MousePressed
            lblAgregar.setName("" + ind);
            lblAgregar.setForeground(new java.awt.Color(255, 255, 255));
            lblAgregar.setCursor(new Cursor(Cursor.HAND_CURSOR));

            pnlDato.setToolTipText("Agregar Grupo " + obj.getDatosMostrar());
            pnlDato.add(lblnombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(3, 3, obj.getWidthLblD(), obj.getHeight()));
            pnlDato.add(lblAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(3 + obj.getWidthLblD(), 3, obj.getWidthLblC(), obj.getHeight()));
            pnlAnimalesMostrar.add(pnlDato, new org.netbeans.lib.awtextra.AbsoluteConstraints(obj.getX(), obj.getY(), obj.getWidthPnl(), obj.getHeightPnl()));
        }
        
        ((JFrame) modeloVentanaGeneral.getFrameVentana()).revalidate();
        ((JFrame) modeloVentanaGeneral.getFrameVentana()).repaint();
    }

    private void RecargarListaAnimalesMostrar() {
        int ind = -1;
        for (ModeloDatosMultiple obj : Lista_Animales_Mostrar) {
            ind++;
            obj.setX(getOriXMostrar(ind));
            obj.setY(getOriYMostrar(ind));
            obj.setWidthPnl(175);
            obj.setWidthLblD(160);
        }
    }

    private void ActualizarAnimalesMostrar(int ind) {
        Lista_Animales_Seleccionados.add(Lista_Animales_Mostrar.get(ind));
        Lista_Animales_Mostrar.remove(ind);
        RecargarListaAnimalesMostrar();
        LlenarPnlAnimalesMostrar();

        RecargarListaSeleccionados();
        MostrarAnimalesSeleccionados();
    }

}
