/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Vistas;

/**
 *
 * @author DOLFHANDLER
 */
public class VistaAnimalesPorHierro extends javax.swing.JPanel {

    /**
     * Creates new form VistaAnimalesPorHierro
     */
    public VistaAnimalesPorHierro() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtIdHierro = new javax.swing.JLabel();
        txtIdPropietario = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        lbltitle6 = new javax.swing.JLabel();
        cbPropietarios = new javax.swing.JComboBox();
        txtHierro = new javax.swing.JLabel();
        cbHierros = new javax.swing.JComboBox();
        lbltitle8 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblAnimales = new javax.swing.JTable();
        lbltitle9 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbltitle6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbltitle6.setForeground(new java.awt.Color(59, 123, 50));
        lbltitle6.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbltitle6.setText("Propietarios");
        jPanel1.add(lbltitle6, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 20, 180, -1));

        cbPropietarios.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        cbPropietarios.setForeground(new java.awt.Color(59, 123, 50));
        cbPropietarios.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Seleccionar", "Activo", "Inactivo" }));
        cbPropietarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbPropietariosActionPerformed(evt);
            }
        });
        jPanel1.add(cbPropietarios, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 40, 480, 30));

        txtHierro.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtHierro.setForeground(new java.awt.Color(59, 123, 50));
        txtHierro.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jPanel1.add(txtHierro, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 80, 430, 20));

        cbHierros.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        cbHierros.setForeground(new java.awt.Color(59, 123, 50));
        cbHierros.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Seleccionar", "Activo", "Inactivo" }));
        cbHierros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbHierrosActionPerformed(evt);
            }
        });
        jPanel1.add(cbHierros, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 100, 480, 30));

        lbltitle8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbltitle8.setForeground(new java.awt.Color(59, 123, 50));
        lbltitle8.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbltitle8.setText("Animales");
        jPanel1.add(lbltitle8, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 140, 90, 20));

        tblAnimales.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblAnimales.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                tblAnimalesMouseReleased(evt);
            }
        });
        jScrollPane1.setViewportView(tblAnimales);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 170, 480, 220));

        lbltitle9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbltitle9.setForeground(new java.awt.Color(59, 123, 50));
        lbltitle9.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbltitle9.setText("Hierro");
        jPanel1.add(lbltitle9, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 80, 50, 20));

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 740, 520));
    }// </editor-fold>//GEN-END:initComponents

    private void cbPropietariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbPropietariosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbPropietariosActionPerformed

    private void cbHierrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbHierrosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbHierrosActionPerformed

    private void tblAnimalesMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblAnimalesMouseReleased
//        int fila = tblAnimales.getSelectedRow();
//        int cola = tblAnimales.getSelectedColumn();
//        if(cola == 5){// ACTUALIZAR
//            modeloHierro = new ModeloHierros();
//            modeloHierro = ListamodeloHierros.get(fila);
//
//            objetoVentana = new ModeloVentanaGeneral(this, new VistaHierros(), 1,modeloHierro);
//            objetoVentana.setFila(fila);
//
//            new VistaGeneral(objetoVentana).setVisible(true);
//
//        }else if(cola == 6){ //ELIMINAR
//            int resp = JOptionPane.showConfirmDialog(this, "¿Esta Seguro de Eliminar esta Fila?");
//            if(resp == JOptionPane.YES_OPTION){
//                JOptionPane.showMessageDialog(this, "HAz EL MEtodo ");
//            }
//        }else if(cola == 4){ //VER IMAGEN
//
//        }
    }//GEN-LAST:event_tblAnimalesMouseReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JComboBox cbHierros;
    public javax.swing.JComboBox cbPropietarios;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbltitle6;
    private javax.swing.JLabel lbltitle8;
    private javax.swing.JLabel lbltitle9;
    private javax.swing.JTable tblAnimales;
    private javax.swing.JLabel txtHierro;
    private javax.swing.JLabel txtIdHierro;
    private javax.swing.JLabel txtIdPropietario;
    // End of variables declaration//GEN-END:variables
}
