/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Vistas;

import Utilidades.Utilidades;
import java.util.ArrayList;
import javax.swing.DefaultListModel;

/**
 *
 * @author MERRY
 */
public class VistaInformes extends javax.swing.JPanel {
    
    public ArrayList<String[]> listacategorias = new ArrayList<>();
    public ArrayList<String[]> listainformes = new ArrayList<>();
    public DefaultListModel modlistCategorias;
    public DefaultListModel modlistInformes;
    /**
     * Creates new form VistaInformes
     */
    public VistaInformes() {
        initComponents();
        modlistCategorias = new DefaultListModel();
        modlistInformes = new DefaultListModel();
        cargarArray();
        llenarCategorias();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        pnlCategoria = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listCategoria = new javax.swing.JList();
        pnlInforme = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        listInformes = new javax.swing.JList();
        jSeparator1 = new javax.swing.JSeparator();
        pnlGenerar = new javax.swing.JPanel();
        btnGenerar = new javax.swing.JButton();
        pnlOpciones = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new java.awt.GridBagLayout());

        pnlCategoria.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Categoria", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12), new java.awt.Color(59, 123, 50))); // NOI18N

        listCategoria.setForeground(new java.awt.Color(59, 123, 50));
        listCategoria.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        listCategoria.setSelectionBackground(new java.awt.Color(59, 123, 50));
        listCategoria.setVerifyInputWhenFocusTarget(false);
        listCategoria.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                listCategoriaMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                listCategoriaMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(listCategoria);

        javax.swing.GroupLayout pnlCategoriaLayout = new javax.swing.GroupLayout(pnlCategoria);
        pnlCategoria.setLayout(pnlCategoriaLayout);
        pnlCategoriaLayout.setHorizontalGroup(
            pnlCategoriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCategoriaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnlCategoriaLayout.setVerticalGroup(
            pnlCategoriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCategoriaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(7, Short.MAX_VALUE))
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.VERTICAL;
        gridBagConstraints.ipadx = 120;
        gridBagConstraints.ipady = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 0, 0);
        add(pnlCategoria, gridBagConstraints);

        pnlInforme.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Informe", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12), new java.awt.Color(59, 123, 50))); // NOI18N

        listInformes.setForeground(new java.awt.Color(59, 123, 50));
        listInformes.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        listInformes.setSelectionBackground(new java.awt.Color(59, 123, 50));
        listInformes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                listInformesMousePressed(evt);
            }
        });
        jScrollPane2.setViewportView(listInformes);

        javax.swing.GroupLayout pnlInformeLayout = new javax.swing.GroupLayout(pnlInforme);
        pnlInforme.setLayout(pnlInformeLayout);
        pnlInformeLayout.setHorizontalGroup(
            pnlInformeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlInformeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnlInformeLayout.setVerticalGroup(
            pnlInformeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlInformeLayout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 10, Short.MAX_VALUE))
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.VERTICAL;
        gridBagConstraints.ipadx = 118;
        gridBagConstraints.ipady = 10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 0, 0);
        add(pnlInforme, gridBagConstraints);

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.VERTICAL;
        gridBagConstraints.ipadx = 9;
        gridBagConstraints.ipady = 379;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(10, 8, 15, 0);
        add(jSeparator1, gridBagConstraints);

        pnlGenerar.setBackground(new java.awt.Color(59, 123, 50));

        btnGenerar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnGenerar.setForeground(new java.awt.Color(255, 255, 255));
        btnGenerar.setText("Generar");
        btnGenerar.setBorderPainted(false);
        btnGenerar.setContentAreaFilled(false);
        btnGenerar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnGenerarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnGenerarMouseExited(evt);
            }
        });
        btnGenerar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenerarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlGenerarLayout = new javax.swing.GroupLayout(pnlGenerar);
        pnlGenerar.setLayout(pnlGenerarLayout);
        pnlGenerarLayout.setHorizontalGroup(
            pnlGenerarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 160, Short.MAX_VALUE)
            .addGroup(pnlGenerarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnlGenerarLayout.createSequentialGroup()
                    .addGap(0, 42, Short.MAX_VALUE)
                    .addComponent(btnGenerar)
                    .addGap(0, 41, Short.MAX_VALUE)))
        );
        pnlGenerarLayout.setVerticalGroup(
            pnlGenerarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
            .addGroup(pnlGenerarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnlGenerarLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(btnGenerar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 83;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(20, 10, 0, 0);
        add(pnlGenerar, gridBagConstraints);

        pnlOpciones.setBackground(new java.awt.Color(255, 255, 255));
        pnlOpciones.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("jLabel1");
        pnlOpciones.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jList1.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane3.setViewportView(jList1);

        pnlOpciones.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, -1, -1));

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 470;
        gridBagConstraints.ipady = 380;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 0.9;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 15, 14);
        add(pnlOpciones, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    private void btnGenerarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGenerarMouseEntered
        Utilidades.establecerColorDeFondo(pnlGenerar, true);
    }//GEN-LAST:event_btnGenerarMouseEntered

    private void btnGenerarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGenerarMouseExited
        Utilidades.establecerColorDeFondo(pnlGenerar, false);
    }//GEN-LAST:event_btnGenerarMouseExited

    private void btnGenerarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenerarActionPerformed
        //txtURL.setText(Expresiones.seleccionarArchivoExcel(false, "C:/"));
        //System.out.println("txtURL-->"+txtURL.getText());
    }//GEN-LAST:event_btnGenerarActionPerformed

    private void listCategoriaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listCategoriaMousePressed
        SeleccionarCategoria();
    }//GEN-LAST:event_listCategoriaMousePressed

    private void listInformesMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listInformesMousePressed
        MostrarOpciones();
    }//GEN-LAST:event_listInformesMousePressed

    private void listCategoriaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listCategoriaMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_listCategoriaMouseExited


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnGenerar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JList jList1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JList listCategoria;
    private javax.swing.JList listInformes;
    private javax.swing.JPanel pnlCategoria;
    private javax.swing.JPanel pnlGenerar;
    private javax.swing.JPanel pnlInforme;
    private javax.swing.JPanel pnlOpciones;
    // End of variables declaration//GEN-END:variables

    private void cargarArray() {
        /////////////////////////// CAT, NOM
        listacategorias.add(new String[]{"0", "Archivos Excel"});
//        listacategorias.add(new String[]{"1","Historia Clinica"});
//        listacategorias.add(new String[]{"2","Factura"});
//        listacategorias.add(new String[]{"3","Paciente"});
        /////////////7////////////CAT, ID, NOm    
        listainformes.add(new String[]{"0", "0", "Carga Masiva Pesajes"});
        listainformes.add(new String[]{"0", "1", "Carga Masiva Palpación"});
    }
    
    private void llenarCategorias() {
        //cbCate.addItem("Seleccionar");
        for (int i = 0; i < listacategorias.size(); i++) {
            modlistCategorias.addElement(listacategorias.get(i)[1]);
        }
        listCategoria.setModel(modlistCategorias);
    }

    private void llenarInforme(String idcat) {
        LimpiarPanelOpciones();
        modlistInformes.removeAllElements();
        listInformes.setModel(modlistInformes);
        for (String[] lst : listainformes) {
            if (lst[0].equals(idcat)) {
                modlistInformes.addElement(lst[2]);
            }
        }
        listInformes.setModel(modlistInformes);
    }
    
    private void SeleccionarCategoria() {
        int ind = listCategoria.getSelectedIndex();
        //System.out.println("ind----->"+ind);
        //ind = getCategoria(modlistCategorias.getElementAt());
        llenarInforme("" + ind);
    }
    
    private void MostrarOpciones() {
        LimpiarPanelOpciones();

        int indC = listCategoria.getSelectedIndex();
        int indI = listInformes.getSelectedIndex();

        if (indC == 0) {//Archivos Excel
            if (indI == 0) {//Pesaje
                MostrarOpcArchivoPesaje();
            }else if (indI == 1) {//Palpacion
                MostrarOpcArchivoPalpacion();
            }
        }

    }
    
    private void LimpiarPanelOpciones() {
        pnlOpciones.removeAll();
        pnlOpciones.repaint();
//
//        lblPaciente = new javax.swing.JLabel();
//        txtPaciente = new javax.swing.JTextField();
//        btnBuscarP = new javax.swing.JButton();
//        lblIdPaciente = new javax.swing.JLabel();
//        cbBandera = new javax.swing.JComboBox();
//        lblBandera = new javax.swing.JLabel();
//        rbInfohistorico = new javax.swing.JRadioButton();
//        jdFechafinal = new com.toedter.calendar.JDateChooser();
//        jdFechainicial = new com.toedter.calendar.JDateChooser();
//        lblFechafinal = new javax.swing.JLabel();
//        lblFechainicial = new javax.swing.JLabel();
//
//        chPanoramica = new javax.swing.JCheckBox();
//        jLabel2 = new javax.swing.JLabel();
//        chPanoramicaTodas = new javax.swing.JCheckBox();
//        chRadiografia = new javax.swing.JCheckBox();
//        chRadiografiaTodas = new javax.swing.JCheckBox();
//        chOdontogramaTodas = new javax.swing.JCheckBox();
//        chOdontograma = new javax.swing.JCheckBox();
//        chFotografiaTodas = new javax.swing.JCheckBox();
//        chFotografia = new javax.swing.JCheckBox();

    }

    //<editor-fold defaultstate="collapsed" desc="Mostrar Opciones">
    private void MostrarOpcArchivoPesaje() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    private void MostrarOpcArchivoPalpacion() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
    //</editor-fold>
    
    
    

}
