/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

import Actividades.PanelActividades;
import AjustarControles.Ajustar;
import AjustarControles.AjustarControles;
import AjustarControles.ControlDeUsuario;
import AjustarControles.tiposDeAjuste;
import ImportExport.EstadoIE;
import ImportExport.ImportExport;
import Modelo.ModeloVentanaGeneral;
import Utilidades.Consultas;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JPanel;
import javax.swing.JScrollPane;

/**
 *
 * @author DOLFHANDLER
 */
public class VistaPrincipal extends javax.swing.JFrame {

    private ImportExport ie;
    public JScrollPane scroll;
    private JPanel panel;
    public int max = 0;
    private Dimension dpanel = new Dimension();
    private int x, y, band = 0;
    public int desplazamiento = 200;
    public String idFinca="";

    /**
     * Creates new form VistaPrincipal
     */
    public VistaPrincipal() {
        initComponents();
        scroll = new JScrollPane();
        this.setLocationRelativeTo(null);
        Consultas.Agregar();
        ie = new ImportExport(this);
        max = 0;
        OcultarContenidoMenu();
        dpanel = new Dimension(pnlContenedor.getSize());
        //OcultarMenu();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        progreso = new javax.swing.JProgressBar();
        mensaje = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        pnlTitulo = new javax.swing.JPanel();
        btnMinimizar = new javax.swing.JLabel();
        btnCerrar = new javax.swing.JLabel();
        lblTitulo = new javax.swing.JLabel();
        importarExportar = new javax.swing.JLabel();
        btnInicio = new javax.swing.JLabel();
        btnMenuVertical = new javax.swing.JLabel();
        btnMaximizar = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        pnlContenedor = new javax.swing.JPanel();
        pnlMenuVertical = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        pnlMenu = new javax.swing.JPanel();
        btnMostrarPropietarios = new javax.swing.JLabel();
        pnlContenedorPropietarios = new javax.swing.JPanel();
        btnPropietarios = new javax.swing.JLabel();
        btnHierros = new javax.swing.JLabel();
        btnMostrarFincas = new javax.swing.JLabel();
        pnlContenedorFincas = new javax.swing.JPanel();
        btnFincas = new javax.swing.JLabel();
        btnBloques = new javax.swing.JLabel();
        btnLotes = new javax.swing.JLabel();
        btnFuenteHidrica = new javax.swing.JLabel();
        btnPluviometro = new javax.swing.JLabel();
        btnMostrarGruposAnimales = new javax.swing.JLabel();
        pnlContenedorGruposAnimales = new javax.swing.JPanel();
        btnMacrogrupos = new javax.swing.JLabel();
        btnGrupos = new javax.swing.JLabel();
        btnTipoAnimal = new javax.swing.JLabel();
        btnMostrarActividades = new javax.swing.JLabel();
        pnlContenedorAnimales = new javax.swing.JPanel();
        btnAnimales = new javax.swing.JLabel();
        btnMuerteAnimal = new javax.swing.JLabel();
        btnAnimalxHierro1 = new javax.swing.JLabel();
        btnVentasAnimal = new javax.swing.JLabel();
        btnVerAnimales = new javax.swing.JLabel();
        btnTrasladoAnimal = new javax.swing.JLabel();
        btnRotacion = new javax.swing.JLabel();
        btnUsuarios = new javax.swing.JLabel();
        btnMostrarAnimales = new javax.swing.JLabel();
        pnlContenedorActividades = new javax.swing.JPanel();
        btnRegistroActividades = new javax.swing.JLabel();
        btnEstadoActividades = new javax.swing.JLabel();
        btnCronograma = new javax.swing.JLabel();

        progreso.setBackground(new java.awt.Color(255, 255, 255));
        progreso.setForeground(new java.awt.Color(36, 151, 20));

        mensaje.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        mensaje.setForeground(new java.awt.Color(36, 151, 20));
        mensaje.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        mensaje.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(progreso, javax.swing.GroupLayout.PREFERRED_SIZE, 728, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(mensaje, javax.swing.GroupLayout.PREFERRED_SIZE, 728, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(progreso, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addComponent(mensaje, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new java.awt.GridBagLayout());

        jPanel2.setBackground(new java.awt.Color(153, 0, 102));
        jPanel2.setMinimumSize(new java.awt.Dimension(750, 570));
        jPanel2.setLayout(new java.awt.GridBagLayout());

        pnlTitulo.setBackground(new java.awt.Color(59, 123, 50));
        pnlTitulo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pnlTituloMousePressed(evt);
            }
        });
        pnlTitulo.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                pnlTituloMouseDragged(evt);
            }
        });
        pnlTitulo.setLayout(new java.awt.GridBagLayout());

        btnMinimizar.setBackground(new java.awt.Color(255, 255, 255));
        btnMinimizar.setForeground(java.awt.Color.gray);
        btnMinimizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconos/minimizar.png"))); // NOI18N
        btnMinimizar.setToolTipText("Minimizar");
        btnMinimizar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnMinimizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnMinimizarMouseClicked(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 0.003;
        gridBagConstraints.insets = new java.awt.Insets(11, 10, 11, 0);
        pnlTitulo.add(btnMinimizar, gridBagConstraints);

        btnCerrar.setBackground(new java.awt.Color(153, 255, 0));
        btnCerrar.setForeground(java.awt.Color.gray);
        btnCerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconos/cerrar_1.png"))); // NOI18N
        btnCerrar.setToolTipText("Cerrar");
        btnCerrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCerrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCerrarMouseClicked(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 7;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 0.003;
        gridBagConstraints.insets = new java.awt.Insets(11, 4, 11, 10);
        pnlTitulo.add(btnCerrar, gridBagConstraints);

        lblTitulo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(255, 255, 255));
        lblTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitulo.setText("Ventana Principal");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.9;
        gridBagConstraints.insets = new java.awt.Insets(24, 18, 11, 10);
        pnlTitulo.add(lblTitulo, gridBagConstraints);

        importarExportar.setBackground(new java.awt.Color(255, 255, 255));
        importarExportar.setForeground(java.awt.Color.gray);
        importarExportar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconos/exportar.png"))); // NOI18N
        importarExportar.setToolTipText("Exportar");
        importarExportar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        importarExportar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                importarExportarMouseClicked(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 0.003;
        gridBagConstraints.insets = new java.awt.Insets(11, 6, 11, 0);
        pnlTitulo.add(importarExportar, gridBagConstraints);

        btnInicio.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnInicio.setForeground(new java.awt.Color(255, 255, 255));
        btnInicio.setText("INICIO");
        btnInicio.setToolTipText("INICIO");
        btnInicio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnInicioMouseClicked(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 0.007;
        gridBagConstraints.insets = new java.awt.Insets(24, 10, 11, 0);
        pnlTitulo.add(btnInicio, gridBagConstraints);

        btnMenuVertical.setBackground(new java.awt.Color(255, 255, 255));
        btnMenuVertical.setForeground(java.awt.Color.gray);
        btnMenuVertical.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconos/menu_1.png"))); // NOI18N
        btnMenuVertical.setToolTipText("Menu Vertical");
        btnMenuVertical.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnMenuVertical.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnMenuVerticalMouseClicked(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 0.003;
        gridBagConstraints.insets = new java.awt.Insets(11, 10, 11, 0);
        pnlTitulo.add(btnMenuVertical, gridBagConstraints);

        btnMaximizar.setBackground(new java.awt.Color(255, 255, 255));
        btnMaximizar.setForeground(java.awt.Color.gray);
        btnMaximizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconos/maximizar.png"))); // NOI18N
        btnMaximizar.setToolTipText("Maximizar");
        btnMaximizar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnMaximizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnMaximizarMouseClicked(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 0.003;
        gridBagConstraints.insets = new java.awt.Insets(11, 6, 11, 0);
        pnlTitulo.add(btnMaximizar, gridBagConstraints);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconos/importar.png"))); // NOI18N
        jLabel1.setToolTipText("Importar");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 0.003;
        gridBagConstraints.insets = new java.awt.Insets(11, 6, 11, 0);
        pnlTitulo.add(jLabel1, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        jPanel2.add(pnlTitulo, gridBagConstraints);

        pnlContenedor.setBackground(new java.awt.Color(255, 255, 255));
        pnlContenedor.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(36, 151, 20)));
        pnlContenedor.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                pnlContenedorComponentResized(evt);
            }
        });

        javax.swing.GroupLayout pnlContenedorLayout = new javax.swing.GroupLayout(pnlContenedor);
        pnlContenedor.setLayout(pnlContenedorLayout);
        pnlContenedorLayout.setHorizontalGroup(
            pnlContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 755, Short.MAX_VALUE)
        );
        pnlContenedorLayout.setVerticalGroup(
            pnlContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 559, Short.MAX_VALUE)
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        jPanel2.add(pnlContenedor, gridBagConstraints);

        pnlMenuVertical.setBackground(new java.awt.Color(59, 123, 50));
        pnlMenuVertical.setPreferredSize(new java.awt.Dimension(220, 612));
        pnlMenuVertical.setRequestFocusEnabled(false);

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setOpaque(false);
        jScrollPane1.setPreferredSize(new java.awt.Dimension(212, 782));

        pnlMenu.setBackground(new java.awt.Color(59, 123, 50));
        pnlMenu.setName(""); // NOI18N
        pnlMenu.setPreferredSize(new java.awt.Dimension(220, 780));
        pnlMenu.setRequestFocusEnabled(false);

        btnMostrarPropietarios.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnMostrarPropietarios.setForeground(new java.awt.Color(255, 255, 255));
        btnMostrarPropietarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconos/factura_mini_2.png"))); // NOI18N
        btnMostrarPropietarios.setText("Propietarios");
        btnMostrarPropietarios.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnMostrarPropietarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnMostrarPropietariosMouseClicked(evt);
            }
        });

        pnlContenedorPropietarios.setBackground(new java.awt.Color(59, 145, 70));

        btnPropietarios.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnPropietarios.setForeground(new java.awt.Color(255, 255, 255));
        btnPropietarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconos/factura_mini_2.png"))); // NOI18N
        btnPropietarios.setText("Propietario");
        btnPropietarios.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnPropietarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnPropietariosMouseClicked(evt);
            }
        });

        btnHierros.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnHierros.setForeground(new java.awt.Color(255, 255, 255));
        btnHierros.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconos/factura_mini_2.png"))); // NOI18N
        btnHierros.setText("Hierros");
        btnHierros.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnHierros.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnHierrosMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout pnlContenedorPropietariosLayout = new javax.swing.GroupLayout(pnlContenedorPropietarios);
        pnlContenedorPropietarios.setLayout(pnlContenedorPropietariosLayout);
        pnlContenedorPropietariosLayout.setHorizontalGroup(
            pnlContenedorPropietariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnPropietarios, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(btnHierros, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        pnlContenedorPropietariosLayout.setVerticalGroup(
            pnlContenedorPropietariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlContenedorPropietariosLayout.createSequentialGroup()
                .addComponent(btnPropietarios)
                .addGap(0, 0, 0)
                .addComponent(btnHierros))
        );

        btnMostrarFincas.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnMostrarFincas.setForeground(new java.awt.Color(255, 255, 255));
        btnMostrarFincas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconos/factura_mini_2.png"))); // NOI18N
        btnMostrarFincas.setText("Fincas");
        btnMostrarFincas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnMostrarFincas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnMostrarFincasMouseClicked(evt);
            }
        });

        pnlContenedorFincas.setBackground(new java.awt.Color(59, 145, 70));

        btnFincas.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnFincas.setForeground(new java.awt.Color(255, 255, 255));
        btnFincas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconos/factura_mini_2.png"))); // NOI18N
        btnFincas.setText("Finca");
        btnFincas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnFincas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnFincasMouseClicked(evt);
            }
        });

        btnBloques.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnBloques.setForeground(new java.awt.Color(255, 255, 255));
        btnBloques.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconos/factura_mini_2.png"))); // NOI18N
        btnBloques.setText("Bloques");
        btnBloques.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBloques.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBloquesMouseClicked(evt);
            }
        });

        btnLotes.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnLotes.setForeground(new java.awt.Color(255, 255, 255));
        btnLotes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconos/factura_mini_2.png"))); // NOI18N
        btnLotes.setText("Lotes");
        btnLotes.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLotes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnLotesMouseClicked(evt);
            }
        });

        btnFuenteHidrica.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnFuenteHidrica.setForeground(new java.awt.Color(255, 255, 255));
        btnFuenteHidrica.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconos/factura_mini_2.png"))); // NOI18N
        btnFuenteHidrica.setText("Fuente Hidrica");
        btnFuenteHidrica.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnFuenteHidrica.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnFuenteHidricaMouseClicked(evt);
            }
        });

        btnPluviometro.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnPluviometro.setForeground(new java.awt.Color(255, 255, 255));
        btnPluviometro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconos/factura_mini_2.png"))); // NOI18N
        btnPluviometro.setText("Pluviometro");
        btnPluviometro.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnPluviometro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnPluviometroMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout pnlContenedorFincasLayout = new javax.swing.GroupLayout(pnlContenedorFincas);
        pnlContenedorFincas.setLayout(pnlContenedorFincasLayout);
        pnlContenedorFincasLayout.setHorizontalGroup(
            pnlContenedorFincasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnFincas, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(btnBloques, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(btnFuenteHidrica, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(btnLotes, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(btnPluviometro, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        pnlContenedorFincasLayout.setVerticalGroup(
            pnlContenedorFincasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlContenedorFincasLayout.createSequentialGroup()
                .addComponent(btnFincas)
                .addGap(0, 0, 0)
                .addComponent(btnBloques)
                .addGap(0, 0, 0)
                .addComponent(btnFuenteHidrica)
                .addGap(0, 0, 0)
                .addComponent(btnLotes)
                .addGap(0, 0, 0)
                .addComponent(btnPluviometro))
        );

        btnMostrarGruposAnimales.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnMostrarGruposAnimales.setForeground(new java.awt.Color(255, 255, 255));
        btnMostrarGruposAnimales.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconos/factura_mini_2.png"))); // NOI18N
        btnMostrarGruposAnimales.setText("Grupos Animales");
        btnMostrarGruposAnimales.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnMostrarGruposAnimales.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnMostrarGruposAnimalesMouseClicked(evt);
            }
        });

        pnlContenedorGruposAnimales.setBackground(new java.awt.Color(59, 145, 70));

        btnMacrogrupos.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnMacrogrupos.setForeground(new java.awt.Color(255, 255, 255));
        btnMacrogrupos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconos/factura_mini_2.png"))); // NOI18N
        btnMacrogrupos.setText("Macrogrupos");
        btnMacrogrupos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnMacrogrupos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnMacrogruposRealMousePressed(evt);
            }
        });

        btnGrupos.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnGrupos.setForeground(new java.awt.Color(255, 255, 255));
        btnGrupos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconos/factura_mini_2.png"))); // NOI18N
        btnGrupos.setText("Grupos");
        btnGrupos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnGrupos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnGruposMousePressed(evt);
            }
        });

        btnTipoAnimal.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnTipoAnimal.setForeground(new java.awt.Color(255, 255, 255));
        btnTipoAnimal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconos/factura_mini_2.png"))); // NOI18N
        btnTipoAnimal.setText("Tipo Animales");
        btnTipoAnimal.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnTipoAnimal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnTipoAnimalMousePressed(evt);
            }
        });

        javax.swing.GroupLayout pnlContenedorGruposAnimalesLayout = new javax.swing.GroupLayout(pnlContenedorGruposAnimales);
        pnlContenedorGruposAnimales.setLayout(pnlContenedorGruposAnimalesLayout);
        pnlContenedorGruposAnimalesLayout.setHorizontalGroup(
            pnlContenedorGruposAnimalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnMacrogrupos, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(btnGrupos, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(btnTipoAnimal, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        pnlContenedorGruposAnimalesLayout.setVerticalGroup(
            pnlContenedorGruposAnimalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlContenedorGruposAnimalesLayout.createSequentialGroup()
                .addComponent(btnMacrogrupos)
                .addGap(0, 0, 0)
                .addComponent(btnGrupos)
                .addGap(0, 0, 0)
                .addComponent(btnTipoAnimal)
                .addGap(30, 30, 30))
        );

        btnMostrarActividades.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnMostrarActividades.setForeground(new java.awt.Color(255, 255, 255));
        btnMostrarActividades.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconos/factura_mini_2.png"))); // NOI18N
        btnMostrarActividades.setText("Actividades");
        btnMostrarActividades.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnMostrarActividades.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnMostrarActividadesMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnMostrarActividadesMousePressed(evt);
            }
        });

        pnlContenedorAnimales.setBackground(new java.awt.Color(59, 145, 70));

        btnAnimales.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnAnimales.setForeground(new java.awt.Color(255, 255, 255));
        btnAnimales.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconos/factura_mini_2.png"))); // NOI18N
        btnAnimales.setText("Agregar Animal");
        btnAnimales.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAnimales.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnAnimalesRealMousePressed(evt);
            }
        });

        btnMuerteAnimal.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnMuerteAnimal.setForeground(new java.awt.Color(255, 255, 255));
        btnMuerteAnimal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconos/factura_mini_2.png"))); // NOI18N
        btnMuerteAnimal.setText("Muertes");
        btnMuerteAnimal.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnMuerteAnimal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnMuerteAnimalMousePressed(evt);
            }
        });

        btnAnimalxHierro1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnAnimalxHierro1.setForeground(new java.awt.Color(255, 255, 255));
        btnAnimalxHierro1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconos/factura_mini_2.png"))); // NOI18N
        btnAnimalxHierro1.setText("Hierro por Animal");
        btnAnimalxHierro1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAnimalxHierro1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnAnimalxHierro1MousePressed(evt);
            }
        });

        btnVentasAnimal.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnVentasAnimal.setForeground(new java.awt.Color(255, 255, 255));
        btnVentasAnimal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconos/factura_mini_2.png"))); // NOI18N
        btnVentasAnimal.setText("Ventas");
        btnVentasAnimal.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnVentasAnimal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnVentasAnimalMousePressed(evt);
            }
        });

        btnVerAnimales.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnVerAnimales.setForeground(new java.awt.Color(255, 255, 255));
        btnVerAnimales.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconos/factura_mini_2.png"))); // NOI18N
        btnVerAnimales.setText("Ver Animales");
        btnVerAnimales.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnVerAnimales.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnVerAnimalesRealMousePressed(evt);
            }
        });

        javax.swing.GroupLayout pnlContenedorAnimalesLayout = new javax.swing.GroupLayout(pnlContenedorAnimales);
        pnlContenedorAnimales.setLayout(pnlContenedorAnimalesLayout);
        pnlContenedorAnimalesLayout.setHorizontalGroup(
            pnlContenedorAnimalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnAnimales, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(btnVerAnimales, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(btnAnimalxHierro1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(btnVentasAnimal, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(btnMuerteAnimal, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        pnlContenedorAnimalesLayout.setVerticalGroup(
            pnlContenedorAnimalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlContenedorAnimalesLayout.createSequentialGroup()
                .addComponent(btnAnimales)
                .addGap(0, 0, 0)
                .addComponent(btnVerAnimales)
                .addGap(0, 0, 0)
                .addComponent(btnAnimalxHierro1)
                .addGap(0, 0, 0)
                .addComponent(btnVentasAnimal)
                .addGap(0, 0, 0)
                .addComponent(btnMuerteAnimal))
        );

        btnTrasladoAnimal.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnTrasladoAnimal.setForeground(new java.awt.Color(255, 255, 255));
        btnTrasladoAnimal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconos/factura_mini_2.png"))); // NOI18N
        btnTrasladoAnimal.setText("Traslado Animal");
        btnTrasladoAnimal.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnTrasladoAnimal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnTrasladoAnimalMouseClicked(evt);
            }
        });

        btnRotacion.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnRotacion.setForeground(new java.awt.Color(255, 255, 255));
        btnRotacion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconos/factura_mini_2.png"))); // NOI18N
        btnRotacion.setText("Rotación");
        btnRotacion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRotacion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnRotacionMouseClicked(evt);
            }
        });

        btnUsuarios.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnUsuarios.setForeground(new java.awt.Color(255, 255, 255));
        btnUsuarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconos/factura_mini_2.png"))); // NOI18N
        btnUsuarios.setText("Usuarios");
        btnUsuarios.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        btnMostrarAnimales.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnMostrarAnimales.setForeground(new java.awt.Color(255, 255, 255));
        btnMostrarAnimales.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconos/factura_mini_2.png"))); // NOI18N
        btnMostrarAnimales.setText("Animales");
        btnMostrarAnimales.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnMostrarAnimales.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnMostrarAnimalesMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnMostrarAnimalesMousePressed(evt);
            }
        });

        pnlContenedorActividades.setBackground(new java.awt.Color(59, 145, 70));

        btnRegistroActividades.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnRegistroActividades.setForeground(new java.awt.Color(255, 255, 255));
        btnRegistroActividades.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconos/factura_mini_2.png"))); // NOI18N
        btnRegistroActividades.setText("Registro ");
        btnRegistroActividades.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRegistroActividades.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnRegistroActividadesRealMousePressed(evt);
            }
        });

        btnEstadoActividades.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnEstadoActividades.setForeground(new java.awt.Color(255, 255, 255));
        btnEstadoActividades.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconos/factura_mini_2.png"))); // NOI18N
        btnEstadoActividades.setText("Estado");
        btnEstadoActividades.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEstadoActividades.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnEstadoActividadesMousePressed(evt);
            }
        });

        btnCronograma.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnCronograma.setForeground(new java.awt.Color(255, 255, 255));
        btnCronograma.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconos/factura_mini_2.png"))); // NOI18N
        btnCronograma.setText("Cronograma");
        btnCronograma.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCronograma.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnCronogramaMousePressed(evt);
            }
        });

        javax.swing.GroupLayout pnlContenedorActividadesLayout = new javax.swing.GroupLayout(pnlContenedorActividades);
        pnlContenedorActividades.setLayout(pnlContenedorActividadesLayout);
        pnlContenedorActividadesLayout.setHorizontalGroup(
            pnlContenedorActividadesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnRegistroActividades, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(btnEstadoActividades, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(btnCronograma, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        pnlContenedorActividadesLayout.setVerticalGroup(
            pnlContenedorActividadesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlContenedorActividadesLayout.createSequentialGroup()
                .addComponent(btnRegistroActividades)
                .addGap(0, 0, 0)
                .addComponent(btnEstadoActividades)
                .addGap(0, 0, 0)
                .addComponent(btnCronograma)
                .addGap(30, 30, 30))
        );

        javax.swing.GroupLayout pnlMenuLayout = new javax.swing.GroupLayout(pnlMenu);
        pnlMenu.setLayout(pnlMenuLayout);
        pnlMenuLayout.setHorizontalGroup(
            pnlMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnMostrarPropietarios, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(pnlContenedorPropietarios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(btnMostrarFincas, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(pnlContenedorFincas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(btnMostrarGruposAnimales, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(pnlContenedorGruposAnimales, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(btnMostrarAnimales, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(pnlContenedorAnimales, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(btnMostrarActividades, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(pnlContenedorActividades, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(btnTrasladoAnimal, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(btnRotacion, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(btnUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        pnlMenuLayout.setVerticalGroup(
            pnlMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMenuLayout.createSequentialGroup()
                .addComponent(btnMostrarPropietarios)
                .addGap(0, 0, 0)
                .addComponent(pnlContenedorPropietarios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btnMostrarFincas)
                .addGap(0, 0, 0)
                .addComponent(pnlContenedorFincas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btnMostrarGruposAnimales)
                .addGap(0, 0, 0)
                .addComponent(pnlContenedorGruposAnimales, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btnMostrarAnimales)
                .addGap(0, 0, 0)
                .addComponent(pnlContenedorAnimales, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btnMostrarActividades)
                .addGap(0, 0, 0)
                .addComponent(pnlContenedorActividades, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btnTrasladoAnimal)
                .addGap(0, 0, 0)
                .addComponent(btnRotacion)
                .addGap(0, 0, 0)
                .addComponent(btnUsuarios))
        );

        jScrollPane1.setViewportView(pnlMenu);

        javax.swing.GroupLayout pnlMenuVerticalLayout = new javax.swing.GroupLayout(pnlMenuVertical);
        pnlMenuVertical.setLayout(pnlMenuVerticalLayout);
        pnlMenuVerticalLayout.setHorizontalGroup(
            pnlMenuVerticalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE)
        );
        pnlMenuVerticalLayout.setVerticalGroup(
            pnlMenuVerticalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 613, Short.MAX_VALUE)
        );

        jScrollPane1.getAccessibleContext().setAccessibleDescription("");

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.VERTICAL;
        gridBagConstraints.ipady = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weighty = 1.0;
        jPanel2.add(pnlMenuVertical, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        getContentPane().add(jPanel2, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnMinimizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMinimizarMouseClicked
        this.setState(VistaInicioSesion.ICONIFIED);
    }//GEN-LAST:event_btnMinimizarMouseClicked

    private void btnCerrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCerrarMouseClicked
        System.exit(0);
    }//GEN-LAST:event_btnCerrarMouseClicked

    public void MostrarPanel(JPanel panel) {
        this.panel = panel;
        this.panel.setBounds(0, 0, pnlContenedor.getWidth(), pnlContenedor.getHeight());
        pnlContenedor.removeAll();

        java.awt.GridBagConstraints gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        pnlContenedor.add(this.panel, gridBagConstraints);

        pnlContenedor.revalidate();
        pnlContenedor.repaint();

    }

    public void MostrarPanel(JScrollPane scroll) {
        scroll.setBounds(0, 0, pnlContenedor.getWidth(), pnlContenedor.getHeight());
        pnlContenedor.removeAll();
        pnlContenedor.add(scroll);
        pnlContenedor.revalidate();
        pnlContenedor.repaint();

    }

    private void btnTrasladoAnimalMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTrasladoAnimalMousePressed
        if (evt.getClickCount() == 1) {
//            VistaAnimales vista = new VistaAnimales();
//            MostrarPanel(vista);
        }
    }//GEN-LAST:event_btnTrasladoAnimalMousePressed

    private void btnMostrarActividadesMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMostrarActividadesMousePressed

    }//GEN-LAST:event_btnMostrarActividadesMousePressed

    private void btnMostrarPropietariosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMostrarPropietarios1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btnMostrarPropietarios1MouseEntered

    private void btnMostrarPropietariosMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMostrarPropietarios1MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnMostrarPropietarios1MousePressed

    private void btnPropietariosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPropietarios1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPropietarios1MouseEntered

    private void btnPropietariosMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPropietarios1MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPropietarios1MousePressed

    private void btnBloquesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHierros1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btnHierros1MouseEntered

    private void btnBloquesMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHierros1MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnHierros1MousePressed

    private void btnLotesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHierros2MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btnHierros2MouseEntered

    private void btnLotesMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHierros2MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnHierros2MousePressed

    private void btnFuenteHidricaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPropietarios2MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPropietarios2MouseEntered

    private void btnFuenteHidricaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPropietarios2MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPropietarios2MousePressed

    private void btnMacrogruposMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnFincas1MouseEntered

    }//GEN-LAST:event_btnFincas1MouseEntered

    private void btnMacrogruposMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnFincas1MousePressed

    }//GEN-LAST:event_btnFincas1MousePressed

    private void btnMostrarPropietariosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMostrarPropietariosMouseClicked
        btnPropietarios.setVisible(!pnlContenedorPropietarios.isVisible());
        btnHierros.setVisible(!pnlContenedorPropietarios.isVisible());
        pnlContenedorPropietarios.setVisible(!pnlContenedorPropietarios.isVisible());
    }//GEN-LAST:event_btnMostrarPropietariosMouseClicked

    private void btnMostrarFincasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMostrarFincasMouseClicked
        btnFincas.setVisible(!pnlContenedorFincas.isVisible());
        btnBloques.setVisible(!pnlContenedorFincas.isVisible());
        btnFuenteHidrica.setVisible(!pnlContenedorFincas.isVisible());
        btnLotes.setVisible(!pnlContenedorFincas.isVisible());
        pnlContenedorFincas.setVisible(!pnlContenedorFincas.isVisible());
    }//GEN-LAST:event_btnMostrarFincasMouseClicked

    private void btnMostrarGruposAnimalesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMostrarGruposAnimalesMouseClicked
        btnMacrogrupos.setVisible(!pnlContenedorGruposAnimales.isVisible());
        btnGrupos.setVisible(!pnlContenedorGruposAnimales.isVisible());
        btnTipoAnimal.setVisible(!pnlContenedorGruposAnimales.isVisible());
        pnlContenedorGruposAnimales.setVisible(!pnlContenedorGruposAnimales.isVisible());
    }//GEN-LAST:event_btnMostrarGruposAnimalesMouseClicked

    private void btnPropietariosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPropietariosMouseClicked
        if (evt.getClickCount() == 1) {
            EstablecerTituloVentana("Propietarios");
            VistaPropietarios vista = new VistaPropietarios();
            MostrarPanel(vista);
        }
    }//GEN-LAST:event_btnPropietariosMouseClicked

    private void btnHierrosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHierrosMouseClicked
        if (evt.getClickCount() == 1) {
            EstablecerTituloVentana("Hierros por Propietarios");
            VistaAllHierros vista = new VistaAllHierros();
            MostrarPanel(vista);
        }
    }//GEN-LAST:event_btnHierrosMouseClicked

    private void btnGruposMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGruposMousePressed
        if (evt.getClickCount() == 1) {
            EstablecerTituloVentana("Grupos");
            VistaGrupos vista = new VistaGrupos();
            MostrarPanel(vista);
        }
    }//GEN-LAST:event_btnGruposMousePressed

    private void btnTipoAnimalMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTipoAnimalMousePressed
        if (evt.getClickCount() == 1) {
            EstablecerTituloVentana("Tipo Animal");
            VistaTipoAnimales vista = new VistaTipoAnimales();
            MostrarPanel(vista);
        }
    }//GEN-LAST:event_btnTipoAnimalMousePressed

    private void btnMacrogruposRealMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMacrogruposRealMousePressed
        if (evt.getClickCount() == 1) {
            EstablecerTituloVentana("Macrogrupos");
            VistaMacroGrupo vista = new VistaMacroGrupo();
            MostrarPanel(vista);
        }
    }//GEN-LAST:event_btnMacrogruposRealMousePressed

    private void btnFincasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnFincasMouseClicked
        if (evt.getClickCount() == 1) {
            EstablecerTituloVentana("Fincas");
            VistaFincas vista = new VistaFincas();
            MostrarPanel(vista);
        }
    }//GEN-LAST:event_btnFincasMouseClicked

    private void btnBloquesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBloquesMouseClicked
        if (evt.getClickCount() == 1) {
            EstablecerTituloVentana("Bloques");
            VistaAllBloques vista = new VistaAllBloques();
            MostrarPanel(vista);
        }
    }//GEN-LAST:event_btnBloquesMouseClicked

    private void btnFuenteHidricaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnFuenteHidricaMouseClicked
        if (evt.getClickCount() == 1) {
            EstablecerTituloVentana("Fuentes Hidricas");
            VistaFuentesHidricas vista = new VistaFuentesHidricas();
            MostrarPanel(vista);
        }
    }//GEN-LAST:event_btnFuenteHidricaMouseClicked

    private void btnLotesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLotesMouseClicked
        if (evt.getClickCount() == 1) {
            EstablecerTituloVentana("Lotes");
            VistaAllLotes vista = new VistaAllLotes();
            MostrarPanel(vista);
        }
    }//GEN-LAST:event_btnLotesMouseClicked

    private void btnTrasladoAnimalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTrasladoAnimalMouseClicked
        if (evt.getClickCount() == 1) {
            EstablecerTituloVentana("Traslado Animales");
            VistaTraslado vista = new VistaTraslado();
            MostrarPanel(vista);
        }
    }//GEN-LAST:event_btnTrasladoAnimalMouseClicked

    private void btnRotacionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRotacionMouseClicked
        if (evt.getClickCount() == 1) {
            EstablecerTituloVentana("Rotación Animales");
            VistaRotacion vista = new VistaRotacion();
            MostrarPanel(vista);
        }
    }//GEN-LAST:event_btnRotacionMouseClicked

    private void btnAnimalesRealMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAnimalesRealMousePressed
        if (evt.getClickCount() == 1) {
            EstablecerTituloVentana("Animales");
            VistaAnimales vista = new VistaAnimales();
            MostrarPanel(vista);
        }
    }//GEN-LAST:event_btnAnimalesRealMousePressed

    private void btnMuerteAnimalMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMuerteAnimalMousePressed
        if (evt.getClickCount() == 1) {
            EstablecerTituloVentana("Historico Muertes");
            VistaHistoricoMuertes vista = new VistaHistoricoMuertes();
            MostrarPanel(vista);
        }
    }//GEN-LAST:event_btnMuerteAnimalMousePressed

    private void btnMostrarActividadesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMostrarActividadesMouseClicked
        btnRegistroActividades.setVisible(!pnlContenedorActividades.isVisible());
        btnEstadoActividades.setVisible(!pnlContenedorActividades.isVisible());
        btnCronograma.setVisible(!pnlContenedorActividades.isVisible());
        pnlContenedorActividades.setVisible(!pnlContenedorActividades.isVisible());
    }//GEN-LAST:event_btnMostrarActividadesMouseClicked

    private void btnPluviometroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPluviometroMouseClicked
        if (evt.getClickCount() == 1) {
            EstablecerTituloVentana("Pluviometro");
            VistaPluviometro vista = new VistaPluviometro();
            MostrarPanel(vista);
        }
    }//GEN-LAST:event_btnPluviometroMouseClicked

    private void importarExportarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_importarExportarMouseClicked
        if (evt.getClickCount() == 1) {
            ie.estado = EstadoIE.EXPORTAR;
            ie.iniciar();
        }
    }//GEN-LAST:event_importarExportarMouseClicked

    private void btnAnimalxHierro1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAnimalxHierro1MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAnimalxHierro1MousePressed

    private void btnVentasAnimalMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVentasAnimalMousePressed
        if (evt.getClickCount() == 1) {
            EstablecerTituloVentana("Historico Ventas");
            VistaHistoricoVentas vista = new VistaHistoricoVentas();
            MostrarPanel(vista);
        }
    }//GEN-LAST:event_btnVentasAnimalMousePressed

    private void btnVerAnimalesRealMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVerAnimalesRealMousePressed
        if (evt.getClickCount() == 1) {
            EstablecerTituloVentana("Ver Animales");
            VistaVerAnimales vista = new VistaVerAnimales();
            MostrarPanel(vista);
        }
    }//GEN-LAST:event_btnVerAnimalesRealMousePressed

    private void btnInicioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnInicioMouseClicked
        if (evt.getClickCount() == 1) {
            EstablecerTituloVentana("Estadisticas");
            VistaInicio vista = new VistaInicio(this);
            MostrarPanel(vista);
        }
    }//GEN-LAST:event_btnInicioMouseClicked

    private void btnMostrarAnimalesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMostrarAnimalesMouseClicked
        btnAnimales.setVisible(!pnlContenedorAnimales.isVisible());
        btnMuerteAnimal.setVisible(!pnlContenedorAnimales.isVisible());
        pnlContenedorAnimales.setVisible(!pnlContenedorAnimales.isVisible());
    }//GEN-LAST:event_btnMostrarAnimalesMouseClicked

    private void btnMostrarAnimalesMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMostrarAnimalesMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnMostrarAnimalesMousePressed

    private void btnRegistroActividadesRealMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRegistroActividadesRealMousePressed
        if (evt.getClickCount() == 1) {
            EstablecerTituloVentana("Actividades");
            VistaActividades vista = new VistaActividades();
            MostrarPanel(vista);
        }
    }//GEN-LAST:event_btnRegistroActividadesRealMousePressed

    private void btnEstadoActividadesMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEstadoActividadesMousePressed
        if (evt.getClickCount() == 1) {
            EstablecerTituloVentana("Estados Actividad");
            VistaEstadoActividad vista = new VistaEstadoActividad();
            MostrarPanel(vista);
        }
    }//GEN-LAST:event_btnEstadoActividadesMousePressed

    private void btnCronogramaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCronogramaMousePressed
        if (evt.getClickCount() == 1) {
            SeleccionarFinca();
//            EstablecerTituloVentana("Cronograma");
//            PanelActividades vista = new PanelActividades(this);
//            scroll = new JScrollPane();
//            scroll.setViewportView(vista);
//            scroll.setPreferredSize(new Dimension(this.getSize()));
//            MostrarPanel(scroll);
        }
    }//GEN-LAST:event_btnCronogramaMousePressed

    private void btnMenuVerticalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMenuVerticalMouseClicked

        int tamanio = 30;
        int x = 0;
        int ancho = 0;
        if (band == 0) {
            desplazamiento = pnlMenuVertical.getWidth() - tamanio;
            x = pnlTitulo.getX() - desplazamiento;
            ancho = pnlTitulo.getWidth() + desplazamiento;

            pnlMenuVertical.setBounds(
                    pnlMenuVertical.getX(),
                    pnlMenuVertical.getY(),
                    pnlMenuVertical.getWidth() - desplazamiento,
                    pnlMenuVertical.getHeight()
            );
            jScrollPane1.setBounds(
                    jScrollPane1.getX(),
                    jScrollPane1.getY(),
                    jScrollPane1.getWidth() - desplazamiento,
                    jScrollPane1.getHeight()
            );
            band = 1;
        } else {
            x = pnlTitulo.getX() + desplazamiento;
            ancho = pnlTitulo.getWidth() - desplazamiento;

            pnlMenuVertical.setBounds(
                    pnlMenuVertical.getX(),
                    pnlMenuVertical.getY(),
                    desplazamiento + tamanio,
                    pnlMenuVertical.getHeight()
            );
            jScrollPane1.setBounds(
                    jScrollPane1.getX(),
                    jScrollPane1.getY(),
                    desplazamiento + tamanio,
                    jScrollPane1.getHeight()
            );
            band = 0;
        }

        pnlTitulo.setBounds(
                x,
                pnlTitulo.getY(),
                ancho,
                pnlTitulo.getHeight()
        );
        pnlContenedor.setBounds(
                x,
                pnlContenedor.getY(),
                ancho,
                pnlContenedor.getHeight()
        );
    }//GEN-LAST:event_btnMenuVerticalMouseClicked

    private void btnMaximizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMaximizarMouseClicked
        if (evt.getClickCount() == 1) {
            System.out.println("max--->" + max);
            System.out.println("w pnlcontenedor--->" + pnlContenedor.getWidth());
            System.out.println("h pnlcontenedor--->" + pnlContenedor.getHeight());
            if (max == 0) {//MAXIMIZAR
                btnMaximizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconos/restaurar.png")));
                btnMaximizar.setToolTipText("Restaurar");
                max = 1;
                this.setExtendedState(JFrame.MAXIMIZED_BOTH);
            } else {//RESTAURAR
                btnMaximizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconos/maximizar.png")));
                btnMaximizar.setToolTipText("Maximizar");
                max = 0;
                this.setExtendedState(JFrame.NORMAL);
            }
            System.out.println("w pnlcontenedor--->" + pnlContenedor.getWidth());
            System.out.println("h pnlcontenedor--->" + pnlContenedor.getHeight());

        }
    }//GEN-LAST:event_btnMaximizarMouseClicked

    private void pnlContenedorComponentResized(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_pnlContenedorComponentResized
        EstablecerPnlContenedor();
    }//GEN-LAST:event_pnlContenedorComponentResized

    private void pnlTituloMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlTituloMousePressed
        x = evt.getX();
        y = evt.getY();
    }//GEN-LAST:event_pnlTituloMousePressed

    private void pnlTituloMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlTituloMouseDragged
        this.setLocation(this.getLocation().x + evt.getX() - x, this.getLocation().y + evt.getY() - y);
    }//GEN-LAST:event_pnlTituloMouseDragged

    public void EstablecerPnlContenedor() {
        if (pnlContenedor.getComponents().length > 0) {
            if (max == 0) {
                pnlContenedor.getComponent(0).setSize(dpanel);
            } else {
                pnlContenedor.getComponent(0).setSize(pnlContenedor.getWidth(), pnlContenedor.getHeight());
            }
            java.awt.GridBagConstraints gridBagConstraints = new java.awt.GridBagConstraints();
            gridBagConstraints.gridx = 0;
            gridBagConstraints.gridy = 0;
            gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
            gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
            gridBagConstraints.weightx = 1.0;
            gridBagConstraints.weighty = 1.0;
            pnlContenedor.add(pnlContenedor.getComponent(0), gridBagConstraints);

            //        pnlContenedor.add(panel);
            pnlContenedor.revalidate();
            pnlContenedor.repaint();
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnAnimales;
    private javax.swing.JLabel btnAnimalxHierro1;
    private javax.swing.JLabel btnBloques;
    private javax.swing.JLabel btnCerrar;
    private javax.swing.JLabel btnCronograma;
    private javax.swing.JLabel btnEstadoActividades;
    private javax.swing.JLabel btnFincas;
    private javax.swing.JLabel btnFuenteHidrica;
    private javax.swing.JLabel btnGrupos;
    private javax.swing.JLabel btnHierros;
    private javax.swing.JLabel btnInicio;
    private javax.swing.JLabel btnLotes;
    private javax.swing.JLabel btnMacrogrupos;
    private javax.swing.JLabel btnMaximizar;
    private javax.swing.JLabel btnMenuVertical;
    private javax.swing.JLabel btnMinimizar;
    private javax.swing.JLabel btnMostrarActividades;
    private javax.swing.JLabel btnMostrarAnimales;
    private javax.swing.JLabel btnMostrarFincas;
    private javax.swing.JLabel btnMostrarGruposAnimales;
    private javax.swing.JLabel btnMostrarPropietarios;
    private javax.swing.JLabel btnMuerteAnimal;
    private javax.swing.JLabel btnPluviometro;
    private javax.swing.JLabel btnPropietarios;
    private javax.swing.JLabel btnRegistroActividades;
    private javax.swing.JLabel btnRotacion;
    private javax.swing.JLabel btnTipoAnimal;
    private javax.swing.JLabel btnTrasladoAnimal;
    private javax.swing.JLabel btnUsuarios;
    private javax.swing.JLabel btnVentasAnimal;
    private javax.swing.JLabel btnVerAnimales;
    private javax.swing.JLabel importarExportar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JLabel lblTitulo;
    public javax.swing.JLabel mensaje;
    public javax.swing.JPanel pnlContenedor;
    private javax.swing.JPanel pnlContenedorActividades;
    private javax.swing.JPanel pnlContenedorAnimales;
    private javax.swing.JPanel pnlContenedorFincas;
    private javax.swing.JPanel pnlContenedorGruposAnimales;
    private javax.swing.JPanel pnlContenedorPropietarios;
    private javax.swing.JPanel pnlMenu;
    private javax.swing.JPanel pnlMenuVertical;
    private javax.swing.JPanel pnlTitulo;
    public javax.swing.JProgressBar progreso;
    // End of variables declaration//GEN-END:variables

    private void OcultarContenidoMenu() {
        pnlContenedorPropietarios.setVisible(false);
        btnPropietarios.setVisible(false);
        btnHierros.setVisible(false);
        pnlContenedorFincas.setVisible(false);
        pnlContenedorGruposAnimales.setVisible(false);
        pnlContenedorAnimales.setVisible(false);
        pnlContenedorActividades.setVisible(false);
    }

    private void EstablecerTituloVentana(String titulo) {
        lblTitulo.setText("" + titulo);
    }

    private void SeleccionarFinca() {
        VistaSeleccionarFinca vsf = new VistaSeleccionarFinca();
        ModeloVentanaGeneral objetoVentana = new ModeloVentanaGeneral(this, vsf, 1);
        new VistaGeneral(objetoVentana).setVisible(true);
    }


}
