/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

import Actividades.ActividadesPorPeriodo;
import Actividades.PanelActividades;
import Configuracion.InformacionGlobal;
import Control.ControlCronograma;
import Control.ControlGeneral;
import Modelo.ModeloVentanaGeneral;
import static Utilidades.Consultas.consultas;
import Utilidades.Utilidades;
import java.awt.Color;
import java.awt.Dimension;
import java.util.ArrayList;
import java.util.List;
import java.util.Map;
import javax.swing.JScrollPane;

/**
 *
 * @author DOLFHANDLER
 */
public class VistaSeleccionarFinca extends javax.swing.JPanel {

    private ControlGeneral controlGral;
    private List<Map<String, String>> fincas;
    public ModeloVentanaGeneral modeloVentanaGeneral;
    public String idFinca = "";

    /**
     * Creates new form VistaSeleccionarFinca
     */
    public VistaSeleccionarFinca() {
        initComponents();
        controlGral = new ControlGeneral();
        
        InformacionGlobal.setFincaDesdeConstructor(cbFinca);
    }

    VistaSeleccionarFinca(ModeloVentanaGeneral modeloVentanaGeneral) {
        initComponents();
        setSize(300, 200);
        this.modeloVentanaGeneral = modeloVentanaGeneral;
        controlGral = new ControlGeneral();
        cargarComboFincas();
        
        InformacionGlobal.setFincaDesdeConstructor(cbFinca);
    }

    private void cargarComboFincas() {
        String consulta = consultas.get("CARGAR_COMBO_FINCAS");
        fincas = controlGral.GetComboBox(consulta);

        Utilidades.LlenarComboBox(cbFinca, fincas, "descripcion");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        lbltitle8 = new javax.swing.JLabel();
        cbFinca = new javax.swing.JComboBox();
        jPanel2 = new javax.swing.JPanel();
        btniniciarsesion = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(59, 123, 50)));
        setLayout(new java.awt.GridBagLayout());

        lbltitle8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbltitle8.setForeground(new java.awt.Color(59, 123, 50));
        lbltitle8.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbltitle8.setText("Fincas");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.FIRST_LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(20, 20, 9, 0);
        add(lbltitle8, gridBagConstraints);

        cbFinca.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        cbFinca.setForeground(new java.awt.Color(59, 123, 50));
        cbFinca.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Seleccionar" }));
        cbFinca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbFincaActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.ipadx = 123;
        gridBagConstraints.ipady = 9;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.FIRST_LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(0, 20, 9, 20);
        add(cbFinca, gridBagConstraints);

        jPanel2.setBackground(new java.awt.Color(59, 123, 50));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(59, 123, 50)));

        btniniciarsesion.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        btniniciarsesion.setForeground(new java.awt.Color(255, 255, 255));
        btniniciarsesion.setText("Aceptar");
        btniniciarsesion.setBorderPainted(false);
        btniniciarsesion.setContentAreaFilled(false);
        btniniciarsesion.setFocusPainted(false);
        btniniciarsesion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btniniciarsesionMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btniniciarsesionMouseExited(evt);
            }
        });
        btniniciarsesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btniniciarsesionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btniniciarsesion, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btniniciarsesion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(0, 20, 20, 20);
        add(jPanel2, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    private void cbFincaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbFincaActionPerformed
        InformacionGlobal.setFincaDesdeEventoChange(cbFinca);
        
        int indice = cbFinca.getSelectedIndex();
        if (indice > 0) {
            idFinca = fincas.get(indice).get("id");
        }
    }//GEN-LAST:event_cbFincaActionPerformed

    private void btniniciarsesionMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btniniciarsesionMouseEntered
        Utilidades.establecerColorDeFondo(jPanel2, true);
    }//GEN-LAST:event_btniniciarsesionMouseEntered

    private void btniniciarsesionMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btniniciarsesionMouseExited
        Utilidades.establecerColorDeFondo(jPanel2, false);
    }//GEN-LAST:event_btniniciarsesionMouseExited

    private void btniniciarsesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btniniciarsesionActionPerformed
        Aceptar();
    }//GEN-LAST:event_btniniciarsesionActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btniniciarsesion;
    public javax.swing.JComboBox cbFinca;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lbltitle8;
    // End of variables declaration//GEN-END:variables

    private void Aceptar() {
        VistaPrincipal vp = (VistaPrincipal) modeloVentanaGeneral.getPanelPadre();
        vp.lblTitulo.setText("Cronograma");
        vp.idFinca=idFinca;
        
        PanelActividades vista = new PanelActividades(vp);
        vp.scroll = new JScrollPane();
        vp.scroll.setViewportView(vista);
        vp.scroll.setPreferredSize(new Dimension(vp.getSize()));
        vp.MostrarPanel(vp.scroll);
        ((VistaGeneral)modeloVentanaGeneral.getFrameVentana()).dispose();
    }

}
