/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Vistas;

import Control.*;
import Modelo.*;
import Utilidades.Utilidades;
import Utilidades.datosUsuario;
import java.awt.Cursor;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;

/**
 *
 * @author MERRY
 */
public class VistaRotar extends javax.swing.JPanel {
    public ControlGeneral controlgen = new ControlGeneral();
    public ControlRotar controlRotar = new ControlRotar();
    public List<Map<String, String>> listaFincas;
    public List<Map<String, String>> listaLotes;
    private ModeloVentanaGeneral  modeloVentanaGeneral;
    private ModeloRotacionLotes  modeloRotacionLotes;
    private ArrayList<ModeloRotacionGrupos>  ListamodeloRotacionGrupos;
    private List<Map<String, String>>  ListaGruposSeleccionados;
    private List<Map<String, String>>  ListaGrupos;
    private ArrayList<ModeloDatosMultiple>  ListaGruposMostrar;
    public ArrayList<ModeloDatosMultiple> Lista_Grupos_Seleccionados = new ArrayList<>();
    public int cantpnl = 3;
    public int ind = 0;
    public String idFinca = "";
    public String idLote = "";
    /**
     * Creates new form VistaRotar
     */
    public VistaRotar() {
        initComponents();
        setSize(608, 450);
    }
    public VistaRotar(ModeloVentanaGeneral modeloVentanaGeneral){
        initComponents();
        setSize(608, 450);
        System.out.println("******************VistaRotar***************+fasdfasdfasd+");
        this.modeloVentanaGeneral = modeloVentanaGeneral;
        controlRotar = new ControlRotar();
        IniciarFecha();
        idFinca = "";
        idLote = "";
        listaLotes = new ArrayList<>();
        modeloRotacionLotes = new ModeloRotacionLotes();
        ListamodeloRotacionGrupos = new ArrayList<>();
        
        ListaGrupos = new ArrayList<>();
        
        
        ListaGruposMostrar = new ArrayList<>();
        Lista_Grupos_Seleccionados = new ArrayList<>();
        ListaGruposSeleccionados = (List<Map<String, String>>) modeloVentanaGeneral.getModeloDatos();
        System.out.println("ListaGruposSeleccionados-->"+ListaGruposSeleccionados.size());
        if(ListaGruposSeleccionados.size()> 0){
            LlenarPnlGrupos();
        }
        
        CargarListaFincas();
        getGruposSistema();
        if(ListaGrupos.size()>0){
            EstablecerGruposxMostrar();
        }
        if(ListaGruposMostrar.size()> 0){
            LlenarPnlGruposMostrar();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        cbFinca = new javax.swing.JComboBox();
        lblTid = new javax.swing.JLabel();
        cbLote = new javax.swing.JComboBox();
        lblTid2 = new javax.swing.JLabel();
        scrpnlsGrupos = new javax.swing.JScrollPane();
        pnlGrupos = new javax.swing.JPanel();
        btnGuardar = new javax.swing.JButton();
        btnDescartar = new javax.swing.JButton();
        lblTid3 = new javax.swing.JLabel();
        jdFechaEntrada = new com.toedter.calendar.JDateChooser();
        scrpnlsGrupos1 = new javax.swing.JScrollPane();
        pnlGruposMostrar = new javax.swing.JPanel();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 0)));
        setLayout(new java.awt.GridBagLayout());

        cbFinca.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        cbFinca.setForeground(new java.awt.Color(59, 123, 50));
        cbFinca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbFincaActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 10;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 280;
        gridBagConstraints.ipady = 9;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 0.7;
        gridBagConstraints.insets = new java.awt.Insets(5, 40, 0, 0);
        add(cbFinca, gridBagConstraints);

        lblTid.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblTid.setForeground(new java.awt.Color(59, 123, 50));
        lblTid.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblTid.setText("Finca");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 120;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(20, 40, 0, 0);
        add(lblTid, gridBagConstraints);

        cbLote.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        cbLote.setForeground(new java.awt.Color(59, 123, 50));
        cbLote.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbLoteActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 10;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 280;
        gridBagConstraints.ipady = 9;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 40, 0, 0);
        add(cbLote, gridBagConstraints);

        lblTid2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblTid2.setForeground(new java.awt.Color(59, 123, 50));
        lblTid2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblTid2.setText("Fecha Entrada");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.ipadx = 64;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 40, 0, 0);
        add(lblTid2, gridBagConstraints);

        scrpnlsGrupos.setBackground(new java.awt.Color(255, 255, 255));
        scrpnlsGrupos.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(59, 123, 50)), "Grupos a Rotar", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12), new java.awt.Color(59, 123, 50))); // NOI18N
        scrpnlsGrupos.setForeground(new java.awt.Color(59, 123, 50));

        pnlGrupos.setBackground(new java.awt.Color(255, 255, 255));
        pnlGrupos.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                pnlGruposComponentAdded(evt);
            }
            public void componentRemoved(java.awt.event.ContainerEvent evt) {
                pnlGruposComponentRemoved(evt);
            }
        });
        pnlGrupos.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        scrpnlsGrupos.setViewportView(pnlGrupos);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.gridwidth = 11;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 519;
        gridBagConstraints.ipady = 67;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(10, 40, 0, 18);
        add(scrpnlsGrupos, gridBagConstraints);

        btnGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconos/guardar.png"))); // NOI18N
        btnGuardar.setToolTipText("Guardar");
        btnGuardar.setBorderPainted(false);
        btnGuardar.setContentAreaFilled(false);
        btnGuardar.setMargin(new java.awt.Insets(2, 10, 2, 8));
        btnGuardar.setName("btnGuardar"); // NOI18N
        btnGuardar.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconos/guardar_over.png"))); // NOI18N
        btnGuardar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconos/guardar_over.png"))); // NOI18N
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.ipadx = -23;
        gridBagConstraints.ipady = -9;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHEAST;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(10, 40, 16, 0);
        add(btnGuardar, gridBagConstraints);

        btnDescartar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconos/descartar.png"))); // NOI18N
        btnDescartar.setToolTipText("Descartar");
        btnDescartar.setBorderPainted(false);
        btnDescartar.setContentAreaFilled(false);
        btnDescartar.setMargin(new java.awt.Insets(2, 10, 2, 8));
        btnDescartar.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconos/descartar_over.png"))); // NOI18N
        btnDescartar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconos/descartar_over.png"))); // NOI18N
        btnDescartar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDescartarActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.gridwidth = 6;
        gridBagConstraints.ipadx = -23;
        gridBagConstraints.ipady = -9;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(10, 6, 16, 0);
        add(btnDescartar, gridBagConstraints);

        lblTid3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblTid3.setForeground(new java.awt.Color(59, 123, 50));
        lblTid3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblTid3.setText("Lote");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.ipadx = 122;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(20, 40, 0, 0);
        add(lblTid3, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridwidth = 10;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 173;
        gridBagConstraints.ipady = 10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 40, 0, 0);
        add(jdFechaEntrada, gridBagConstraints);

        scrpnlsGrupos1.setBackground(new java.awt.Color(255, 255, 255));
        scrpnlsGrupos1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(59, 123, 50)), "Agregar Grupos", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12), new java.awt.Color(59, 123, 50))); // NOI18N
        scrpnlsGrupos1.setForeground(new java.awt.Color(59, 123, 50));

        pnlGruposMostrar.setBackground(new java.awt.Color(255, 255, 255));
        pnlGruposMostrar.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                pnlGruposMostrarComponentAdded(evt);
            }
            public void componentRemoved(java.awt.event.ContainerEvent evt) {
                pnlGruposMostrarComponentRemoved(evt);
            }
        });
        pnlGruposMostrar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        scrpnlsGrupos1.setViewportView(pnlGruposMostrar);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 10;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.VERTICAL;
        gridBagConstraints.ipadx = 169;
        gridBagConstraints.ipady = 147;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHEAST;
        gridBagConstraints.weightx = 0.3;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(10, 26, 0, 18);
        add(scrpnlsGrupos1, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    private void cbFincaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbFincaActionPerformed
        idFinca = listaFincas.get(cbFinca.getSelectedIndex()).get("ID");
        CargarListaLotes(idFinca);
    }//GEN-LAST:event_cbFincaActionPerformed

    private void cbLoteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbLoteActionPerformed
        System.out.println("listaLotes->"+listaLotes.size());
        if(cbLote.getSelectedIndex() > -1)
            idLote = listaLotes.get(cbLote.getSelectedIndex()).get("IDLOTE");
    }//GEN-LAST:event_cbLoteActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        Guardar();
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnDescartarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDescartarActionPerformed
        LimpiarFomulario();
    }//GEN-LAST:event_btnDescartarActionPerformed

    private void pnlGruposComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_pnlGruposComponentAdded
        //pnlGrupos.repaint();
    }//GEN-LAST:event_pnlGruposComponentAdded

    private void pnlGruposComponentRemoved(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_pnlGruposComponentRemoved
        // TODO add your handling code here:
    }//GEN-LAST:event_pnlGruposComponentRemoved

    private void pnlGruposMostrarComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_pnlGruposMostrarComponentAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_pnlGruposMostrarComponentAdded

    private void pnlGruposMostrarComponentRemoved(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_pnlGruposMostrarComponentRemoved
        // TODO add your handling code here:
    }//GEN-LAST:event_pnlGruposMostrarComponentRemoved


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDescartar;
    private javax.swing.JButton btnGuardar;
    public javax.swing.JComboBox cbFinca;
    public javax.swing.JComboBox cbLote;
    private com.toedter.calendar.JDateChooser jdFechaEntrada;
    private javax.swing.JLabel lblTid;
    private javax.swing.JLabel lblTid2;
    private javax.swing.JLabel lblTid3;
    private javax.swing.JPanel pnlGrupos;
    private javax.swing.JPanel pnlGruposMostrar;
    private javax.swing.JScrollPane scrpnlsGrupos;
    private javax.swing.JScrollPane scrpnlsGrupos1;
    // End of variables declaration//GEN-END:variables

    private void CargarListaFincas() {
        System.out.println("******CargarListaFincas****");
        listaFincas = controlgen.GetComboBox("SELECT '-1' AS ID, 'Seleccionar' AS DESCRIPCION\n" +
                                                "UNION\n" +
                                                "SELECT `id` AS ID, `descripcion` AS DESCRIPCION\n" +
                                                "FROM `fincas`\n"+
                                                "UNION \n"+
                                                "SELECT 'ALL' AS ID, 'TODOS' AS DESCRIPCION");
        Utilidades.LlenarComboBox(cbFinca, listaFincas, "DESCRIPCION");
        cbFinca.setSelectedItem(""+ListaGruposSeleccionados.get(0).get("FINCA"));
        CargarListaLotes(ListaGruposSeleccionados.get(0).get("IDFINCA"));
    }
    private void CargarListaLotes(String idFinca) {
        System.out.println("******CargarListaGrupos****");
        listaLotes = controlgen.GetComboBox("SELECT '-1' AS IDLOTE, '' AS LOTE, \n" +
                                                "'' AS IDBLOQUE, '' AS BLOQUE, \n" +
                                                "'Seleccionar' AS DESCRIPCION\n" +
                                                "UNION\n" +
                                                "SELECT l.`id` AS IDLOTE, CONCAT('Lote ',l.`numero`) AS LOTE,\n" +
                                                "b.`id` AS IDBLOQUE, CONCAT('Bloque ', b.`numero`) AS BLOQUE,\n" +
                                                "CONCAT(CONCAT('Bloque ', b.`numero`), ' / ', CONCAT('Lote ',l.`numero`)) AS DESCRIPCION\n" +
                                                "FROM bloques b\n" +
                                                "INNER JOIN lotes l ON l.`id_bloque` = b.`id`\n" +
                                                "WHERE b.`id_finca` = '"+idFinca+"'");
        Utilidades.LlenarComboBox(cbLote, listaLotes, "DESCRIPCION");
    }
    
    private void getGruposSistema() {
        ListaGrupos = controlRotar.getGruposxFinca(idFinca);
    }
    
    private void Guardar() {
        
        modeloRotacionLotes.setId("0");
        modeloRotacionLotes.setId_lote(idLote);
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
        Calendar fecha = jdFechaEntrada.getCalendar();
        modeloRotacionLotes.setFecha_entrada(sdf.format(fecha.getTime()));
        modeloRotacionLotes.setFecha("NOW()");
        modeloRotacionLotes.setEstado("Activo");
        modeloRotacionLotes.setId_usuario(datosUsuario.datos.get(0).get("ID_USUARIO"));
        
        Map<String, String> datos = new HashMap<>();
        datos.put("IDLOTE", ListaGruposSeleccionados.get(0).get("IDLOTE"));
        datos.put("FECHA_SALIDA", sdf.format(fecha.getTime()));
        System.out.println("ListaGruposSeleccionados.get(0).get(\"IDLOTE\")--->"+ListaGruposSeleccionados.get(0).get("IDLOTE"));
        if(!ListaGruposSeleccionados.get(0).get("IDLOTE").equals(""))
            controlRotar.ActualizarRotacionLote(datos);
        
        int ret = -1, ret2 = -1 ;
        if(modeloRotacionLotes.getId().equals("0")){//INSERT
            ret = controlRotar.Guardar(modeloRotacionLotes);
//        }else{
//            ret = controlBloque.Actualizar(modelo);
        }
        String idRotacionLotes = controlRotar.getId(idLote);
        
        for(int i = 0; i < Lista_Grupos_Seleccionados.size(); i++){
            ListamodeloRotacionGrupos.add(
                new ModeloRotacionGrupos(
                        "0", 
                        idRotacionLotes, 
                        ""+Lista_Grupos_Seleccionados.get(i).getId(), 
                        ""+Lista_Grupos_Seleccionados.get(i).getDatosMostrar(), 
                        "Activo", 
                        "NOW()", 
                        datosUsuario.datos.get(0).get("ID_USUARIO")));
        }
        for(int i = 0; i < ListamodeloRotacionGrupos.size(); i++){
            ret2 = controlRotar.GuardarRotacionGrupos(ListamodeloRotacionGrupos.get(i));
        }
        
        if(ret == 0){
            if(modeloVentanaGeneral.getPanelPadre() instanceof VistaRotacion){
                ((VistaRotacion)modeloVentanaGeneral.getPanelPadre()).RetornoVistaGeneral(modeloVentanaGeneral, modeloRotacionLotes); 
            }
            ((VistaGeneral)modeloVentanaGeneral.getFrameVentana()).dispose();
        }  
    }

    private void LimpiarFomulario() {
        cbFinca.setSelectedIndex(0);
        cbLote.removeAllItems();
        cbFinca.requestFocusInWindow();
        IniciarFecha();
    }
    public void IniciarFecha(){
        SimpleDateFormat formato = new SimpleDateFormat("yyyy-MM-dd");
        jdFechaEntrada.setCalendar(Calendar.getInstance());    
    }
    
    //<editor-fold defaultstate="collapsed" desc="Mostrar Grupos Panel">
        private void LlenarPnlGrupos() {
            System.out.println("********LlenarPnlGrupos********");
            System.out.println("ListaGruposSeleccionados.size()->"+ListaGruposSeleccionados.size());



            for(int i = 0; i < ListaGruposSeleccionados.size(); i++){
                Lista_Grupos_Seleccionados.add(
                    new ModeloDatosMultiple(
                            Integer.parseInt(ListaGruposSeleccionados.get(i).get("IDGRUPO")),  // ID
                            ListaGruposSeleccionados.get(i).get("GRUPO"),                      // DATO
                            getOriX(i), // X
                            getOriY(i), // Y
                            175,          // widthPnl
                            160,          // widthLblD
                            15,           // widthLblC 
                            25,           // heightPnl
                            20,           // height
                            3));          // padding
            }
            System.out.println("Lista_Grupos_Seleccionados-->"+Lista_Grupos_Seleccionados.size());
            MostrarGruposSeleccionados();

        }

        public int getOriX(int tam) {
            int ret = -1; 
            int filas = tam / cantpnl;
            int mod = tam % cantpnl;
            ret = 3 + (mod * (175 + 3));
            return ret;
        }

        private int getOriY(int tam) {
            int ret = -1;
            int filas = tam / cantpnl;      
            int mod = tam % cantpnl;
            ret = 3 + (filas * (25 + 3));
            return ret;
        }

        private void MostrarGruposSeleccionados() {
            System.out.println("*****************MostrarSeleccionados***************+" + Lista_Grupos_Seleccionados.size());
            ind = -1; 
            System.out.println("Lista_Grupos_Seleccionados-->"+Lista_Grupos_Seleccionados.size());
            pnlGrupos.removeAll();
            repaint();
            javax.swing.JPanel pnlDato = new javax.swing.JPanel();
            javax.swing.JLabel lblnombre = new javax.swing.JLabel();
            javax.swing.JLabel lblCerrar = new javax.swing.JLabel();

    //        //<editor-fold defaultstate="collapsed" desc="Boton Agregar">
    //            
    //            pnlDato.setBackground(new java.awt.Color(69, 148, 58));
    //            pnlDato.setForeground(new java.awt.Color(255, 255, 255));
    //            pnlDato.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
    //            pnlDato.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(59, 123, 50), 1, true));
    //            pnlDato.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
    //            pnlDato.setCursor(new Cursor(Cursor.HAND_CURSOR));
    //            pnlDato.addMouseListener(new java.awt.event.MouseAdapter() {
    //                public void mousePressed(java.awt.event.MouseEvent evt) {
    ////                    int indr = Integer.parseInt(evt.getComponent().getName());
    //                    AgregarGrupo();
    //                }
    //                
    //                public void mouseEntered(java.awt.event.MouseEvent evt) {
    //                    evt.getComponent().setBackground(new java.awt.Color(59, 123, 50));
    //                }
    //                public void mouseExited(java.awt.event.MouseEvent evt) {
    //                    evt.getComponent().setBackground(new java.awt.Color(69, 148, 58));
    //                }
    //            
    //            });
    //
    //            lblnombre.setText("Agregar Grupo");
    //            lblnombre.setForeground(new java.awt.Color(255, 255, 255));
    //            lblnombre.setFont(new java.awt.Font("Tahoma", 1, 12));
    //            
    //            lblCerrar.setFont(new java.awt.Font("Tahoma", 1, 12));
    //            lblCerrar.setText("+");//MousePressed
    //            lblCerrar.setName("-1");
    //            lblCerrar.setForeground(new java.awt.Color(255, 255, 255));
    //            lblCerrar.setCursor(new Cursor(Cursor.HAND_CURSOR));
    //            
    //            pnlDato.setToolTipText("Agregar Grupos"); 
    //            
    //            pnlDato.add(lblnombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(3, 3, 160, 20));
    //            pnlDato.add(lblCerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(3 + 160, 3, 15, 20));
    //            pnlGrupos.add(pnlDato, new org.netbeans.lib.awtextra.AbsoluteConstraints(3, 3, 175, 25));
    //        //</editor-fold>
            for (ModeloDatosMultiple obj : Lista_Grupos_Seleccionados) {
                ind++;
                pnlDato = new javax.swing.JPanel();
                lblnombre = new javax.swing.JLabel();
                lblCerrar = new javax.swing.JLabel();
                ///[26,82,118]
                pnlDato.setBackground(new java.awt.Color(59, 123, 50));
                pnlDato.setForeground(new java.awt.Color(255, 255, 255));
                pnlDato.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
                pnlDato.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(59, 123, 50), 1, true));
                pnlDato.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

                lblnombre.setText(obj.getDatosMostrar());
                lblnombre.setForeground(new java.awt.Color(255, 255, 255));

                lblCerrar.setFont(new java.awt.Font("Tahoma", 1, 12));
                lblCerrar.setText("X");//MousePressed
                lblCerrar.setName("" + ind);
                lblCerrar.setForeground(new java.awt.Color(255, 255, 255));
                lblCerrar.setCursor(new Cursor(Cursor.HAND_CURSOR));
                lblCerrar.addMouseListener(new java.awt.event.MouseAdapter() {
                    public void mousePressed(java.awt.event.MouseEvent evt) {
                        int indr = Integer.parseInt(evt.getComponent().getName());
                        ActualizarGruposSeleccionados(indr);
                    }
                });
                pnlDato.setToolTipText(obj.getDatosMostrar());
                pnlDato.add(lblnombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(3, 3, obj.getWidthLblD(), obj.getHeight()));
                pnlDato.add(lblCerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(3 + obj.getWidthLblD(), 3, obj.getWidthLblC(), obj.getHeight()));
                pnlGrupos.add(pnlDato, new org.netbeans.lib.awtextra.AbsoluteConstraints(obj.getX(), obj.getY(), obj.getWidthPnl(), obj.getHeightPnl()));
            }

            ((JFrame)modeloVentanaGeneral.getFrameVentana()).revalidate();
            ((JFrame)modeloVentanaGeneral.getFrameVentana()).repaint();
        }

        private void RecargarListaSeleccionados() {
            int ind = -1;
            for (ModeloDatosMultiple obj : Lista_Grupos_Seleccionados) {
                ind++;
                obj.setX(getOriX(ind));
                obj.setY(getOriY(ind));
            }
        }
        
        private void ActualizarGruposSeleccionados(int ind){
            ListaGruposMostrar.add(Lista_Grupos_Seleccionados.get(ind));
            Lista_Grupos_Seleccionados.remove(ind);
            RecargarListaSeleccionados();
            MostrarGruposSeleccionados(); 
            
            RecargarListaGruposMostrar();
            LlenarPnlGruposMostrar();
        }
        
        
        ////GRUPOS A MOSTRAR
        private void LlenarPnlGruposMostrar() {
            ind = -1; 
            System.out.println("ListaGruposMostrar-->"+ListaGruposMostrar.size());
            pnlGruposMostrar.removeAll();
            repaint();
            javax.swing.JPanel pnlDato = new javax.swing.JPanel();
            javax.swing.JLabel lblnombre = new javax.swing.JLabel();
            javax.swing.JLabel lblAgregar = new javax.swing.JLabel();

            for (ModeloDatosMultiple obj : ListaGruposMostrar) {
                ind++;
                pnlDato = new javax.swing.JPanel();
                lblnombre = new javax.swing.JLabel();
                lblAgregar = new javax.swing.JLabel();
                ///[26,82,118]
                pnlDato.setBackground(new java.awt.Color(59, 123, 50));
                pnlDato.setForeground(new java.awt.Color(255, 255, 255));
                pnlDato.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
                pnlDato.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(59, 123, 50), 1, true));
                pnlDato.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
                pnlDato.setCursor(new Cursor(Cursor.HAND_CURSOR));
                pnlDato.setName("" + ind);
                pnlDato.addMouseListener(new java.awt.event.MouseAdapter() {
                    public void mousePressed(java.awt.event.MouseEvent evt) {
                        int indr = Integer.parseInt(evt.getComponent().getName());
                        ActualizarGruposMostrar(indr);
                    }
                });

                lblnombre.setText(obj.getDatosMostrar());
                lblnombre.setForeground(new java.awt.Color(255, 255, 255));

                lblAgregar.setFont(new java.awt.Font("Tahoma", 1, 12));
                lblAgregar.setText("+");//MousePressed
                lblAgregar.setName("" + ind);
                lblAgregar.setForeground(new java.awt.Color(255, 255, 255));
                lblAgregar.setCursor(new Cursor(Cursor.HAND_CURSOR));
                
                pnlDato.setToolTipText("Agregar Grupo "+obj.getDatosMostrar());
                pnlDato.add(lblnombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(3, 3, obj.getWidthLblD(), obj.getHeight()));
                pnlDato.add(lblAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(3 + obj.getWidthLblD(), 3, obj.getWidthLblC(), obj.getHeight()));
                pnlGruposMostrar.add(pnlDato, new org.netbeans.lib.awtextra.AbsoluteConstraints(obj.getX(), obj.getY(), obj.getWidthPnl(), obj.getHeightPnl()));
            }

            ((JFrame)modeloVentanaGeneral.getFrameVentana()).revalidate();
            ((JFrame)modeloVentanaGeneral.getFrameVentana()).repaint();
        }
        public int getOriXMostrar(int tam) {
            int ret = -1; 
            int filas = tam / 1;
            int mod = tam % 1;
            ret = 3 + (mod * (175 + 3));
            return ret;
        }

        private int getOriYMostrar(int tam) {
            int ret = -1;
            int filas = tam / 1;      
            int mod = tam % 1;
            ret = 3 + (filas * (25 + 3));
            return ret;
        }
        private void RecargarListaGruposMostrar() {
            int ind = -1;
            for (ModeloDatosMultiple obj : ListaGruposMostrar) {
                ind++;
                obj.setX(getOriXMostrar(ind));
                obj.setY(getOriYMostrar(ind));
            }
        }
        
        private void ActualizarGruposMostrar(int ind){
            Lista_Grupos_Seleccionados.add(ListaGruposMostrar.get(ind));
            ListaGruposMostrar.remove(ind);
            RecargarListaGruposMostrar();
            LlenarPnlGruposMostrar();
                        
            RecargarListaSeleccionados();
            MostrarGruposSeleccionados(); 
        }
        
    //</editor-fold>    

    private void EstablecerGruposxMostrar() {
        int ind = -1;
        boolean encontro = false;
        for(int i = 0; i < ListaGrupos.size(); i++){
            encontro = false;
            for(int j = 0; j < Lista_Grupos_Seleccionados.size(); j++ ){
                if(Lista_Grupos_Seleccionados.get(j).getDatosMostrar().equals(ListaGrupos.get(i).get("DESCRIPCION"))){
                   encontro = true;
                    break;
                }
            }
            if(!encontro){
                ind++;
                ListaGruposMostrar.add(
                    new ModeloDatosMultiple(
                            Integer.parseInt(ListaGrupos.get(i).get("ID")),  // ID
                            ListaGrupos.get(i).get("DESCRIPCION"),                      // DATO
                            getOriXMostrar(ind), // X
                            getOriYMostrar(ind), // Y
                            175,          // widthPnl
                            160,          // widthLblD
                            15,           // widthLblC 
                            25,           // heightPnl
                            20,           // height
                            3));          // padding
            }
        }
    }

    

    

    

    

    
}
