/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Vistas;

import Busqueda.VistaBusqueda;
import Control.*;
import Modelo.*;
import Utilidades.Expresiones;
import Utilidades.Utilidades;
import Utilidades.datosUsuario;
import java.util.ArrayList;
import java.util.List;
import java.util.Map;
import javax.swing.DefaultListModel;

/**
 *
 * @author MERRY
 */
public class VistaLotes extends javax.swing.JPanel {
    private ModeloLotes  modelo;
    private ModeloFuentesHidricas  modeloFuente;
    private ModeloVentanaGeneral  modeloVentanaGeneral;
    private ControLotes controlLote;
    public int banBQDFuenteHidrica;
    ModeloGestorBusqueda objetoBusqueda;
    public List<Map<String, String>> listaBloques;
    public ControlGeneral controlgen = new ControlGeneral();
    
    
    
    /**
     * Creates new form VistaLotes
     */
    public VistaLotes() {
        initComponents();
        lblIdFuente.setVisible(false);
        banBQDFuenteHidrica = 0;
        modelo = new ModeloLotes();
        controlLote = new ControLotes();
        listaBloques = new ArrayList<>();
        CargarListaBloques();
        
    }
    
    public VistaLotes(ModeloVentanaGeneral modeloVentanaGeneral){
        initComponents();
        lblIdFuente.setVisible(false);
        banBQDFuenteHidrica = 0;
        this.modeloVentanaGeneral = modeloVentanaGeneral;
        controlLote = new ControLotes();
        this.modelo = (ModeloLotes)modeloVentanaGeneral.getModeloDatos();
        listaBloques = new ArrayList<>();
        CargarListaBloques();
        if(!modelo.getId().equals("0")){
            CargarDatos();
        }
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbltitle1 = new javax.swing.JLabel();
        txtNumero = new javax.swing.JTextField();
        jSeparator6 = new javax.swing.JSeparator();
        lbltitle3 = new javax.swing.JLabel();
        txtAreaT = new javax.swing.JTextField();
        jSeparator8 = new javax.swing.JSeparator();
        jLabel13 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        btnGuardar = new javax.swing.JButton();
        btnDescartar = new javax.swing.JButton();
        cbBloque = new javax.swing.JComboBox();
        lblTid = new javax.swing.JLabel();
        lbltitle4 = new javax.swing.JLabel();
        txtFuenteHidraulica = new javax.swing.JTextField();
        jSeparator9 = new javax.swing.JSeparator();
        lblBsqFuenteHidrica = new javax.swing.JLabel();
        btnAgregarFuenteHidrica = new javax.swing.JButton();
        lblIdFuente = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbltitle1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbltitle1.setForeground(new java.awt.Color(59, 123, 50));
        lbltitle1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbltitle1.setText("Número");
        add(lbltitle1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, 100, 20));

        txtNumero.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtNumero.setForeground(new java.awt.Color(59, 123, 50));
        txtNumero.setBorder(null);
        txtNumero.setCaretColor(new java.awt.Color(59, 123, 50));
        txtNumero.setFocusCycleRoot(true);
        txtNumero.setSelectionColor(new java.awt.Color(59, 123, 50));
        txtNumero.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtNumeroFocusLost(evt);
            }
        });
        txtNumero.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtNumeroKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtNumeroKeyReleased(evt);
            }
        });
        add(txtNumero, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, 400, 30));

        jSeparator6.setBackground(new java.awt.Color(59, 123, 50));
        add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 140, 400, 10));

        lbltitle3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbltitle3.setForeground(new java.awt.Color(59, 123, 50));
        lbltitle3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbltitle3.setText("Area Total");
        add(lbltitle3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 160, 100, 20));

        txtAreaT.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtAreaT.setForeground(new java.awt.Color(59, 123, 50));
        txtAreaT.setBorder(null);
        txtAreaT.setCaretColor(new java.awt.Color(59, 123, 50));
        txtAreaT.setFocusCycleRoot(true);
        txtAreaT.setSelectionColor(new java.awt.Color(59, 123, 50));
        txtAreaT.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtAreaTFocusLost(evt);
            }
        });
        txtAreaT.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtAreaTKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtAreaTKeyReleased(evt);
            }
        });
        add(txtAreaT, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 180, 400, 30));

        jSeparator8.setBackground(new java.awt.Color(59, 123, 50));
        add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 210, 400, 10));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(59, 123, 50));
        jLabel13.setText("mts");
        add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 180, -1, 30));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(59, 123, 50));
        jLabel12.setText("2");
        add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 170, -1, 30));

        btnGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconos/guardar.png"))); // NOI18N
        btnGuardar.setToolTipText("Guardar");
        btnGuardar.setBorderPainted(false);
        btnGuardar.setContentAreaFilled(false);
        btnGuardar.setMargin(new java.awt.Insets(2, 10, 2, 8));
        btnGuardar.setName("btnGuardar"); // NOI18N
        btnGuardar.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconos/guardar_over.png"))); // NOI18N
        btnGuardar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconos/guardar_over.png"))); // NOI18N
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        add(btnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 320, 64, 64));

        btnDescartar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconos/descartar.png"))); // NOI18N
        btnDescartar.setToolTipText("Descartar");
        btnDescartar.setBorderPainted(false);
        btnDescartar.setContentAreaFilled(false);
        btnDescartar.setMargin(new java.awt.Insets(2, 10, 2, 8));
        btnDescartar.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconos/descartar_over.png"))); // NOI18N
        btnDescartar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconos/descartar_over.png"))); // NOI18N
        btnDescartar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDescartarActionPerformed(evt);
            }
        });
        add(btnDescartar, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 320, 64, 64));

        cbBloque.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        cbBloque.setForeground(new java.awt.Color(59, 123, 50));
        cbBloque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbBloqueActionPerformed(evt);
            }
        });
        add(cbBloque, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 40, 400, 30));

        lblTid.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblTid.setForeground(new java.awt.Color(59, 123, 50));
        lblTid.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblTid.setText("Bloque");
        add(lblTid, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, 150, -1));

        lbltitle4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbltitle4.setForeground(new java.awt.Color(59, 123, 50));
        lbltitle4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbltitle4.setText("Fuente Hidrica");
        add(lbltitle4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 240, 110, 10));

        txtFuenteHidraulica.setEditable(false);
        txtFuenteHidraulica.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtFuenteHidraulica.setForeground(new java.awt.Color(59, 123, 50));
        txtFuenteHidraulica.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtFuenteHidraulica.setBorder(null);
        txtFuenteHidraulica.setCaretColor(new java.awt.Color(59, 123, 50));
        txtFuenteHidraulica.setSelectionColor(new java.awt.Color(59, 123, 50));
        add(txtFuenteHidraulica, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 260, 400, 30));

        jSeparator9.setBackground(new java.awt.Color(59, 123, 50));
        add(jSeparator9, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 290, 400, 10));

        lblBsqFuenteHidrica.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconos/lupa_1.png"))); // NOI18N
        lblBsqFuenteHidrica.setToolTipText("Consultar Arrendatario");
        lblBsqFuenteHidrica.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblBsqFuenteHidrica.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblBsqFuenteHidricaMouseClicked(evt);
            }
        });
        add(lblBsqFuenteHidrica, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 260, 30, 30));

        btnAgregarFuenteHidrica.setBackground(new java.awt.Color(0, 0, 204));
        btnAgregarFuenteHidrica.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconos/add.png"))); // NOI18N
        btnAgregarFuenteHidrica.setToolTipText("Agregar Arrendatario");
        btnAgregarFuenteHidrica.setBorder(null);
        btnAgregarFuenteHidrica.setBorderPainted(false);
        btnAgregarFuenteHidrica.setContentAreaFilled(false);
        btnAgregarFuenteHidrica.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAgregarFuenteHidrica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarFuenteHidricaActionPerformed(evt);
            }
        });
        add(btnAgregarFuenteHidrica, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 260, 30, 30));
        add(lblIdFuente, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void txtNumeroFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNumeroFocusLost

    }//GEN-LAST:event_txtNumeroFocusLost

    private void txtNumeroKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNumeroKeyPressed

    }//GEN-LAST:event_txtNumeroKeyPressed

    private void txtNumeroKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNumeroKeyReleased

    }//GEN-LAST:event_txtNumeroKeyReleased

    private void txtAreaTFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtAreaTFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAreaTFocusLost

    private void txtAreaTKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAreaTKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAreaTKeyPressed

    private void txtAreaTKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAreaTKeyReleased
        String areat = txtAreaT.getText();
        String valorsin = areat.indexOf(".") > -1 ? areat.replace(".", "") : areat;
        String dato = Expresiones.procesarSoloNumP(valorsin);
        dato = Utilidades.MascaraMonedaConDecimales(dato);
        txtAreaT.setText(dato);
    }//GEN-LAST:event_txtAreaTKeyReleased

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        Guardar();
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnDescartarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDescartarActionPerformed
        LimpiarFomulario();
    }//GEN-LAST:event_btnDescartarActionPerformed

    private void cbBloqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbBloqueActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbBloqueActionPerformed

    private void lblBsqFuenteHidricaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBsqFuenteHidricaMouseClicked
        if(banBQDFuenteHidrica == 0){
            banBQDFuenteHidrica = 1;
            //new ventanaBusquedaPaciente(1, "IDENTIFICACION:-:NOMBRE", estadoch, this);
            if(lblBsqFuenteHidrica.isEnabled()){
                objetoBusqueda = new ModeloGestorBusqueda(this, "BQD_FNT_HDRC", 1);
                LimpiarFuenteHidrica();
                new VistaBusqueda(objetoBusqueda);
            }
        }
    }//GEN-LAST:event_lblBsqFuenteHidricaMouseClicked

    private void btnAgregarFuenteHidricaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarFuenteHidricaActionPerformed
        //new VistaContratos(this).setVisible(true);
        btnAgregarFuenteHidrica.setEnabled(false);
        modeloFuente = new ModeloFuentesHidricas();
        
        modeloFuente.setId("0");
        
        modeloVentanaGeneral = new ModeloVentanaGeneral(this, new VistaFuentesHidricas(), 1, modeloFuente);
        
        LimpiarFuenteHidrica();
        new VistaGeneral(modeloVentanaGeneral).setVisible(true);
    }//GEN-LAST:event_btnAgregarFuenteHidricaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnAgregarFuenteHidrica;
    private javax.swing.JButton btnDescartar;
    private javax.swing.JButton btnGuardar;
    public javax.swing.JComboBox cbBloque;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JLabel lblBsqFuenteHidrica;
    private javax.swing.JLabel lblIdFuente;
    private javax.swing.JLabel lblTid;
    public javax.swing.JLabel lbltitle1;
    public javax.swing.JLabel lbltitle3;
    private javax.swing.JLabel lbltitle4;
    public javax.swing.JTextField txtAreaT;
    public javax.swing.JTextField txtFuenteHidraulica;
    public javax.swing.JTextField txtNumero;
    // End of variables declaration//GEN-END:variables

    private void LimpiarFuenteHidrica() {
        lblIdFuente.setText("");
        txtFuenteHidraulica.setText("");
    }
    
     //<editor-fold defaultstate="collapsed" desc="Metodo Busqueda Retorno">
    public void RetornoBusqueda(ModeloGestorBusqueda objeto, Map<String, String> retorno) {
        
        if(objeto.getOpcion() == 0){// DEFAULT VISTA__VENTANA__
            
        }else if(objeto.getOpcion() == 1){// FUENTES
            lblIdFuente.setText(""+retorno.get("ID"));
            txtFuenteHidraulica.setText(""+retorno.get("FUENTE"));
        }
    }
    //</editor-fold>

    public void RetornoVistaGeneral(ModeloVentanaGeneral objeto, Object retorno) {
        
        if(objeto.getOpcion() == 1){// VISTA FUENTES
            modeloFuente = (ModeloFuentesHidricas) retorno;
            lblIdFuente.setText(""+modeloFuente.getId());
            txtFuenteHidraulica.setText(""+modeloFuente.getDescripcion());
        }
    }
//    

    
    


    private void LimpiarFomulario() {
        cbBloque.setSelectedIndex(0);
        txtNumero.setText("");
        txtAreaT.setText("");
        lblIdFuente.setText("");
        txtFuenteHidraulica.setText("");
    }

    private void Guardar() {
        modelo.setId_bloque(""+listaBloques.get(cbBloque.getSelectedIndex()).get("ID"));
        modelo.setNumero(txtNumero.getText().trim());
        modelo.setArea(txtAreaT.getText().trim().replace(".", "").replace(",", "."));
        modelo.setId_fuente_hidrica(""+lblIdFuente.getText());
        modelo.setFecha("NOW()");
        modelo.setId_usuario(datosUsuario.datos.get(0).get("ID_USUARIO"));
        
        int ret = -1;
        if(modelo.getId().equals("0")){//INSERT
            ret = controlLote.Guardar(modelo);
        }else{
            ret = controlLote.Actualizar(modelo);
        }
        
        if(ret == 0){
            if(modeloVentanaGeneral.getPanelPadre() instanceof VistaFincas){
                ((VistaFincas)modeloVentanaGeneral.getPanelPadre()).RetornoVistaGeneral(modeloVentanaGeneral, modelo); 
            }
            ((VistaGeneral)modeloVentanaGeneral.getFrameVentana()).dispose();
        }  
    }

    private void CargarDatos() {
        cbBloque.setSelectedItem("Bloque "+modelo.getId_bloque());
        txtNumero.setText(""+modelo.getNumero());
        txtAreaT.setText(""+Utilidades.MascaraMonedaConDecimales(modelo.getArea()));  
        lblIdFuente.setText(""+modelo.getId_fuente_hidrica());
        txtFuenteHidraulica.setText("");
    }

    private void CargarListaBloques() {
        System.out.println("modelo.getId_finca()-->"+modelo.getId_finca());
        listaBloques = controlgen.GetComboBox("SELECT '-1' AS ID, 'Seleccionar' AS NUMERO, '' AS AREAT\n" +
                                                "UNION\n" +
                                                "SELECT b.id AS ID, CONCAT('Bloque ', b.numero) AS NUMERO, b.area AS AREAT\n" +
                                                "FROM bloques b\n" +
                                                "WHERE b.id_finca = '"+modelo.getId_finca()+"'" );
        
        Utilidades.LlenarComboBox(cbBloque, listaBloques, "NUMERO");
       
    }
    
}
