/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Vistas;

import Control.ControlGeneral;
import Control.ControlTraslado;
import Utilidades.Utilidades;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.List;
import java.util.Map;
import javax.swing.DefaultListModel;
import javax.swing.DefaultListSelectionModel;
import javax.swing.JComboBox;

/**
 *
 * @author MERRY
 */
public class VistaTrasladoGrupos extends javax.swing.JPanel {
    public List<Map<String, String>> listaFincas;
    public List<Map<String, String>> listaTipoAnimales;
    public List<Map<String, String>> listaFincasDestino;
    public List<Map<String, String>> listaTipoAnimalesDestino;
    public ControlGeneral controlgen = new ControlGeneral();
    public String idFinca;
    public String idFincaDestino;
    public String idTipoAnimal;
    public String idTipoAnimalDestino;
    public List<Map<String, String>> listaGrupos;
    public List<Map<String, String>> listaGruposDestino;
    public DefaultListModel modlistGrupos;
    public DefaultListModel modlistGruposDestino;
    private ControlTraslado controlTraslado = new ControlTraslado();
    /**
     * Creates new form VistaTrasladoGrupos
     */
    public VistaTrasladoGrupos() {
        initComponents();
        lstGruposOrigen.setSelectionModel(new DefaultListSelectionModel() {
            private int i0 = -1;
            private int i1 = -1;

            public void setSelectionInterval(int index0, int index1) {
                if(i0 == index0 && i1 == index1){
                    if(getValueIsAdjusting()){
                         setValueIsAdjusting(false);
                         setSelection(index0, index1);
                    }
                }else{
                    i0 = index0;
                    i1 = index1;
                    setValueIsAdjusting(false);
                    setSelection(index0, index1);
                }
            }
            private void setSelection(int index0, int index1){
                if(super.isSelectedIndex(index0)) {
                    super.removeSelectionInterval(index0, index1);
                }else {
                    super.addSelectionInterval(index0, index1);
                }
            }
        });
        listaFincas = new ArrayList<>();
        listaTipoAnimales = new ArrayList<>();
        listaFincasDestino = new ArrayList<>();
        listaTipoAnimalesDestino = new ArrayList<>();
        listaGrupos = new ArrayList<>();
        listaGruposDestino = new ArrayList<>();
        idFinca = "";
        idTipoAnimal = "";
        idFincaDestino = "";
        idTipoAnimalDestino = "";
        modlistGrupos = new DefaultListModel();
        modlistGruposDestino = new DefaultListModel();
        IniciarFecha();
        LlenarListaFincas();
        CargarListaFincas(0, cbFinca);
        CargarListaFincas(1, cbFincaDestino);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        lblTid = new javax.swing.JLabel();
        cbFinca = new javax.swing.JComboBox();
        cbTipoAnimales = new javax.swing.JComboBox();
        lblTid3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstGruposOrigen = new javax.swing.JList();
        jPanel4 = new javax.swing.JPanel();
        jdFechaTraslado = new com.toedter.calendar.JDateChooser();
        lblTid4 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        lstGrupoDestino = new javax.swing.JList();
        lblTid1 = new javax.swing.JLabel();
        cbFincaDestino = new javax.swing.JComboBox();
        cbTipoAnimalesDestino = new javax.swing.JComboBox();
        lblTid5 = new javax.swing.JLabel();
        btnDescartar = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Traslado Origen", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12), new java.awt.Color(59, 123, 50))); // NOI18N
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTid.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblTid.setForeground(new java.awt.Color(59, 123, 50));
        lblTid.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblTid.setText("Finca");
        jPanel3.add(lblTid, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 28, -1, -1));

        cbFinca.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        cbFinca.setForeground(new java.awt.Color(59, 123, 50));
        cbFinca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbFincaActionPerformed(evt);
            }
        });
        jPanel3.add(cbFinca, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 48, 232, 30));

        cbTipoAnimales.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        cbTipoAnimales.setForeground(new java.awt.Color(59, 123, 50));
        cbTipoAnimales.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbTipoAnimalesActionPerformed(evt);
            }
        });
        jPanel3.add(cbTipoAnimales, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 108, 232, 30));

        lblTid3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblTid3.setForeground(new java.awt.Color(59, 123, 50));
        lblTid3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblTid3.setText("Tipo Animales");
        jPanel3.add(lblTid3, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 88, -1, -1));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Grupos", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12), new java.awt.Color(59, 123, 50))); // NOI18N

        lstGruposOrigen.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        lstGruposOrigen.setSelectionBackground(new java.awt.Color(59, 123, 50));
        lstGruposOrigen.setValueIsAdjusting(true);
        jScrollPane1.setViewportView(lstGruposOrigen);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        jPanel3.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 144, -1, 300));

        add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 260, 460));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Traslado Destino", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12), new java.awt.Color(59, 123, 50))); // NOI18N
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel4.add(jdFechaTraslado, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 165, 230, 30));

        lblTid4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblTid4.setForeground(new java.awt.Color(59, 123, 50));
        lblTid4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblTid4.setText("Fecha Traslado");
        jPanel4.add(lblTid4, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 145, -1, -1));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Grupo ", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12), new java.awt.Color(59, 123, 50))); // NOI18N

        lstGrupoDestino.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        lstGrupoDestino.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        lstGrupoDestino.setSelectionBackground(new java.awt.Color(59, 123, 50));
        lstGrupoDestino.setValueIsAdjusting(true);
        jScrollPane2.setViewportView(lstGrupoDestino);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(13, Short.MAX_VALUE))
        );

        jPanel4.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 206, 230, 237));

        lblTid1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblTid1.setForeground(new java.awt.Color(59, 123, 50));
        lblTid1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblTid1.setText("Finca");
        jPanel4.add(lblTid1, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 28, -1, -1));

        cbFincaDestino.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        cbFincaDestino.setForeground(new java.awt.Color(59, 123, 50));
        cbFincaDestino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbFincaDestinoActionPerformed(evt);
            }
        });
        jPanel4.add(cbFincaDestino, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 48, 230, 30));

        cbTipoAnimalesDestino.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        cbTipoAnimalesDestino.setForeground(new java.awt.Color(59, 123, 50));
        cbTipoAnimalesDestino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbTipoAnimalesDestinoActionPerformed(evt);
            }
        });
        jPanel4.add(cbTipoAnimalesDestino, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 109, 230, 30));

        lblTid5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblTid5.setForeground(new java.awt.Color(59, 123, 50));
        lblTid5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblTid5.setText("Tipo Animales");
        jPanel4.add(lblTid5, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 89, -1, -1));

        add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 20, 260, 460));

        btnDescartar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconos/descartar.png"))); // NOI18N
        btnDescartar.setToolTipText("Descartar");
        btnDescartar.setBorderPainted(false);
        btnDescartar.setContentAreaFilled(false);
        btnDescartar.setMargin(new java.awt.Insets(2, 10, 2, 8));
        btnDescartar.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconos/descartar_over.png"))); // NOI18N
        btnDescartar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconos/descartar_over.png"))); // NOI18N
        btnDescartar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDescartarActionPerformed(evt);
            }
        });
        add(btnDescartar, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 490, -1, -1));

        btnGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconos/guardar.png"))); // NOI18N
        btnGuardar.setToolTipText("Guardar");
        btnGuardar.setBorderPainted(false);
        btnGuardar.setContentAreaFilled(false);
        btnGuardar.setMargin(new java.awt.Insets(2, 10, 2, 8));
        btnGuardar.setName("btnGuardar"); // NOI18N
        btnGuardar.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconos/guardar_over.png"))); // NOI18N
        btnGuardar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconos/guardar_over.png"))); // NOI18N
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        add(btnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 490, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void cbFincaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbFincaActionPerformed
        if(cbFinca.getItemCount() > 0){
            idFinca = listaFincas.get(cbFinca.getSelectedIndex()).get("ID");
            FuncionLlenarTipoAnimales(0);
        }
    }//GEN-LAST:event_cbFincaActionPerformed

    private void cbTipoAnimalesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbTipoAnimalesActionPerformed
        if(cbTipoAnimales.getItemCount() > 0){
            idTipoAnimal = listaTipoAnimales.get(cbTipoAnimales.getSelectedIndex()).get("ID");
            //FuncionLlenarGrupos(0);
        }
    }//GEN-LAST:event_cbTipoAnimalesActionPerformed

    private void cbFincaDestinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbFincaDestinoActionPerformed
        if(cbFincaDestino.getItemCount() > 0){
            idFincaDestino = listaFincas.get(cbFincaDestino.getSelectedIndex()).get("ID");
            FuncionLlenarTipoAnimales(1);
        }
    }//GEN-LAST:event_cbFincaDestinoActionPerformed

    private void cbTipoAnimalesDestinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbTipoAnimalesDestinoActionPerformed
        if(cbTipoAnimalesDestino.getItemCount() > 0){
            idTipoAnimalDestino = listaTipoAnimalesDestino.get(cbTipoAnimalesDestino.getSelectedIndex()).get("ID");
            //FuncionLlenarGrupos(1);
        }
    }//GEN-LAST:event_cbTipoAnimalesDestinoActionPerformed

    private void btnDescartarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDescartarActionPerformed
        LimpiarFomulario();
    }//GEN-LAST:event_btnDescartarActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        Guardar();
    }//GEN-LAST:event_btnGuardarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDescartar;
    private javax.swing.JButton btnGuardar;
    public javax.swing.JComboBox cbFinca;
    public javax.swing.JComboBox cbFincaDestino;
    public javax.swing.JComboBox cbTipoAnimales;
    public javax.swing.JComboBox cbTipoAnimalesDestino;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private com.toedter.calendar.JDateChooser jdFechaTraslado;
    private javax.swing.JLabel lblTid;
    private javax.swing.JLabel lblTid1;
    private javax.swing.JLabel lblTid3;
    private javax.swing.JLabel lblTid4;
    private javax.swing.JLabel lblTid5;
    private javax.swing.JList lstGrupoDestino;
    private javax.swing.JList lstGruposOrigen;
    // End of variables declaration//GEN-END:variables

    private void LlenarListaFincas(){
        listaFincas = controlgen.GetComboBox("SELECT '-1' AS ID, 'Seleccionar' AS DESCRIPCION\n" +
                                                "UNION\n" +
                                                "SELECT `id` AS ID, `descripcion` AS DESCRIPCION\n" +
                                                "FROM `fincas`\n"+
                                                "/*UNION \n"+
                                                "SELECT 'ALL' AS ID, 'TODOS' AS DESCRIPCION*/");
    }
    
    private void CargarListaFincas(int opc, JComboBox jcombo) {
        Utilidades.LlenarComboBox(jcombo, listaFincas, "DESCRIPCION");
        jcombo.setSelectedIndex(1);
    }
    
    private void FuncionLlenarTipoAnimales(int opc){
        if(opc == 0){//ORIGEN
            listaTipoAnimales = controlgen.GetComboBox("SELECT '-1' AS ID, 'Seleccionar' AS DESCRIPCION\n" +
                                                    "UNION\n" +
                                                    "SELECT id AS ID, descripcion AS DESCRIPCION\n" +
                                                    "FROM `tipo_animales`\n" +
                                                    "WHERE id_finca = '"+idFinca+"' AND estado = 'Activo'\n" +
                                                    "ORDER BY id ASC");
            Utilidades.LlenarComboBox(cbTipoAnimales, listaTipoAnimales, "DESCRIPCION");
            cbTipoAnimales.setSelectedIndex(0);
        }else{
            listaTipoAnimalesDestino = controlgen.GetComboBox("SELECT '-1' AS ID, 'Seleccionar' AS DESCRIPCION\n" +
                                                    "UNION\n" +
                                                    "SELECT id AS ID, descripcion AS DESCRIPCION\n" +
                                                    "FROM `tipo_animales`\n" +
                                                    "WHERE id_finca = '"+idFincaDestino+"' AND estado = 'Activo'\n" +
                                                    "ORDER BY id ASC");
            Utilidades.LlenarComboBox(cbTipoAnimalesDestino, listaTipoAnimalesDestino, "DESCRIPCION");
            cbTipoAnimalesDestino.setSelectedIndex(0);
        }
        
    }
    
    public void IniciarFecha() {
        SimpleDateFormat formato = new SimpleDateFormat("yyyy-MM-dd");
        jdFechaTraslado.setCalendar(Calendar.getInstance());
    }

    private void LimpiarLstGrupos() {
        modlistGrupos.removeAllElements();
        lstGruposOrigen.setModel(modlistGrupos);
    }
    
    private void LimpiarLstGruposDestino() {
        modlistGruposDestino.removeAllElements();
        lstGrupoDestino.setModel(modlistGruposDestino);
    }
    
    private void LimpiarFomulario() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    private void Guardar() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
    
    
}
