/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package pruebas;

import Excel.ControlArchivo;
import Utilidades.Expresiones;
import com.lowagie.text.DocumentException;
import java.awt.Color;
import java.io.IOException;
import java.util.List;
import java.util.Map;
import javax.swing.JOptionPane;

/**
 *
 * @author MERRY
 */
public class LEcturaExcel extends javax.swing.JFrame {

    /**
     * Creates new form LEcturaExcel
     */
    public LEcturaExcel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblTid = new javax.swing.JLabel();
        txtURL = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel4 = new javax.swing.JPanel();
        btnSelectArchivo = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        btnSelectArchivo1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTid.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblTid.setForeground(new java.awt.Color(26, 82, 118));
        lblTid.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblTid.setText("Archivo");
        jPanel1.add(lblTid, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, 60, -1));

        txtURL.setEditable(false);
        txtURL.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        txtURL.setCaretColor(new java.awt.Color(26, 82, 118));
        txtURL.setSelectionColor(new java.awt.Color(26, 82, 118));
        jPanel1.add(txtURL, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 140, 350, 30));

        jSeparator1.setBackground(new java.awt.Color(59, 123, 50));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 170, 350, -1));

        jPanel4.setBackground(new java.awt.Color(26, 82, 118));

        btnSelectArchivo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnSelectArchivo.setForeground(new java.awt.Color(255, 255, 255));
        btnSelectArchivo.setText("Seleccionar Archivo");
        btnSelectArchivo.setBorderPainted(false);
        btnSelectArchivo.setContentAreaFilled(false);
        btnSelectArchivo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnSelectArchivoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnSelectArchivoMouseExited(evt);
            }
        });
        btnSelectArchivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSelectArchivoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 151, Short.MAX_VALUE)
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel4Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(btnSelectArchivo)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel4Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(btnSelectArchivo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 140, -1, 30));

        jPanel5.setBackground(new java.awt.Color(26, 82, 118));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnSelectArchivo1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnSelectArchivo1.setForeground(new java.awt.Color(255, 255, 255));
        btnSelectArchivo1.setText("Generar");
        btnSelectArchivo1.setBorderPainted(false);
        btnSelectArchivo1.setContentAreaFilled(false);
        btnSelectArchivo1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnSelectArchivo1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnSelectArchivo1MouseExited(evt);
            }
        });
        btnSelectArchivo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSelectArchivo1ActionPerformed(evt);
            }
        });
        jPanel5.add(btnSelectArchivo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 100, 30));

        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 230, 100, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSelectArchivoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSelectArchivoMouseEntered
        jPanel4.setBackground(new Color(31, 97, 141));
    }//GEN-LAST:event_btnSelectArchivoMouseEntered

    private void btnSelectArchivoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSelectArchivoMouseExited
        jPanel4.setBackground(new Color(26, 82, 118));
    }//GEN-LAST:event_btnSelectArchivoMouseExited

    private void btnSelectArchivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSelectArchivoActionPerformed
        txtURL.setText(Expresiones.seleccionarArchivoExcel(false, "C:/"));
        //System.out.println("txtURL-->"+txtURL.getText());
    }//GEN-LAST:event_btnSelectArchivoActionPerformed

    private void btnSelectArchivo1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSelectArchivo1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSelectArchivo1MouseEntered

    private void btnSelectArchivo1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSelectArchivo1MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSelectArchivo1MouseExited

    private void btnSelectArchivo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSelectArchivo1ActionPerformed
        try {
            Generar();
        }catch(DocumentException e){

        }catch(IOException e){

        }
    }//GEN-LAST:event_btnSelectArchivo1ActionPerformed

    /**
     * @param args the command line arguments
     */
    
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LEcturaExcel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LEcturaExcel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LEcturaExcel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LEcturaExcel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LEcturaExcel().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnSelectArchivo;
    public javax.swing.JButton btnSelectArchivo1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblTid;
    public javax.swing.JTextField txtURL;
    // End of variables declaration//GEN-END:variables

    private void Generar() throws DocumentException, IOException {
        String ruta = txtURL.getText().trim();
        System.out.println("ruta-->"+ruta);
        ControlArchivo con = new ControlArchivo();
        
        List<Map<String, String>> lista =  con.LeerExcelAct(ruta);
        
        System.out.println("list--->"+lista);
        for (Map<String, String> map : lista) {
            System.out.println("************************************************************************************************");
            for (Map.Entry<String, String> entry : map.entrySet()) {
                Object key = entry.getKey();
                Object val = entry.getValue();
                System.out.println("key-->"+key+"-------+value-->"+val);

            }
        }
        
//            GeneracionActas gen = new GeneracionActas();
//            gen.GenerarActas(ruta);
    }

}


