/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas.Inventario;

import Modelo.ModeloVentanaGeneral;
import Tablas.TablaRender;
import Vistas.VistaGeneral;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Font;
import java.util.ArrayList;
import javax.swing.JLabel;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;

/**
 *
 * @author DOLFHANDLER
 */
public class VistaInventario extends javax.swing.JPanel {

    public DefaultTableModel modeloTblInventario;
    public String[] NameColumnas;
    public String[] EncabezadoTblInventario;
    public ModeloVentanaGeneral objetoVentana;

    public VistaInventario() {
        initComponents();
        EncabezadoTblInventario = new String[]{
            "No",
            "Fecha",
            "Producto",
            "Entradas",
            "Salidas",
            "Existencia",
            "Mod",
            "Agr. Ent."
        };
        InicializarTblInventario();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        lbltitle1 = new javax.swing.JLabel();
        txtFiltro = new javax.swing.JTextField();
        jSeparator6 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_inventario = new Tablas.DiarioTable();
        btnFiltro = new javax.swing.JButton();
        btnAgregarProducto = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(59, 123, 50)));
        setLayout(new java.awt.GridBagLayout());

        lbltitle1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbltitle1.setForeground(new java.awt.Color(59, 123, 50));
        lbltitle1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbltitle1.setText("Filtro de busqueda");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(15, 15, 0, 15);
        add(lbltitle1, gridBagConstraints);

        txtFiltro.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtFiltro.setForeground(new java.awt.Color(59, 123, 50));
        txtFiltro.setBorder(null);
        txtFiltro.setCaretColor(new java.awt.Color(59, 123, 50));
        txtFiltro.setFocusCycleRoot(true);
        txtFiltro.setSelectionColor(new java.awt.Color(59, 123, 50));
        txtFiltro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFiltroActionPerformed(evt);
            }
        });
        txtFiltro.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtFiltroFocusLost(evt);
            }
        });
        txtFiltro.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtFiltroKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtFiltroKeyReleased(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipady = 15;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 15, 0, 0);
        add(txtFiltro, gridBagConstraints);

        jSeparator6.setBackground(new java.awt.Color(59, 123, 50));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.FIRST_LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(0, 15, 0, 0);
        add(jSeparator6, gridBagConstraints);

        tbl_inventario.setForeground(new java.awt.Color(59, 123, 50));
        tbl_inventario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbl_inventario.setFocusTraversalPolicyProvider(true);
        tbl_inventario.setGridColor(new java.awt.Color(59, 123, 50));
        tbl_inventario.setMaximumSize(new java.awt.Dimension(2147483647, 2147483647));
        tbl_inventario.setMinimumSize(new java.awt.Dimension(200, 200));
        tbl_inventario.setPreferredSize(new java.awt.Dimension(200, 200));
        tbl_inventario.setSelectionBackground(new java.awt.Color(59, 123, 50));
        tbl_inventario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                tbl_inventarioMouseReleased(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_inventario);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(10, 15, 15, 15);
        add(jScrollPane1, gridBagConstraints);

        btnFiltro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconos/buscar30.png"))); // NOI18N
        btnFiltro.setToolTipText("Agregar");
        btnFiltro.setBorderPainted(false);
        btnFiltro.setContentAreaFilled(false);
        btnFiltro.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnFiltro.setFocusPainted(false);
        btnFiltro.setMargin(new java.awt.Insets(2, 10, 2, 8));
        btnFiltro.setMaximumSize(new java.awt.Dimension(30, 30));
        btnFiltro.setMinimumSize(new java.awt.Dimension(30, 30));
        btnFiltro.setName("btnFiltro"); // NOI18N
        btnFiltro.setPreferredSize(new java.awt.Dimension(30, 30));
        btnFiltro.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconos/buscar30.png"))); // NOI18N
        btnFiltro.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconos/buscar30.png"))); // NOI18N
        btnFiltro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFiltroActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 15);
        add(btnFiltro, gridBagConstraints);

        btnAgregarProducto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconos/agregar30.png"))); // NOI18N
        btnAgregarProducto.setToolTipText("Agregar Producto");
        btnAgregarProducto.setBorderPainted(false);
        btnAgregarProducto.setContentAreaFilled(false);
        btnAgregarProducto.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAgregarProducto.setFocusPainted(false);
        btnAgregarProducto.setMargin(new java.awt.Insets(2, 10, 2, 8));
        btnAgregarProducto.setMaximumSize(new java.awt.Dimension(30, 30));
        btnAgregarProducto.setMinimumSize(new java.awt.Dimension(30, 30));
        btnAgregarProducto.setName("btnAgregar"); // NOI18N
        btnAgregarProducto.setPreferredSize(new java.awt.Dimension(30, 30));
        btnAgregarProducto.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconos/agregar30_over.png"))); // NOI18N
        btnAgregarProducto.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconos/agregar30_over.png"))); // NOI18N
        btnAgregarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarProductoActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 15);
        add(btnAgregarProducto, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    private void txtFiltroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFiltroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFiltroActionPerformed

    private void txtFiltroFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtFiltroFocusLost

    }//GEN-LAST:event_txtFiltroFocusLost

    private void txtFiltroKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFiltroKeyPressed

    }//GEN-LAST:event_txtFiltroKeyPressed

    private void txtFiltroKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFiltroKeyReleased
        String texto = txtFiltro.getText();
        if (texto.length() == 0) {
            return;
        }

        aplicarFiltro(texto);
    }//GEN-LAST:event_txtFiltroKeyReleased

    private void tbl_inventarioMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_inventarioMouseReleased
//        filaSeleccionada = tbl_LibroDiario.getSelectedRow();
//        int cola = tbl_LibroDiario.getSelectedColumn();
//        String dato = tbl_LibroDiario.getValueAt(filaSeleccionada, cola).toString();
//
//        if (band == 0) {
//            if (dato.equalsIgnoreCase("Modificar")) {
//                band = 1;
//                datoaModificar = ListaLibroMostrar.get(filaSeleccionada);
//                EditarRegistro();
//            } else if (dato.equalsIgnoreCase("Eliminar")) {
//
//            }
//        }
    }//GEN-LAST:event_tbl_inventarioMouseReleased

    private void btnFiltroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFiltroActionPerformed
        aplicarFiltro(txtFiltro.getText());
    }//GEN-LAST:event_btnFiltroActionPerformed

    private void btnAgregarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarProductoActionPerformed
        objetoVentana = new ModeloVentanaGeneral(this, new VistaProducto(), 1, null);
        VistaGeneral vis = new VistaGeneral(objetoVentana);
        vis.setVisible(true);
    }//GEN-LAST:event_btnAgregarProductoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarProducto;
    private javax.swing.JButton btnFiltro;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator6;
    public javax.swing.JLabel lbltitle1;
    public javax.swing.JTable tbl_inventario;
    public javax.swing.JTextField txtFiltro;
    // End of variables declaration//GEN-END:variables

    private void aplicarFiltro(String text) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    public void InicializarTblInventario() {
        tbl_inventario.setDefaultRenderer(Object.class, new TablaRender());

        modeloTblInventario = new DefaultTableModel(EncabezadoTblInventario, 0) {
            Class[] types = new Class[]{
                java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class,
                java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class,
                java.lang.Object.class, java.lang.Object.class
            };

            public Class getColumnClass(int col) {
                return types[col];
            }

            public boolean isCellEditable(int row, int col) {
                return false;
            }
        };

        tbl_inventario.setModel(modeloTblInventario);

        tbl_inventario.getColumnModel().getColumn(0).setPreferredWidth(10);
        tbl_inventario.getColumnModel().getColumn(1).setPreferredWidth(70);
        tbl_inventario.getColumnModel().getColumn(2).setPreferredWidth(200);
        tbl_inventario.getColumnModel().getColumn(3).setPreferredWidth(50);
        tbl_inventario.getColumnModel().getColumn(4).setPreferredWidth(50);
        tbl_inventario.getColumnModel().getColumn(5).setPreferredWidth(50);
        tbl_inventario.getColumnModel().getColumn(6).setPreferredWidth(10);
        tbl_inventario.getColumnModel().getColumn(7).setPreferredWidth(10);

        tbl_inventario.getTableHeader().setReorderingAllowed(false);

        for (int i = 0; i < modeloTblInventario.getColumnCount(); i++) {
            tbl_inventario.getColumnModel().getColumn(i).setResizable(false);
            DefaultTableCellRenderer tcr = new DefaultTableCellRenderer();
            tcr.setFont(new Font("Tahoma", 0, 12));
            tcr.setHorizontalAlignment(SwingConstants.CENTER);
            tcr.setForeground(new Color(59, 123, 50));
            tbl_inventario.getColumnModel().getColumn(i).setCellRenderer(tcr);

        }
        JTableHeader header = tbl_inventario.getTableHeader();

        ((DefaultTableCellRenderer) header.getDefaultRenderer()).setHorizontalAlignment(JLabel.CENTER);
        ((DefaultTableCellRenderer) header.getDefaultRenderer()).setPreferredSize(new Dimension(0, 35));
        ((DefaultTableCellRenderer) header.getDefaultRenderer()).setVerticalAlignment(JLabel.CENTER);

    }

}
