/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas.Inventario;

import Control.Inventario.ControlInventario;
import Control.Retorno;
import Modelo.Inventario.ModeloProducto;
import Modelo.ModeloVentanaGeneral;
import Utilidades.Utilidades;
import Utilidades.datosUsuario;
import Vistas.VistaGeneral;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.HashMap;
import java.util.Map;
import javax.swing.JOptionPane;

/**
 *
 * @author DOLFHANDLER
 */
public class VistaModificarProducto extends javax.swing.JPanel {

    private Map<String, String> producto;
    private String id_producto;
    private String idFinca;
    private VistaInventario vistaInventario;
    private VistaGeneral vistaGeneral;
    private ModeloProducto mProducto;
    private ControlInventario control;

    /**
     * Creates new form VistaModificarProducto
     */
    public VistaModificarProducto() {
        initComponents();
        setSize(294, 250);
    }

    public VistaModificarProducto(ModeloVentanaGeneral modeloVista) {
        initComponents();
        setSize(294, 250);
        mProducto = new ModeloProducto();
        control = new ControlInventario();
        producto = new HashMap<String, String>();
        producto = (HashMap<String, String>) modeloVista.getModeloDatos();
        vistaInventario = (VistaInventario) modeloVista.getPanelPadre();
        vistaGeneral = (VistaGeneral) modeloVista.getFrameVentana();
        cargarProducto(producto);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        txtProducto = new javax.swing.JTextField();
        cbTipo = new javax.swing.JComboBox();
        jPanel2 = new javax.swing.JPanel();
        btnGuardar1 = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(59, 123, 50)));
        java.awt.GridBagLayout layout = new java.awt.GridBagLayout();
        layout.columnWidths = new int[] {0, 15, 0, 15, 0, 15, 0, 15, 0};
        layout.rowHeights = new int[] {0, 10, 0, 10, 0, 10, 0, 10, 0};
        setLayout(layout);

        txtProducto.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtProducto.setForeground(new java.awt.Color(59, 123, 50));
        txtProducto.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(59, 123, 50)), "Nombre del producto", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12), new java.awt.Color(59, 123, 50))); // NOI18N
        txtProducto.setCaretColor(new java.awt.Color(59, 123, 50));
        txtProducto.setFocusCycleRoot(true);
        txtProducto.setSelectionColor(new java.awt.Color(59, 123, 50));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipady = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        add(txtProducto, gridBagConstraints);

        cbTipo.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        cbTipo.setForeground(new java.awt.Color(59, 123, 50));
        cbTipo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Selecciona...", "unidad", "peso", "metros" }));
        cbTipo.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(59, 123, 50)), "Tipo", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12), new java.awt.Color(59, 123, 50))); // NOI18N
        cbTipo.setEditor(null);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipady = -3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        add(cbTipo, gridBagConstraints);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new java.awt.GridBagLayout());

        btnGuardar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconos/guardar.png"))); // NOI18N
        btnGuardar1.setToolTipText("Guardar");
        btnGuardar1.setBorderPainted(false);
        btnGuardar1.setContentAreaFilled(false);
        btnGuardar1.setMargin(new java.awt.Insets(2, 10, 2, 8));
        btnGuardar1.setMaximumSize(new java.awt.Dimension(64, 64));
        btnGuardar1.setMinimumSize(new java.awt.Dimension(64, 64));
        btnGuardar1.setName("btnGuardar"); // NOI18N
        btnGuardar1.setPreferredSize(new java.awt.Dimension(64, 64));
        btnGuardar1.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconos/guardar_over.png"))); // NOI18N
        btnGuardar1.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconos/guardar_over.png"))); // NOI18N
        btnGuardar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardar1ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        jPanel2.add(btnGuardar1, gridBagConstraints);

        btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconos/cancelar.png"))); // NOI18N
        btnCancelar.setToolTipText("Eliminar");
        btnCancelar.setBorderPainted(false);
        btnCancelar.setContentAreaFilled(false);
        btnCancelar.setMargin(new java.awt.Insets(2, 10, 2, 8));
        btnCancelar.setMaximumSize(new java.awt.Dimension(64, 64));
        btnCancelar.setMinimumSize(new java.awt.Dimension(64, 64));
        btnCancelar.setName("btnCancelar"); // NOI18N
        btnCancelar.setPreferredSize(new java.awt.Dimension(64, 64));
        btnCancelar.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconos/cancelar_over.png"))); // NOI18N
        btnCancelar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconos/cancelar_over.png"))); // NOI18N
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        jPanel2.add(btnCancelar, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.gridwidth = 9;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.FIRST_LINE_START;
        gridBagConstraints.weightx = 1.0;
        add(jPanel2, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuardar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardar1ActionPerformed
        Guardar();
    }//GEN-LAST:event_btnGuardar1ActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        vistaGeneral.dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnGuardar1;
    public javax.swing.JComboBox cbTipo;
    private javax.swing.JPanel jPanel2;
    public javax.swing.JTextField txtProducto;
    // End of variables declaration//GEN-END:variables

    private void Guardar() {
        mProducto.setId(id_producto);
        mProducto.setEstado("Activo");
        mProducto.setFecha("NOW()");
        mProducto.setId_usuario(datosUsuario.datos.get(0).get("ID_USUARIO"));
        mProducto.setTipo_salida(cbTipo.getSelectedItem().toString());
        mProducto.setDescripcion(Utilidades.CodificarElemento(txtProducto.getText().trim()));

        int retorno = Retorno.DEFECTO;

        retorno = control.ActualizarProducto(mProducto);

        String mensaje = "";
        switch (retorno) {
            case Retorno.EXITO:
                mensaje = "El producto fue modificado con exito.";
                JOptionPane.showMessageDialog(this, mensaje);
                vistaInventario.AccionCombo();
                vistaGeneral.dispose();
                return;
            case Retorno.ERROR:
                mensaje = "El registro no pudo ser guardado.";
                JOptionPane.showMessageDialog(this, mensaje);
                return;
            case Retorno.EXCEPCION_SQL:
                mensaje = "Ocurrio un error en la base de datos\nOperación no realizada.";
                JOptionPane.showMessageDialog(this, mensaje);
                return;
            case Retorno.CLASE_NO_ENCONTRADA:
                mensaje = "Ocurrio un error con el conector de la base de datos\nOperación no realizada.";
                JOptionPane.showMessageDialog(this, mensaje);
                return;
        }
    }

    private void cargarProducto(Map<String, String> producto) {
        id_producto = producto.get("id_producto");
        idFinca = producto.get("id_finca");
        txtProducto.setText(producto.get("PRODUCTO"));
        cbTipo.setSelectedItem(producto.get("tipo_salida"));
    }

}
